### ISSUE TITLE
[Improvement] Make logo clickable

### ISSUE THREAD

**Issue by ramess18** [leiweibau/Pi.Alert#100]
Hi leiweibau,
I'd love to have Pi.Alert's logo clickable - link the same as title _Pi.Alert_ has.
![image](https://user-images.githubusercontent.com/16610727/225237363-9604932b-60d4-42f1-b2c6-00238e816b0e.png)
I think it will be useful for more of us. Many webs has this and users are used to it.
Thanks
Radim

**Comment by leiweibau** [comment]
It is done. It will be included in the next update
