### ISSUE TITLE
[Feature Request] Generate Reports

### ISSUE THREAD

**Issue by intheshell** [leiweibau/Pi.Alert#102]
Hello how are you?

Can the download of new device detection reports be integrated, online and offline? like a PDF / CSV

**Comment by intheshell** [comment]
Yes, of course, to the reports that can be seen in the dashboard, could some functionality be added to export them?

**Comment by leiweibau** [comment]
A download of the messages as PDF is implemented. The feature will be released with the next update.

Example of a report:
<img width="635" alt="report" src="https://user-images.githubusercontent.com/105860611/225979902-ad40c08d-1b3f-44bd-bac5-e36f1251be01.png">
