### ISSUE TITLE
[Documentation Request] Network Overview and Web Services

### ISSUE THREAD

**Issue by smibrandon** [leiweibau/Pi.Alert#104]
Hello-- Probably not the right place for this, but I'm gonna take a stab at it anyways.

Are there more docs that discuss the use of _Network Overview_ and _Web Services_ sections? I've always been a fan of everything PiAlert can offer, and I'm intrigued, but I just can't find anything that explains this. Thanks in advance!

**Comment by leiweibau** [comment]
Not currently, but I'll keep that in mind.

**Comment by leiweibau** [comment]
First update with https://github.com/leiweibau/Pi.Alert/commit/3e6ebe35aa3a31f11d47978d1d8466ab97009c59
