### ISSUE TITLE
No Mail notification in the latest build (2023-03-18)

### ISSUE THREAD

**Issue by Viking-1** [leiweibau/Pi.Alert#105]
Again: Pi-Alert is installed this way:

```
## update sources ##
apt-get update

apt-get install avahi-daemon
nano /etc/hosts

127.0.0.1	PiAlert.local

## add repository ##
apt install software-properties-common
add-apt-repository universe

## install curl ##
apt-get install curl

## Instal PiAlerts ##
curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh | bash
```
PiAlert is running and the config is set as followed:

```
Special Protocol Scanning
# ----------------------
SCAN_ROGUE_DHCP        = True
DHCP_SERVER_ADDRESS    = '192.168.1.1'

# Mail-Account Settings
# ----------------------
SMTP_SERVER       = 'smtp-server.de'
SMTP_PORT         = 465
SMTP_USER         = 'user@smtp-server.de'
SMTP_PASS         = 'xxxxxx'
SMTP_SKIP_TLS	  = False
SMTP_SKIP_LOGIN	  = False

# WebGUI Reporting
# ----------------------
REPORT_WEBGUI         = True
REPORT_WEBGUI_WEBMON  = True

# Mail Reporting
# ----------------------
REPORT_MAIL          = True
REPORT_MAIL_WEBMON   = True
REPORT_FROM          = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO            = 'pialert@server.de'
REPORT_DEVICE_URL    = 'http://pi.alert/deviceDetails.php?mac='
REPORT_DASHBOARD_URL = 'http://pi.alert/'
```

After sending a test notification, no mail is incoming. But the dashboard says, an email was sent.

And after testing it a second time, PiAlert goes into some kind of loop. The site is trying to reload but without effort. And if not reloading automatically: If you want to go to another site (like the dashboard), the PiAlert is loading forever. Only a reboot is working.

**Comment by leiweibau** [comment]
I just tested it on my end with no problems. I will work through your installation steps in the near future to test if I can reproduce the error pattern.

**Comment by leiweibau** [comment]
Okay.

But I would like to give you some more information:
- The test message, regardless of web interface or terminal, is executed by the pialert-cli. I actually set the appropriate permissions for that. If something is wrong here, feel free to contact me again to identify the problem.
- if Pi-hole is running on another server/VM, you can't use the Pi-hole support, because Pi.Alert likes to access the database locally.
- without the direct Pi-hole support you may not get the hostnames resolved.

**Comment by Viking-1** [comment]
I'm not using the Pi-Hole support. Just mentioning it. But I set the DNS to the Pi-Hole's IP in Proxmox.
So. My clean installation is done. Nothing changed or configured beside the Mail settings. Same behavior. Pi-Alert is loading forever, but Proxmox shows no load after all. No Mail will be sent.

**Comment by leiweibau** [comment]
Can you test it via pialert-cli in ./pialert/back/ ?

**Comment by Viking-1** [comment]
Yes, if you tell me, what I must do specifically.

**Comment by leiweibau** [comment]
Enter the shell of your ubuntu server. Move the the installdir (wars shown during installation), then to "./back" or ./pialert/back (full path). No run "./pialert-cli reporting_test"

**Comment by Viking-1** [comment]
Exactly after 5 minutes waiting time I get this:


```
Test Reporting...
    Sending report by email...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 2429, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 103, in main
    res = email_reporting_test('Test')
  File "/root/pialert/back/pialert.py", line 2177, in email_reporting_test
    send_email (notiMessage, notiMessage)
  File "/root/pialert/back/pialert.py", line 2346, in send_email
    smtp_connection = smtplib.SMTP (SMTP_SERVER, SMTP_PORT)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
Test executed
```

**Comment by leiweibau** [comment]
1. why is your group „staff“, it should be "www-data"
2. There should be even different directories with "www-data" as group
3. According to your error message, the server seems to disconnect. Has it ever worked with this configuration? Is there a possibility that the server is blocking your IP because of suspected spam?

It's difficult at the moment, but I'll set up an Ubuntu Server 2022.4 VM as soon as I can and run through your setup as far as possible

**Comment by Viking-1** [comment]
1. I don't know. I used the curl command from above (curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh | bash). And I haven't changed anything so far after the installation is done. At this point I hope you can tell me.
2. It never worked before, but the credentials are the same for every other client/app like Thunderbird, my Speedtest-Server, Proxmox, Spark, ...

I can try a step by step installation later this day.

**Comment by leiweibau** [comment]
Once again to the configuration:
Port 465 is, as far as I could find out, for SMTP over SSL. Does your provider not support TLS? Without knowing everything, you could test the SMTP_SKIP_TLS = True function.
