### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by JYewdall** [leiweibau/Pi.Alert#107]
curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh | bash

############################################################
 Pi.Alert Update
############################################################
Mon 20 Mar 14:46:11 GMT 2023
Logfile: pialert_update_2023-03-20_14-46.log

- Checking Python...
- Reset permissions...
- Creating new Pi.Alert backup...
........................................................................................
- Cleaning previous version...
- Checking package apt-utils...
- Checking package sqlite3...
- Checking packages dnsutils & net-tools...
- Checking packages php-curl...
- Downloading update file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 78.9M  100 78.9M    0     0  5630k      0  0:00:14  0:00:14 --:--:-- 11.1M

- Uncompressing tar file
................................................................................
- Deleting downloaded tar file...
- Config backup...
- Updating config file...
- Updating DB permissions...
- Installing sqlite3...
- Checking Devices new columns...
  - Adding column 'Model' to 'Devices'...
Error: attempt to write a readonly database

**Comment by leiweibau** [comment]
That may be so. Was a scan running during the update? From the time, that could have been the case. You can simply pause the scan and wait a few minutes (you can see on the settings page if a scan is running). Then do the update again.

**Comment by JYewdall** [comment]
Still the same error. I have disabled the arp-scan for 60 minutes.
scan log viewer says 'It is probably currently running scan' All other logs are 'no log available'
I can download the dbbackup but it is 5 hours old.

**Comment by leiweibau** [comment]
The scan is normally performed every 5min. However, if the scan is already running, then the scan is disabled for next run.

Do I understand you correctly that even current scans are no longer stored in the database because the database is "read only"? If no scan is running at the moment, you should restore the backup and then run the update again.

**Comment by JYewdall** [comment]
uninstalled, reinstalled, update script works. Restore my dbbackup and update script errors so starting from scratch.

**Comment by leiweibau** [comment]
Thanks for the feedback. It's unfortunate that you now had to start from scratch. Your case shows me that I need to take more precautions when updating. I may also need to add an integrity check (don't know how to do that yet) to the backup function.

**Comment by JYewdall** [comment]
An indication that a scan was taking place would be nice, maybe a change in colour of the top bar or somewhere.

**Comment by leiweibau** [comment]
Whether a scan is currently running can be seen on the settings page in the status box. I have now changed the update script a bit. In the future I will run database update again exclusively via the PHP or Python scripts and not via the update script.

**Comment by leiweibau** [comment]
Added warning message at the beginning of the update. Database updates are now again made during runtime and not within the update process.
