### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Viking-1** [leiweibau/Pi.Alert#108]
![grafik](https://user-images.githubusercontent.com/125771058/226572174-add6a92d-e7fa-430e-a57c-a4ebe77bd5eb.png)
Just wondering if the amount of decimal numbers in the load section are correct. If not, can I change it somewhere?
Compared to PiHole:
![grafik](https://user-images.githubusercontent.com/125771058/226572378-07de1e1f-b0cf-4730-bc47-f875f27b79fb.png)

**Comment by leiweibau** [comment]
I am also wondering since the function used only returns values with 2 decimal places. I have also never seen such long values in my case.  However, I can add a rounding function to eliminate the error. Nevertheless, I do not have an explanation for this.

**Comment by leiweibau** [comment]
Should be fixed with latest update. (https://github.com/leiweibau/Pi.Alert/commit/73ccf4fddb4aaac10e28ef2f7f3f3f1e3d82873a)
