### ISSUE TITLE
unable to install on dietpi

### ISSUE THREAD

**Issue by voxie12** [leiweibau/Pi.Alert#110]
i tried to install pialert on dietpi but lighttpd failed.

![image](https://user-images.githubusercontent.com/65469239/227776960-4fbb4e5f-bdbf-4d91-bab0-2363e38dce46.png)

![image](https://user-images.githubusercontent.com/65469239/227777026-8125fd8a-701e-43d4-ae1d-229a58521971.png)

**Comment by leiweibau** [comment]
I also can't tell you exactly why lighttpd won't install for you?

Do you already have another web server installed (apache, nginx)? You can use the command `sudo netstat -tulpn | grep LISTEN` to see which ports are used. Port 80 should be free.

You can check `/var/log/lighttpd/` for logs.
You can run `sudo journalctl -xe | grep lighttpd`
I am currently using a clean dietpi (8.15.2) installation for testing and have not experienced your error yet.

**Comment by voxie12** [comment]
everything is working fine. i reinstall dietpi and put ```curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh | bash```. thats why pihole wasnt working well with pialert from dietpi-software.

i installed unbound from dietpi-software and everything stopped working...

i will redo everything and install unbound first then that

**Comment by NossieUK** [comment]
do you mind confirming the process you used to resolve this?
