### ISSUE TITLE
How to add unmanaged Switches?

### ISSUE THREAD

**Issue by myssv** [leiweibau/Pi.Alert#111]
I have two unmanaged switched and would also add them to the network list.

Is that possible?

**Comment by leiweibau** [comment]
Adding an unmanaged switch to the network list is possible. However, you cannot add it to the device list.

<img width="434" alt="screen" src="https://user-images.githubusercontent.com/105860611/227779972-1f80d1d1-484f-4498-b698-f60b6829425f.png">

After that the switch appears as "Uplink Target" in the Device Details page.

**Comment by myssv** [comment]
Great!

Thanks a lot for your fast Answer!
