### ISSUE TITLE
Rechner immer wieder als Offline gemeldet obwohl durchgehend an

### ISSUE THREAD

**Issue by myssv** [leiweibau/Pi.Alert#113]
Mein Rechner wird vom System immer mal wieder als Offline gemeldet, obwohl er durchgehend an war. Ich schreibe auch gerade an ihm obwohl er als Offline angezeigt wird:

![image](https://user-images.githubusercontent.com/65643813/228320225-b37ee05a-4851-47a1-8af1-6a0d281e0f54.png)

Woran könnte das liegen?

**Comment by leiweibau** [comment]
Das könnte mehrere Ursachen haben. Ist der Rechner via WLAN oder Ethernet angebunden? Sind mehrere Switches involviert? Ist der Rechner immer an, oder geht er vielleicht nach einiger Zeit in den Ruhezustand oder Standby? Du kannst hier auch mal in die Energieeinstellungen deines Rechners schauen.

Du könntest testweise probieren, den Wert von "retry" zu erhöhen (vielleicht 8, oder 10). Mache hierfür aber eine Sicherung von originalen Script.
https://github.com/leiweibau/Pi.Alert/blob/3458130a072a391d777c3b41894f909614f2f1b4/back/pialert.py#L634
Mit der Erhöhung der Retries verlängert sich auch die Scandauer, bitte bedenke dies.

**Comment by myssv** [comment]
Der Rechner war die ganze Zeit an und in Benutzung. Er ist per Ethernet über 2 Switche mit dem Pi.Alert Server verbunden.

Dies war es leider auch nicht:
![image](https://user-images.githubusercontent.com/65643813/228366638-43843943-fc71-4820-892e-5b2b571ff87d.png)

Ich habe inzwischen 49 Geräte eingebunden und nur bei meinem Rechner passiert es. Ich denke es müsste was lokales sein, habe aber keine Idee mehr.

Ich habe den retry-Wert mal auf 8 erhöht.

Danke!

**Comment by leiweibau** [comment]
Gib gern noch mal Rückmeldung.

**Comment by myssv** [comment]
Ohne Erfolg!

Ich bin seit ca. 22:45h durchgehend am Rechner aktiv:

![image](https://user-images.githubusercontent.com/65643813/228377430-f48de540-55dc-4e58-9248-f460ba8bc2cb.png)

**Comment by leiweibau** [comment]
Da bin ich gerade etwas überfragt. Aus irgend einem Grund muss ich immer an IPv6 denken, kann dir aber hier nicht sagen, ob das wirklich eine Ursache sein könnte.

Der zugrundelliegende arp-scan klopft ja jede IP des eigenen Subnet ab und liefert, wenn der Host antwortet eine MAC-Adresse zurück. Dies probiert er, entsprechend der retry Variabel "n" mal. Nun ist die Frage, ob die Anfrage nicht zum Rechner kommt, oder ob der Rechner diese Anfrage verwirft? Wenn der Rechner IPv6 verwendet, dann funktioniert der arp-scan nicht. In dem Fall kommt dann "ndp" zum Einsatz. Warum sollte aber das Betriebssystem dann nicht mehr auf IPv4 reagieren? Ich bin also selbst gerade etwas überfragt.

**Comment by myssv** [comment]
Ich nutze eigentlich nur IP V4, aber auf der Netzwerkkarte war noch IP V6 aktiv. Das habe ich jetzt mal deaktiviert.

Ich beobachte weiter.

**Comment by myssv** [comment]
Das scheint geholfen zu haben. Seit dem ist Ruhe ...

![image](https://user-images.githubusercontent.com/65643813/228490396-fa98a1ef-c437-41de-8947-3fb675c136e4.png)

**Comment by leiweibau** [comment]
Das freut mich, jedoch kann ich mir es trotzdem nicht so richtig erklären.

**Comment by myssv** [comment]
Er hat erkannt, dass ich vorhin den Rechner ausgemacht habe:

![image](https://user-images.githubusercontent.com/65643813/228510414-4e112c4f-dcf6-4084-8c28-f56584f8de1d.png)

Aber nun ist er seit 20 Minuten wieder an und das merkt er nicht.

**Comment by myssv** [comment]
Ich habe eine 1GBit Netzwerkkarte on Board und habe dann eine RealTek 2,5GBit Netzwerkkarte eingebaut. Damit hatte ich Probleme und habe nun eine Intel 2,5GBit Karte drin, die mit voller Geschwindigkeit läuft. Daher die (3)

Nun, um 13:15h hat er mich gefunden.

**Comment by myssv** [comment]
Kommando zurück ...  Es passiert auch weiterhin

![image](https://user-images.githubusercontent.com/65643813/228595979-2829953f-ec68-4eb8-aca1-416391778991.png)

**Comment by leiweibau** [comment]
So leid es mir tut, aber ich glaube, ich kann dir im Moment nicht helfen, da ich selber auch keine Erklärung dafür habe :(

**Comment by myssv** [comment]
Das glaube ich Dir. Ist aber aktuell auch kein Problem. Ich weiß ja, wann der Rechner an ist und wann nicht ;-)
