### ISSUE TITLE
Last Session not up to date

### ISSUE THREAD

**Issue by juancabrio** [leiweibau/Pi.Alert#114]
Hi,

Maybe I've missed the point of the dev_lastConnection field in the devices table.   I presumed if a device is online then dev_lastConnection would reflect the last time  arp-scan was run and picked up the MAC.  So everything that's online today would reflect todays date in dev_lastConnection.  So then if turned something off yesterday I'd see yesterdays date in dev_lastConnection field being the last time it was online.   
This is not what I'm seeing.   What is the expected behavior ?  I wanna see the first time a MAC was visible and the last time.   
Cheers

Juan

**Comment by leiweibau** [comment]
Thanks for your report.
So far I've kept my hands off the session handling, but I'll take a look at it in the next few days. Then I can give you a detailed explanation and maybe make necessary adjustments.

**Comment by leiweibau** [comment]
"dev_lastConnection" contains the time when the device started the last/current session.

Example:
Device "Alpha" was detected for the first time on 2023.02.23 10:35am. Every day 8am the device starts and connects to the network. Every evening at 17 o'clock it switches off again.

"dev_FirstConnection" contains "2023.02.23 10:35".

If it is right now 2023.04.14 7:50am, then the column "dev_LastConnection" contains "2023.04.13 8:00" (The session from the day before).
If it is right now "2023.04.14 9:00" early, then the "dev_LastConnection" column contains "2023.04.14 8:00" (The current session).

Perhaps it should rather be understood as "Last connection established".

**Comment by juancabrio** [comment]
ok got it.  That makes sense.  So I could presume if dev_LastConnection" contains "2023.04.13 8:00 and today being the 14th, the device is still online, it has been online ever since 2023.04.13 8:00. 

Appreciate the clarification.   :)

Juan
