### ISSUE TITLE
After Update to the latest version

### ISSUE THREAD

**Issue by lastsamurai26** [leiweibau/Pi.Alert#115]
```
- Testing Pi.Alert HW vendors database update process...
*** PLEASE WAIT A COUPLE OF MINUTES...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 20, in <module>
    from fritzconnection.lib.fritzhosts import FritzHosts
ImportError: No module named fritzconnection.lib.fritzhosts

- Testing Pi.Alert Internet IP Lookup...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 20, in <module>
    from fritzconnection.lib.fritzhosts import FritzHosts
ImportError: No module named fritzconnection.lib.fritzhosts

- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 20, in <module>
    from fritzconnection.lib.fritzhosts import FritzHosts
ImportError: No module named fritzconnection.lib.fritzhosts
```

I used the latest version but I have 2 Python versions installed because I have a script that does not run on Python3. 
I suspect that he has not installed the two plugins

~ $ python -V
Python 2.7.16
~ $ python3 -V
Python 3.7.3

**Comment by leiweibau** [comment]
Thank you for reporting

You can check if everything is installed by changing to the directory `~/pialert/back` and running `python3 pialert.py`. If this works without errors, then everything is installed correctly.

If the modules are missing, you can install them with the following commands.
```
pip3 install mac-vendor-lookup
pip3 install fritzconnection
```

Please check the cronjob for the user under which Pi.Alert is installed.

`crontab -e`
"python3" should be used, not "python".

I will check the update script in the next few days

**Comment by lastsamurai26** [comment]
```
python3 pialert.py update_vendors

Pi.Alert  (2023-04-13)
---------------------------------------------------------
Current User: pi 

Update HW Vendors
    Timestamp: 2023-04-16 08:43:00

Updating vendors DB (iab & oui)...
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%
################################################################################################################################################################## 100,0%

Searching devices vendor......................
    Devices Ignored:   1
    Vendors Not Found: 1
    Vendors updated:   20
Traceback (most recent call last):
  File "pialert.py", line 2549, in <module>
    sys.exit(main())       
  File "pialert.py", line 111, in main
    res = update_devices_MAC_vendors()
  File "pialert.py", line 423, in update_devices_MAC_vendors
    mac.update_vendors()
  File "/home/pi/.local/lib/python3.7/site-packages/mac_vendor_lookup.py", line 119, in update_vendors
    return self.loop.run_until_complete(self.async_lookup.update_vendors(url))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/mac_vendor_lookup.py", line 69, in update_vendors
    line = await response.content.readline()
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/streams.py", line 311, in readline
    return await self.readuntil()
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/streams.py", line 343, in readuntil
    await self._wait("readuntil")
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```


The modules are installed but I still get an error message and sometimes it hangs.
after the update 
Searching devices vendor......................



tried to reinstall pialert 

- Checking Python 2...
  - Python 2 is installed
    - Python 2.7.16
- Checking Python 3...
  - Python 3 is installed
    - Python 3.7.3
- Using the available Python version installed
  - Python 3 is available
- Using Python 3
E: Paket python-is-python3 kann nicht gefunden werden.


i deleted the python-is-python3 from the apt command

**Comment by leiweibau** [comment]
This message does not come directly from Pi.Alert, but from the new module "
mac-vendor-lookup". As I interpret the message, the module probably can't perform the download of the vendor data. I will have a look later. However, Pi.Alert should still work.

**Comment by lastsamurai26** [comment]
Pialert works by itself only this error message during installation makes me wonder. The modules were all installed and also work.

I hope I can help with the fix somehow

**Comment by leiweibau** [comment]
If the message bothers you, you can disable the code that generates the message.


Just comment out the two lines below it.
https://github.com/leiweibau/Pi.Alert/blob/8e70cfbfd3d51d6ce0a08361de49243dde6d8d05/back/pialert.py#L421

**Comment by leiweibau** [comment]
Maybe you could test for me if the error changes if you make the following change in the file "/home/pi/.local/lib/python3.7/site-packages/mac_vendor_lookup.py".

Line 10:
OUI_URL = "http://standards-oui.ieee.org/oui.txt"
to 
OUI_URL = "https://standards-oui.ieee.org/oui.txt"

**Comment by lastsamurai26** [comment]
I will test this in the next few days, since I am currently on the road a lot and can not access my Pi's.

**Comment by leiweibau** [comment]
I have updated the Pi.Alert update script and adjusted the vendor update. In the best case everything should work now.

**Comment by lastsamurai26** [comment]
for now it seams to work 

but i will do a couple of tests
