### ISSUE TITLE
Not scanning after update

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#116]
Hey,

I recently updated to the latest version (thank you for all the additional fields).

However, I've noticed it's not picking up on new devices. I've restarted the server but nothing is happening.

I checked and arp scans are set to enabled, so I pressed the "scan" button to do it manually and got this:
```Traceback (most recent call last):
File "/root/pialert/back/pialert.py", line 20, in
from fritzconnection.lib.fritzhosts import FritzHosts
ModuleNotFoundError: No module named 'fritzconnection'```

So I installed fritzconnection:
```pip3 install fritzconnection```

But still doesn't appear to be working.

I also tried to update the vendor database and now when I click the "Scan" button I get:
```Traceback (most recent call last):
File "/root/pialert/back/pialert.py", line 21, in
from mac_vendor_lookup import MacLookup
ModuleNotFoundError: No module named 'mac_vendor_lookup'```

I've no idea what's going on, can you help please?

Thanks.

**Comment by leiweibau** [comment]
try to install mac_vendor_lookup

sudo pip3 install mac-vendor-lookup
sudo pip3 install fritzconnection

**Comment by TheCableGuy99** [comment]
Hey, thanks for the fast reply.

One is already installed and one installed:
```root@pialert:~/pialert/config# sudo pip3 install mac-vendor-lookup
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mac-vendor-lookup
  Downloading mac_vendor_lookup-0.1.12-py3-none-any.whl (350 kB)
     |████████████████████████████████| 350 kB 4.7 MB/s
Collecting aiofiles
  Downloading https://www.piwheels.org/simple/aiofiles/aiofiles-23.1.0-py3-none-any.whl (14 kB)
Collecting aiohttp
  Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 17.3 MB/s
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (159 kB)
     |████████████████████████████████| 159 kB 18.3 MB/s
Collecting charset-normalizer<4.0,>=2.0
  Downloading charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (196 kB)
     |████████████████████████████████| 196 kB 18.5 MB/s
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (116 kB)
     |████████████████████████████████| 116 kB 18.4 MB/s
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (265 kB)
     |████████████████████████████████| 265 kB 18.4 MB/s
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Downloading https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting attrs>=17.3.0
  Downloading https://www.piwheels.org/simple/attrs/attrs-23.1.0-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.7 MB/s
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->mac-vendor-lookup) (2.10)
Installing collected packages: multidict, frozenlist, yarl, charset-normalizer, attrs, async-timeout, aiosignal, aiohttp, aiofiles, mac-vendor-lookup
Successfully installed aiofiles-23.1.0 aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 charset-normalizer-3.1.0 frozenlist-1.3.3 mac-vendor-lookup-0.1.12 multidict-6.0.4 yarl-1.9.2```


```root@pialert:~/pialert/config# sudo pip3 install fritzconnection
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: fritzconnection in /usr/local/lib/python3.9/dist-packages (1.12.0)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from fritzconnection) (2.25.1)```

Running the script in the /back directory (update_vendors.sh) works (also worked before I installed as above) but still when I click the button in the web interface it just shows:

```Pi.Alert (2023-03-11)
---------------------------------------------------------
Current User: root

Update HW Vendors
Timestamp: 2023-05-01 03:00:00

Updating vendors DB (iab & oui)...

Searching devices vendor..........................................................................................................
Devices Ignored: 1
Vendors Not Found: 9
Vendors updated: 96```

Doesn't appear to be doing arp scan either still :/

**Comment by leiweibau** [comment]
> I checked and arp scans are set to enabled, so I pressed the "scan" button to do it manually and got this

Just a note, because I think there is a misunderstanding here
The button "Scan" in the box "Log viewer". You open here the scan log and do not start a manual Scan

to run the scan via commandline run `/root/pialert/back/pialert.py 1`

**Comment by TheCableGuy99** [comment]
Ahh okay, sorry about that.

I'm running another scan now in the CLi but getting this error:

```Scanning...
    arp-scan Method...
    arp-scan: Multiple interfaces
    Pi-hole Method...
    DHCP Leases Method...
    Fritzbox Method...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 2561, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 117, in main
    res = scan_network()
  File "/root/pialert/back/pialert.py", line 518, in scan_network
    read_fritzbox_active_hosts()
  File "/root/pialert/back/pialert.py", line 719, in read_fritzbox_active_hosts
    if not FRITZBOX_ACTIVE :
NameError: name 'FRITZBOX_ACTIVE' is not defined```

Thanks pal.

**Comment by leiweibau** [comment]
Please check if you have the following entries in pialert.conf. 

# Fritzbox Configuration
# ----------------------
FRITZBOX_ACTIVE   = False
FRITZBOX_IP       = '192.168.17.1'
FRITZBOX_USER     = 'user'
FRITZBOX_PASS     = 'password'

Actually, the new updatescript should have updated all these things.

**Comment by TheCableGuy99** [comment]
Yeah that wasn't in there so i'll add it.

Is there anything else I should be checking if it's in there / changed I need to update?

Also I thought it used to scan every 5 minutes (could be wrong) but would like to set it to every 5 minutes. Is there a way to set it to scan every 5 minutes?

Thanks again.

**Comment by leiweibau** [comment]
So everything works now?

> Also I thought it used to scan every 5 minutes (could be wrong) but would like to set it to every 5 minutes. Is there a way to set it to scan every 5 minutes?

Yes, the scan starts every 5min. And what do you want to set now?

**Comment by TheCableGuy99** [comment]
Yeah it's scanning now, and yes it does appear to be doing it every 5 minutes. I just thought it had changed because there's no option to set it to 5 minutes in the web interface. The smallest time is 15 minutes so I leave it un-set.

However, there is an error still when running the script:
```Reporting...
    Formating report...
    Sending report by email...
    Skip PUSHSAFER...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 2561, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 128, in main
    email_reporting()
  File "/root/pialert/back/pialert.py", line 2122, in email_reporting
    if REPORT_PUSHOVER :
NameError: name 'REPORT_PUSHOVER' is not defined```

Even though it works and the email comes through it does seem to be alerting me every time it scans even though it's added it as an unknown device. 

Is there a way it can just notify me once when it discovers the new device and adds it?

Cheers.

**Comment by leiweibau** [comment]
Add this to your config file

```
# Pushover
# ----------------------
REPORT_PUSHOVER         = False
REPORT_PUSHOVER_WEBMON  = False
PUSHOVER_TOKEN          = '<Token>'
PUSHOVER_USER           = '<User>'
```

**Comment by TheCableGuy99** [comment]
Okay, not sure if that's to fix the error above or the duplicate notifications or both?

So i've added it, rebooted the pi and re-run the scan manually. Scan finished with no errors (yayyy, thank you).

Just going delete a device and let it pick it up manually, email me and see if it sends me a duplicate notification on the next scan.

I'll let you know shortly if all is well after a bit of testing.

Thanks again for the super fast help :)

**Comment by leiweibau** [comment]
To run the scan every 5 minutes, you must type `crontab -e`
```
0 3 * * 1      python3 ~/pialert/back/pialert.py update_vendors >~/pialert/log/pialert.vendors.log  2>&1
*/1 * * * *    python3 ~/pialert/back/pialert.py internet_IP    >~/pialert/log/pialert.IP.log       2>&1
*/5 * * * *    python3 ~/pialert/back/pialert.py 1              >~/pialert/log/pialert.1.log        2>&1
0 2 * * */4    python3 ~/pialert/back/pialert.py cleanup        >~/pialert/log/pialert.cleanup.log  2>&1
```
It should look something like this

**Comment by TheCableGuy99** [comment]
Nearly the same:
`0 3 * * 1      python3 ~/pialert/back/pialert.py update_vendors >~/pialert/log/pialert.vendors.log  2>&1
*/3 * * * *    python3 ~/pialert/back/pialert.py internet_IP    >~/pialert/log/pialert.IP.log       2>&1
*/5 * * * *    python3 ~/pialert/back/pialert.py 1              >~/pialert/log/pialert.1.log        2>&1
0 2 * * */4    python3 ~/pialert/back/pialert.py cleanup        >~/pialert/log/pialert.cleanup.log  2>&1`

I've updated internet IP to check every minute like yours now as well.

I'll let you know shortly regarding the duplicate emails :)

**Comment by TheCableGuy99** [comment]
Everything is looking great now, thanks so much pal :)

**Comment by leiweibau** [comment]
How did you perform the update?

**Comment by TheCableGuy99** [comment]
The only way I could see....

There's a script in the install directory called "pialert_update.sh" so ran that.

**Comment by leiweibau** [comment]
Okay, this explains the problem.
To update please always use `curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh | bash`, because I have to make additional changes for some new functions.

**Comment by TheCableGuy99** [comment]
In fairness that is in the readme (just checked) so sorry about that. Maybe add something to delete itself from the drive after it's updated so people don't do it by mistake like I did it?

Thanks again.

**Comment by leiweibau** [comment]
No problem. I just created a new readme in the "install" directory and will give a hint here again.
Don't worry about it. It shows me as a maintainer that there is still one or the other place which is not intuitive.
