### ISSUE TITLE
[Feature Request] Create docker build

### ISSUE THREAD

**Issue by p1ranha** [leiweibau/Pi.Alert#117]
Hello,

it would be perfect if you could publish the docker build, as this fork seems to be the best out of all.

Regards
Robert

**Comment by leiweibau** [comment]
Thank you for the compliment.
I have absolutely no idea how to do this. I would absolutely need help here.

**Comment by TheCableGuy99** [comment]
If you do, please don't ever stray away from this version as I need it for multiple vLANs which isn't as easy with docker containers. It can be done, it's just not as easy which is why I went for this version over the docker version that's already out there.

**Comment by leiweibau** [comment]
Don't worry. I maintain this version for the reason that I personally don't really like Docker. So if I really do a Docker build, it will be done in a separate repository.

**Comment by TheCableGuy99** [comment]
Great, it's one of my favourite little servers!

**Comment by roger-** [comment]
I second this request. Would make testing this much easier if there was docker support. Maybe the Dockerfile from [another fork](https://github.com/jokob-sk/Pi.Alert/blob/main/Dockerfile) could be modified?

**Comment by leiweibau** [comment]
I have created a new repository where I will be happy to receive and test pull requests. Without support, I will give the Docker version a subordinate importance.

https://github.com/leiweibau/Pi.Alert-docker

**Comment by leiweibau** [comment]
Since there has been no support for creating a Docker build in the last few weeks, but now, on the part of Github, a security notice has been received for my first attempt of a build, I have deleted the repository again.

For this reason, I will now also close this feature request, since there is obviously no greater need.
