### ISSUE TITLE
ImportError: No module named fritzconnection.lib.fritzhosts  AND fix for Encoding for pialert.py update_vendors

### ISSUE THREAD

**Issue by herbiegreenfield** [leiweibau/Pi.Alert#118]
One-step Automated Install: Results in Problem with python-is-python3

Attempted to step through manually. 

Attempting to install today but get errors related to pialert.py — tried with both python and python3, and got different errors.  Python (2) was corrected by additional line in pialert.py to specify encoding. I guessed and used Latin-1.

```
#!/usr/bin/python
# -*- coding: latin-1 -*-
```

From Manual step 
5.6 - Update vendors DB
python3 ~/pialert/back/pialert.py update_vendors

####
```
pi@pihole:~/pialert $ python ~/pialert/back/pialert.py update_vendors
  File "/home/pi/pialert/back/pialert.py", line 434
SyntaxError: Non-ASCII character '\xc3' in file /home/pi/pialert/back/pialert.py on line 434, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

```
pi@pihole:~/pialert $ python ~/pialert/back/pialert.py update_vendors
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 21, in <module>
    from fritzconnection.lib.fritzhosts import FritzHosts
ImportErrorw: No module named fritzconnection.lib.fritzhosts
```

# or python3

python3 ~/pialert/back/pialert.py update_vendors

####
```
pi@pihole:~/pialert $ python3 ~/pialert/back/pialert.py update_vendors
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 20, in <module>
    from fritzconnection.lib.fritzhosts import FritzHosts
ModuleNotFoundError: No module named 'fritzconnection'
```
####

**Comment by herbiegreenfield** [comment]
I commented out the Fritzbox line. Then encountered similar error for mac_vendor_lookup. 


```
pi@pihole:~ $ python3 ~/pialert/back/pialert.py update_vendors
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 21, in <module>
    from mac_vendor_lookup import MacLookup
ModuleNotFoundError: No module named 'mac_vendor_lookup'
```


Perhaps a solution for a second error for no module found for mac_vendor_lookup:

https://pypi.org/project/mac-vendor-lookup/
# Installation
pip install mac-vendor-lookup

**Comment by leiweibau** [comment]
You're right. The "manual" installation instructions are not up to date. I will correct this.

**Comment by leiweibau** [comment]
I have updated the installation instructions with https://github.com/leiweibau/Pi.Alert/commit/8dd785fc0f6516319ce61dc8c3eb91347799e0c7
