### ISSUE TITLE
Restore existing DB

### ISSUE THREAD

**Issue by PdreiK** [leiweibau/Pi.Alert#123]
Hi there,
you mentioned " If you backup the database, it may be possible to continue using it with my fork after a patch.". Is there any patch available yet? I am using the Pucherot original version and would really like to keep my records and the devices.
best regards,
Peter
PS: I know, this is not an issue, but I can not find any contact information.

**Comment by PdreiK** [comment]
Thanks !
It worked at first try, on my test-system, of course. Will apply it onto my raspi tomorrow.

**Comment by leiweibau** [comment]
Great. Please keep that in mind https://github.com/leiweibau/Pi.Alert/issues/122
