### ISSUE TITLE
Debian 12: pip3 install causes an error (externally-managed-environment)

### ISSUE THREAD

**Issue by jniggemann** [leiweibau/Pi.Alert#129]
Vanilla Debian 12 throws the following error:
```
------------------------------------------------------------
 Python
------------------------------------------------------------
- Checking Python 2...
  - Python 2 is NOT installed

- Checking Python 3...
  - Python 3 is installed
    - Python 3.11.2

- Using the available Python version installed
  - Python 3 is available

- Using Python 3
    - Install additional packages
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by leiweibau** [comment]
Thank you for the report. Currently I do not have Debian 12 in use yet. I will have to take care of this issue in the near future.

**Comment by jniggemann** [comment]
Thank you, that's a fast reply :-)

For my lab, I've added `--break-system-packages` to the 2 pip calls. Install then gets fairly far, before it bails out again because of a missing `install/pialert-cli.autocomplete` (would you like a separate isse for that?). Once I manually added that file, it got to a usable point.

**Comment by leiweibau** [comment]
Yes, I was working on that (adding new features). 5min ago I uploaded an updated package. Now it should work.

**Comment by jniggemann** [comment]
> Wir können uns auch auf deutsch unterhalten, wenn Bedarf besteht.
Nah, let's stick to English so more people finding this can read and understand.

Just dumped the whole LXC and made a new one with the new package.
Deleted `/usr/lib/python3.11/EXTERNALLY-MANAGED` and installed - worked without issues.

I don't think that is an option for many - I wouldn't do this outside a lab setting.
Would you like keep this open until properly resolved? If not, I'd close it.

**Comment by leiweibau** [comment]
I will keep the issue open.
I see it the same way. I currently have no idea how to solve the problem, but maybe there is a pull request.

**Comment by Cybervoidx** [comment]
Hi leiweibau,
ich habe leider das selbe Problem. Sowohl auf Ubuntu 23.04 als auch auf Debian 12.
Gibt es hierfür schon eine Lösung respektive einen praktikablen Workaround?

**Comment by Cybervoidx** [comment]
Nevermind - wie @jniggemann bereits erwähnte, hilft es tatsächlich erstmal `/usr/lib/python3.11/EXTERNALLY-MANAGED` zu löschen und das Skript anschließend erneut auszuführen.

Danke an dieser Stelle!

**Comment by leiweibau** [comment]
> Gibt es hierfür schon eine Lösung respektive einen praktikablen Workaround?

Leider habe ich, abseits des Workaround von @jniggemann und des pip3 Parameter "--break-system-packages" noch keine Möglichkeit gefunden die benötigten Pakete sowohl für www-data als auch für den installierenden Benutzer zu installieren. Ich habe mal ein extra Installationsscript für Debian 12 erstellt.

Da ich mit dieser Lösung nicht so richtig glücklich bin, lasse ich den Issue noch offen, in der Hoffnung, dass eine bessere Lösung gefunden wird.

 <hr>

Unfortunately, apart from the workaround by @jniggemann and the pip3 parameter "--break-system-packages", I have not yet found a way to install the required packages for www-data as well as for the installing user. I have created an extra installation script for Debian 12.

Since I'm not really happy with this solution, I'll leave the issue open for now in the hope that a better solution will be found.

**Comment by leiweibau** [comment]
Debian 12 installation script verified
https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install_debian12.sh
