### ISSUE TITLE
[Feature Request] Ignore devices based on their IP

### ISSUE THREAD

**Issue by upD8R** [leiweibau/Pi.Alert#130]
Hi there,

I posted [a question in the Pihole forum](https://discourse.pi-hole.net/t/restrict-network-table-to-specific-interface/63735) but I'd like to share my "pain "also here as it would be more important to having a clean Pi.Alert than a clean Pihole network table.

AFAIK you fetch directly the (network table) data from pihole.db, so you get all the devices, which are seen in the arp table of the pihole server, isn't it?

While experimenting with docker  I now have different networks (and new interfaces like docker0) on my box. I'd like to exclude this from all the statistics. As workaround I archive that in Pi.Alert but as soon as I change something with docker resp. the containers I usually get a new entry/new MAC/new IP (usually multiple of them) - so this is PITA.

Is there any option how I can restrict Pi.Alert to my normal IP range (e.g. 192.168.12.0/24) to clean/avoid that mess?

Thanks, Mario

**Comment by leiweibau** [comment]
Hello

You will not be able to prevent Pi-hole from including Docker hosts in its database. The reason is that these Docker hosts are likely making DNS queries, and Pi-hole is probably the DNS server handling them. Consequently, these hosts need to be recorded in Pi-hole's ARP cache and subsequently in Pi.Alert. While I have provided a way in the configuration file to create a list of MAC addresses to be hidden, I don't think it will help you in a Docker environment. So far, I haven't implemented the ability to hide based on IP (or IP range). I understand the specific need in your case, but disabling or limiting the detection would go against the purpose of Pi.Alert in my opinion. I only implemented the option to disable individual MAC addresses due to sporadic issues with Pi-hole. However, I will think about this in the next few days.

**Comment by upD8R** [comment]
Thanks, really appreciate your thoughts. On Pi-hole I believe the ARP cache is even filled by the OS, my docker containers usually don't use Pi-hole (except one, which is explicitly configured that way).

I also agree about your statement regarding the purpose of Pi.Alert. Yet, I'm not sure what to do now.
This is an extract how my archive looks like right now and every time I recreate a container due to config changes multiple MACs/IPs are coming up. As soon as my environment gets more stable I might be able to deal with this amount of "tuning" but at the moment it's difficult to keep it clean.
![Screenshot 2023-07-04 142821](https://github.com/leiweibau/Pi.Alert/assets/39015615/1cfb8d06-1e72-45d5-8c66-0db55ed7cb3a)

Is there any way to disable reading the pihole.db and if yes - what do I loose in Pi.Alert?

**Comment by leiweibau** [comment]
The easiest way to prevent reading the Pi-hole database is by disabling Pi-Hole in the pialert.conf file and potentially changing the Pi-hole database name, also in the pialert.conf.

What would you lose?
That depends on your network configuration. However, if the online/offline detection has been working correctly so far, there shouldn't be any major limitations. The name resolution of newly detected hosts might be restricted, though.

**Comment by upD8R** [comment]
Thanks. Still undecided, though ;-)

**Comment by leiweibau** [comment]
I've been thinking about this a bit over the last few days, but I'm not really convinced about ignoring devices based on their IP. Of course, I understand the need in your situation.

I will leave your request open as a [Feature Request]. If this feature gets a higher demand, I will take it up again.

**Comment by upD8R** [comment]
Thanks indeed, you should enjoy sun and not working too much ;-)

IN the Pi-hole thread there's at least one other person having the same "issue". For the time being I disable access to pihole DB as you suggested. Not added any new "real" device yet, though ...

**Comment by upD8R** [comment]
If I could make another wish - you already offer a bulk editor but I couldn't find any bulk deletion. I do have now more than 40 orphan "devices" due to my experiments, which I need to get rid off but the majority appears again after the next config change ...

Thanks a lot!

**Comment by leiweibau** [comment]
Closed, as there is no demand.

**Comment by leiweibau** [comment]
Since I am now also forced to use Docker, I am now also in the situation where the behavior you mentioned also bothers me. I will now implement this request remorsefully.

**Comment by upD8R** [comment]
I'm looking forward to trying it. At the moment I follow your advice to disable pihole DB and this works rather reliable in my case.

**Comment by leiweibau** [comment]
I've been experimenting with the feature for a few days now and realized that it hardly does anything. When the docker0 interface is first recognized, it does help, but as soon as the MAC changes from docker0, it appears on the pihole side without an IP and falls through the grid at that moment. However, filtering devices without an IP is basically not useful for my use case, as I myself have devices on the network without an IP.

With these experiences on my part, do you still want to have this feature implemented, knowing that it is not necessarily effective?

**Comment by upD8R** [comment]
Interesting findings! I'm not insisting on the feature, disabling access to pihole DB works fine for me. Bit I really appreciate your efforts and time spent! Thanks!

**Comment by leiweibau** [comment]
Okay. Then I will reset the changes and really close the feature request. 😉
