### ISSUE TITLE
[Feature Request] Bulk deletion

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#133]
If I could make another wish - you already offer a bulk editor but I couldn't find any bulk deletion. I do have now more than 40 orphan "devices" due to my experiments, which I need to get rid off but the majority appears again after the next config change ...

Thanks a lot!

_Originally posted by @upD8R in https://github.com/leiweibau/Pi.Alert/issues/130#issuecomment-1631358349_

**Comment by leiweibau** [comment]
Good point. I will think about this.

**Comment by leiweibau** [comment]
<img width="571" alt="indicators" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/6e92df8f-0e7f-455b-a95a-44d8239c1694">

I will also add indicators whether the devices are online/offline (border color) or new or archived (chackbox background color). Maybe I can think of some other indicators.

**Comment by upD8R** [comment]
Good idea, favorites might be another one ...

**Comment by leiweibau** [comment]
I have already thought about that. But "Favorites" and "New Devices" use the same color in the GUI. I would have to use a new color and possibly add a legend, which I wanted to avoid. Or do you have a better idea. 

To display the configured notifications, I wanted to use the text color (Blue = All Events, Red = Down, Gradient = Both, Current Color = No Notification).

**Comment by leiweibau** [comment]
implemented
https://github.com/leiweibau/Pi.Alert/commit/a4e7661c1fb495b7f16cd6b01889803c73cb6702

**Comment by upD8R** [comment]
Pretty cool and works as expected, thanks very much indeed!
2 remarks, though:
1) the color coding simplifies the selection a lot, yet I think a "mark all archived" or "mark all favorites" etc. could be another shortcut. 
2) the 2 execution buttons on the bottom have the same color (red) - i think "delete" is more impacting than "saving", maybe the colors should reflect that?

Just my 2 cents.

**Comment by leiweibau** [comment]
> the color coding simplifies the selection a lot, yet I think a "mark all archived" or "mark all favorites" etc. could be another shortcut.

That will not happen for the time being. On the one hand there are then too many buttons and on the other hand JS is already a certain pain ;-)

> the 2 execution buttons on the bottom have the same color (red) - i think "delete" is more impacting than "saving", maybe the colors should reflect that?

Yes, you're not wrong there. However, both should be used with caution. And since deleting is clearly "more dangerous", there is an additional query here. I will let it work a little on me and adjust something on occasion.
