### ISSUE TITLE
Feature Suggestion: Backup/restore enhancement

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#135]
Currently using the backup/restore features create or restore a backup database on the computer on which pi.alert is running.

Suggest adding the capability to backup via browser download/upload to directory specified by the browser.  The same as pihole works.  Currently have to use ftp to get the backup to a different computer.

Also, instead of just backing up the db, could add the ability to backup pialert.conf.

**Comment by leiweibau** [comment]
Yes, the backup handling could use some more attention. I think about it.

However, a download of the database backup is already possible.

![IMG_6143](https://github.com/leiweibau/Pi.Alert/assets/105860611/23e04f89-bfb6-4178-b32a-58541c834186)

**Comment by hspindel** [comment]
Cool!  I missed seeing that download button. :-)

**Comment by leiweibau** [comment]
I have made the database download option a bit more obvious and added another button for the config download

<img width="1017" alt="download" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/26a7c401-bc40-4a96-928e-7709aad88cab">

**Comment by hspindel** [comment]
Excellent.  Thank you very much.

**Comment by hspindel** [comment]
Just FYI, I donwloaded and installed the latest pialert but my backup page doesn't match your image - still looks like the old page.

**Comment by leiweibau** [comment]
Yes, that is correct. I just committed it for now, but it is not yet included in the installation package. Via the "Update Check" you can check if there is an update available

**Comment by leiweibau** [comment]
Update released https://github.com/leiweibau/Pi.Alert/commit/6bbf990d714fd5bcd6b76358f5184d87ab6f2982

**Comment by hspindel** [comment]
Nice!  Working well.  Thank you.
