### ISSUE TITLE
Router/AP issue on network view

### ISSUE THREAD

**Issue by sahara101** [leiweibau/Pi.Alert#136]
Hi. I have an Asus Lyra which if I set up as AP I can add devices to the network view. The problem is, I also have a PS5 hardwired in it + the conection to the normal router.  If I set it up as a router or AP with 2 ports, all wifi devices disappear from the view. It seems you can't mix ports with wifi.

It should let me add 2 ports and also show the wifi devices assigned to it. 

Thanks!

LE: seems you can add them twice, once with ports, once as wifi. I would be better if it is possible to have them together

**Comment by leiweibau** [comment]
Hello

with the way the network overview was written, it is not possible to assign multiple network nodes to one end device. This will also not be possible in the future for the time being. 
As a workaround, you can create a "dummy device" with the same name and assign this to another node. However, no IP or online/offline detection is performed here.

**Comment by leiweibau** [comment]
No feedback received
