### ISSUE TITLE
Enhancement: Dietpi-Software

### ISSUE THREAD

**Issue by holocronology** [leiweibau/Pi.Alert#138]
Have you considered porting this into the dietpi-software install process? It would be excellent if this was a native DietPi option. Seems like you're 99% of the way there.

**Comment by leiweibau** [comment]
Honestly, I've never thought about that before. I wouldn't even know what processes have to be started and adhered to for this. 🤷‍♂️

**Comment by leiweibau** [comment]
Since I don't see any way to influence the software selection process of the DietPi distribution, I'll close this issue for now.
