### ISSUE TITLE
[Feature Idea] Frontend Journal

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#140]
I find the idea quite interesting, as it creates a certain level of security and traceability. Not every click should be monitored, but only database or configuration operations.

**Comment by leiweibau** [comment]
A small preview of the Journal Feature:

<img width="1248" alt="preview" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/4c5728d2-0b31-4cc3-861b-7a3e2c73bfec">

**Comment by leiweibau** [comment]
With color coding (last hour and current day)

<img width="1307" alt="journal" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/977f8bd4-8d6b-48a3-b675-bfb1986d88dc">

**Comment by hspindel** [comment]
Very nice!

**Comment by leiweibau** [comment]
Update Released https://github.com/leiweibau/Pi.Alert/commit/f48c7c40f2c1dddda127558c2c05e079fa2d40bf
