### ISSUE TITLE
pi.alert keeps listing Technicolor Delivery Technologies Belgium NV as unknown device

### ISSUE THREAD

**Issue by graphixillusion** [leiweibau/Pi.Alert#141]
Hi there. As the topic says pi.alert always keeps listing this unknown device in the local lan tagged as new device:

name of the device according to it's mac address = Technicolor Delivery Technologies Belgium NV
mac address = 10:13:31:66:4d:cc
status = offline
last ip = fe80::1213:31ff:fe66:4dcc

In the events view info i have this log:

2023-08-03   01:30 | New Device | fe80::1213:31ff:fe66:4dcc | (Pi-Hole) Technicolor Delivery Technologies Belgium NV

If i delete this device from the list it stills returning after a while. Needless to say i don't have anything like this connected in my LAN.  

I'm running the last version of pi.alert alongside pi.hole on the same raspberry (pizerow).

Any clue?

**Comment by leiweibau** [comment]
Hello,

on the Help / FAQ page in Pi.Alert there is an entry about this topic.

> I have devices in my list that I do not know about. After deleting them, they always reappear.

<hr>

> If you use Pi-hole, please note that Pi.Alert retrieves information from Pi-hole. Pause Pi.Alert, go to the settings page in Pi-hole and delete the DHCP lease if necessary. Then, also in Pi-hole, look under Tools -> Network to see if you can find the recurring hosts there. If yes, delete them there as well. Now you can start Pi.Alert again. Now the device(s) should not show up anymore. Restarting the pihole-FTL service may also fix the problem. If such a device continues to appear repeatedly, the MAC address can be added to the ignore list MAC_IGNORE_LIST in the pialert.conf.

**Comment by leiweibau** [comment]
No problem. Maybe I'll highlight the link to the page a bit more.
