### ISSUE TITLE
Missing menu item?

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#143]
Just updated to the latest pi.alert.

The left column in the pi.alert GUI has a selection for "Update Check".  I could have sworn that that column scrolled and I could reach the update check button by scrolling down.  Now I can only see it by enlarging my browser window so it is long enough to show the last menu item.

Am I wrong about previously being able to scroll?

Oh wait, I just noticed the new PiAlert Journal selection in the left column, which pushes everything in the column further down.  Probably this is why I'm not seeing the Update Check option without enlarging the browser window.

**Comment by leiweibau** [comment]
You're right, the sidebar doesn't seem to scroll. I'll have to have a look tomorrow.

**Comment by hspindel** [comment]
Good to know I'm not going crazy.  Thank you for the support!

**Comment by leiweibau** [comment]
Quick fix
https://github.com/leiweibau/Pi.Alert/blob/1555408109d9ed0f64a34aede3fe6f2a98d65888/front/php/templates/header.php#L135

Remove "fixed" in this line.
Update will be later today

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/10b0045436656f5977cd275bc781e3fb7112c460

**Comment by hspindel** [comment]
Confirmed fixed.  Thank you!
