### ISSUE TITLE
[Bug] New ICMP polling not working as expected?

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#147]
Thank you for adding the ICMP Monitoring feature.  I probably am configuring something wrong, but it isn't working for me.

First, I added MAC ignore entries for two problematic WiFi extenders.  I deleted them from the list of known devices.  They do not reappear in the device list, which is expected and good.

Then I went to the ICMP Monitoring page.  I added 4 IP addresses to monitor (two WiFi extenders, two devices behind the extenders).  I verified that I can ping those devices at the expected IP addresses using a command line.

Pi.Alert Journal confirms that I added the 4 expected IP addresses (although the "Method" field is blank):
--------------------------------------
2023-08-18    16:30:56 | a_031_0001 |   | 192.1.1.12 | Entry added192.1.1.237
2023-08-18    16:30:41 | a_031_0001 |   | 192.1.1.12 | Entry added192.1.1.215
2023-08-18    16:30:20 | a_031_0001 |   | 192.1.1.12 | Entry added192.1.1.200
2023-08-18    16:30:04 | a_031_0001 |   | 192.1.1.12 | Entry added192.1.1.252
-------------------------------------------

On the ICMP Monitor page, there are no devices listed.  So it appears that nothing is getting polled.  I realized I neglected to select "Monitor All Events" when setting up the entry.  I can't find a way to edit any of the four entries I created, and attempting to add them again gives an error:

------------------------------

The ICMP host was not saved

INSERT INTO ICMP_Mon ("icmp_ip", "icmp_hostname", "icmp_LastScan", "icmp_PresentLastScan", "icmp_avgrtt", "icmp_AlertEvents", "icmp_AlertDown", "icmp_Favorite")
                         VALUES("192.1.1.200", "isy", "2023-08-18 16:57:06", "0", "99999", "0", "1", "0") 

not an error
----------------------------------

I also verified that the crontab entries to run pialert are still present.  The most recent pialert.1.log contains in part:
------------------------
Start ICMP Monitoring...
    Get Host/Domain List...
    Flush previous ping results...
    Ping Hosts...
---------------------------------

What am I doing wrong?

**Comment by leiweibau** [comment]
This is frustrating.

**Journal:**
I have provided a new update which should fix the missing part in the journal. Additionally, scan log now shows how many hosts are in the database.
https://github.com/leiweibau/Pi.Alert/commit/c2e28a5d62fd6e1b8cdad16773668c7ff34295be

<hr>

**ICMP Monitoring**

If you enter the URL `https://<Your Pi.Alert>/pialert/php/server/icmpmonitor.php?action=getDevicesList` in the browser, do you get anything displayed? (Maybe you must remove "/pialert", too.)

**Comment by hspindel** [comment]
Thank you for the update.  The journal entry is fixed - the Method field shows "ICMP monitoring" and the journal lists the four IP addresses I am trying to monitor.

During the pialert update process, I saw the following:
Start ICMP Monitoring...
    Get Host/Domain List...
        List contains 4 entries
    Flush previous ping results...
    Ping Hosts...

... and no more information about ping results (don't know if I should expect anything).

You mentioned that the scan log shows how many hosts in the database.  I am not sure where the scan log is.  The pialert.1.log file contains:

Processing scan results...
    Processing ignore list...
        Delete 3 ignored devices from scan on appearance
    Devices Detected.......: 25
        arp-scan Method....: 23
        Pi-hole Method.....: +0
        Fritzbox Method....: +0
        New Devices........: 0

    Devices in this cycle..: 25
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

... and looking through the devices reported in the GUI, everything looks okay.

On the ICMP Monitoring page, there are still no devices listed and no way that I can find to edit the ICMP entries I created that are reported in the journal.

I tried both the URLs you suggested, and my browser (Firefox) says it is unable to connect, service could be unavailable or busy.  I tried http instead of https just in case, but I get a 404 error that way.

What would you like me to try next?  On a hunch, I cleared my browser cache but it made no difference in anything reported above.

Thank you!

**Comment by leiweibau** [comment]
If entries have been made in the ICMP monitoring, the page should look something like this
https://github.com/leiweibau/Pi.Alert/blob/main/docs/img/screen_icmp_01.png

> ... and no more information about ping results (don't know if I should expect anything).

No, there are no more information at the moment

The log file does not show whether this host is online or offline. 
What is your Pi.Alert-URL?

**Comment by hspindel** [comment]
My pialert URL is:

http://192.1.1.11/pialert/devices.php

My ICMP Monitoring page looks like this:


![Screenshot 2023-08-19 at 02-40-31 Pi Alert - RaspberryPi](https://github.com/leiweibau/Pi.Alert/assets/11689573/459756a6-99a1-4ce3-9ef4-e42da60c478a)

**Comment by hspindel** [comment]
Sorry, forgot to give you OS/Platform.

pialert is running on a Raspberry PI, the usual Debian.  I just used the typical pihole installation on this Pi.

I'm accessing pialert's GUI from a Win 10 machine, using Firefox.  Just in case, I just tried this with Chrome.  The results are the same.

**Comment by leiweibau** [comment]
Did you get an output when you enter this URL?
http://192.1.1.11/pialert/php/server/icmpmonitor.php?action=getDevicesList

**Comment by hspindel** [comment]
This is what I get at the requested URL:

{"data":[["isyaccesspt","192.1.1.252",0,4.924,"2023-08-19 02:57",1,0,1],["isy","192.1.1.200",0,7.159,"2023-08-19 02:57",1,0,2],["eax15","192.1.1.215",0,3.679,"2023-08-19 02:57",1,0,3],["arlobase","192.1.1.237",0,3.862,"2023-08-19 02:57",1,0,4]]}

**Comment by leiweibau** [comment]
Okay. The Backend seems okay:
"isyaccesspt","192.1.1.252",0,4.924,"2023-08-19 02:57",1,0,1
hostname, ip, no Favorite, avg_rtt, Ping Time, online, no Alert down, rowID

This seems to be a problem in the frontend.

**Comment by hspindel** [comment]
Let me know if there are any more tests to run.

I'm going to bed now.  It's 3AM where I live.  :-)

Thank you.

**Comment by leiweibau** [comment]
I see only now that there are too many entries in the table header. But why?
Here should be only "Name", "IP", "Favorite", "Response Time", "Scan Time" and "Status".

can you please check these lines?
https://github.com/leiweibau/Pi.Alert/blob/ee4d499398193b5ab4b375b8464a0a3f3f1aee99/front/icmpmonitor.php#L266
    'columnDefs'   : [
      {visible:   false,         targets: [6,7] },
      {className: 'text-center', targets: [1,2,3,4,5] },
      {className: 'text-left',   targets: [0] },
      {width:     '150px',       targets: [4] },
      {width:     '80px',        targets: [2,5] },
      {width:     '110px',       targets: [3] },

**Comment by leiweibau** [comment]
If the "main()" function in the JavaScript does not start, the error pattern that you have occurs.
Can you get more information in the developer tools in the browser?

**Comment by hspindel** [comment]
I know nothing about browser debugging, but I gave it a try.

I see one error in the Inspector tab of the debug console.  Can't find a way to copy it to the clipboard, so I'm going to transcribe it by hand.  I might make mistakes.

<body class="skin-blue sidebar-mini" style="background-image; url("img/background.png"); height: auto; min-height: 100%;" upload="show_pia_servertime();"> overflow

Here I am uploading the output from the Firefox console (showing an issue with pialert):

[FirefoxConsole.txt](https://github.com/leiweibau/Pi.Alert/files/12386851/FirefoxConsole.txt)

Also, I don't know if this helps, but I am uploading the page source that Firefox sees;

[pialert_web_source.txt](https://github.com/leiweibau/Pi.Alert/files/12386838/pialert_web_source.txt)

**Comment by hspindel** [comment]
> Now I see that there are too many entries in the table header. But why? Here should be only "Name", "IP", "Favorite", "Response Time", "Scan Time" and "Status".

My local copy of icmpmonitor.php has the same text as what you linked.

**Comment by leiweibau** [comment]
Have you tried disabling the "Origin" extension for this page?

**Comment by hspindel** [comment]
I only have UBlock origin enabled in Firefox.  I tried viewing the ICMP Monitoring page in both Chrome and Edge (both of which I keep vanilla without extensions) and both of them behaved the same as Firefox.

But just to be complete about it, I disabled UBlock Origin in Firefox.  Made no difference.

The logs I sent previously show some errors.  Were there any clues in that?

**Comment by hspindel** [comment]
Found another potential clue.

One of the requests to pialert from the browser is:
http://192.1.1.11/pialert/php/server/parameters.php?action=get&parameter=Front_Devices_Rows

It returns null.

**Comment by leiweibau** [comment]
I just set another update and set another option in the javascript, hoping that an error which was seen in your Console will disappear.
Unfortunately, this error does not exist in my case, which makes it very difficult for me to work on it. In the meantime I also tested the browser "Opera" (definitely no cache existing), where I can't reproduce the error either.

**Comment by leiweibau** [comment]
You can try to copy&past this:
https://raw.githubusercontent.com/leiweibau/Pi.Alert/d06169ed344bcf8e737d51e6e5bb4e3f605695b8/front/icmpmonitor.php
in your pialert/front/icmpmonitor.php. This is a cleaned up version

**Comment by hspindel** [comment]
Hi,

I updated my pialert to the latest version you posted, and SUCCESS!  The ICMP Monitor page reports the 4 ping'ed devices I asked for!

**Comment by leiweibau** [comment]
First of all, many thanks to you, for your patience and helpfulness and of course for the sponsorship 🙏

In your "FirefoxConsole - Log" there was an error that indicated a missing order configuration in the table.
```
Uncaught TypeError: e[i] is undefined
    jQuery 8
    initializeDatatable http://192.1.1.11/pialert/icmpmonitor.php:560
    main http://192.1.1.11/pialert/icmpmonitor.php:548
    jQuery 4
```
Why this came only with you, but not with me to the effect, I can not answer.

**Comment by hspindel** [comment]
You are very welcome.  I really appreciate that you took the time to implement ICMP Monitoring, and I am happy that I was able to provide enough information for you to figure out what the issue was.

I tested it by (temporarily) adding a printer to the ICMP polling and turning it on and off.  I got emails of the events.  Excellent!

Couple very minor suggestions (I'll post as enhancement requests if you prefer):

In the email reports, for example a "down" report, perhaps there could be an indication of what part of pialert detected the event (e.g., ICMP, arp, web services).

On the web services page, if you click on a device you cannot edit the URL.  Similarly for ICMP Monitoring, if you click on a device you cannot edit the IP.  In both cases, the only choice is to delete the device and recreate it (which is not that big of a deal, if you don't think it's worth addressing).

**Comment by leiweibau** [comment]
> In the email reports, for example a "down" report, perhaps there could be an indication of what part of pialert detected the event (e.g., ICMP, arp, web services).

Good idea. I will change that in the next days.

>On the web services page, if you click on a device you cannot edit the URL. Similarly for ICMP Monitoring, if you click on a device you cannot edit the IP. In both cases, the only choice is to delete the device and recreate it.

Yes, this is intended. The background here is that the URL and the IP serve as primary key and are a reference to the "Events" table. If you change the URL or IP, you would also have to change, with under, several hundred events. When an ICMP host is deleted, the events are also deleted, so that another host with the same IP does not take over its events. Also in the device list you cannot change the MAC address.

**Comment by hspindel** [comment]
Okay, thank you for the cogent replies!

After 24 hours, the ICMP monitoring is working perfectly. Excellent!
