### ISSUE TITLE
can't backup DB

### ISSUE THREAD

**Issue by ramess18** [leiweibau/Pi.Alert#150]
Hello,
I'd like to make a **DB Backup** via _Settings>Backup/Restore_ but I got this strange notification:
![image](https://github.com/leiweibau/Pi.Alert/assets/16610727/65dcd038-8c26-4e11-ac26-bee47f9cb8bb)
...and no new backup was created.
Can you please give me a hint how to correct it? I am on the latest version - (2023-08-20)
Thanks
Radim

**Comment by leiweibau** [comment]
Have you try it again? It should not be a fundamental problem, since everything works in my development version and there is no abnormality on my test devices either. 

**To explain the message:**
If you copy the database as a file, just like that, it can result in a corrupt database (I learned this painfully in the past). So now, using database commands, I create a copy of the database and it is then checked for integrity. But since I don't have a "non-integer" database, I can't answer if it can also be copied just like that and only gives an error when integrity is checked.

Did you start using my fork with this version, or are you already using it with earlier versions?

Apart from this error, does Pi.Alert work properly (can you edit or add entries)?

If you upgraded from a previous version, did you pause Pi.Alert according to the warnings?

Have you already created a previous backup?

**Comment by ramess18** [comment]
_Have you try it again?_ 
Yes I did restarts and tryied several times. It seems to do something with updates ...Backup via UI always worked well for me.

_Did you start using my fork with this version, or are you already using it with earlier versions?_ 
No I've used your fork for long time and just using your upgrade script.

_Apart from this error, does Pi.Alert work properly (can you edit or add entries)?_ 
Yes, I can.

_If you upgraded from a previous version, did you pause Pi.Alert according to the warnings?_
For upgrades I use your script with the cmd: 
`curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh | bash`

_Have you already created a previous backup?_ 
Yes I did, but it was several Pi.Alert versions back.

**Comment by leiweibau** [comment]
> For upgrades I use your script with the cmd

And this update script warns 2 times to pause Pi.Alert ;-)

Please pause Pi.Alert (via Web Gui or pialert-cli), navigate to your Pi.Alert DB folder `~/pialert/db` and run the following command:
`sqlite3 pialert.db "PRAGMA integrity_check"`
This checks the database for basic errors, as the backup function does with the copy.

**Comment by ramess18** [comment]
Ok. I did pause Pi.Alert and than run the commands. Still the same notification and no new backup created.
I tried re-run update script and there is this message at the end:
```
Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 2535, in <module>
    sys.exit(main())       
  File "/root/pialert/back/pialert.py", line 108, in main
    res = scan_network()
  File "/root/pialert/back/pialert.py", line 492, in scan_network
    update_devices_data_from_scan ()
  File "/root/pialert/back/pialert.py", line 1035, in update_devices_data_from_scan
    sql.execute ("""UPDATE Devices SET dev_PresentLastScan = 0
sqlite3.DatabaseError: database disk image is malformed
```
Last sentence doesn't sound right ;)

I found out also this mail for root:
```
pialert.lan : Aug 20 20:03:57 : www-data : a password is required ; PWD=/root/pialert/front/php/server ; USER=root ; COMMAND=/usr/bin/chmod -R 775 /root/pialert/back/../front/reports/
```

**Comment by leiweibau** [comment]
That is not nice.

I would now recommend the following:
- If the last backup was made with a version newer than 2023-07-20, the database should be okay. If the backup is older, I can't guarantee it, unfortunately.
- To restore the backup, pause Pi.Alert with pialert-cli. To do this, change to the directory `~/pialert/back` and execute `sudo ./pialert-cli disable_scan`. This has the advantage that running scans are also terminated.
- Now change to the directory `~/pialert/db` and rename the file pialert.db to pialert.db.old and unzip your backup in the same directory with `unzip <ARCHIVNAME>.zip`.
- Regarding to [Known issues](https://github.com/leiweibau/Pi.Alert/issues/128) you have to do the following:
>When restoring the database via the web interface, the file permissions are not correct. For this it is necessary to execute ./pialert-cli set_peermissions in the folder ~/pialert/back.

<hr>

> I found out also this mail for root

To avoid this, you can add the components of Pi.Alert to the sudoers
- change to the directory `~/pialert/back`
- run `sudo ./pialert-cli set_sudoers`
- A text output is shown, which users and commands have been entered under sudoers
I could also do this during setup, but for transparency reasons, I want everyone to do this consciously themselves.

**Comment by ramess18** [comment]
I tryed all my DB backups (back to 2 months old) and all the same behaviour. 
Pi.alert is working correctly (editing devices, network) except the GUI DB backup so I keep using it as is. 
Thank you for your effort.

**Comment by leiweibau** [comment]
Thank you for the feedback.
