### ISSUE TITLE
New person wanting to ask/check

### ISSUE THREAD

**Issue by Just-another-pleb** [leiweibau/Pi.Alert#151]
I updated this from the original version.
This one is still supported, so I hope I can find a *forum* where I could ask about weird new devices that keep showing up on my network.

Here?  Or is there a better place?

**Comment by leiweibau** [comment]
You can ask here, but there is also a FAQ/Help page, that addresses this issue.

**Comment by Just-another-pleb** [comment]
I have an edge router set up as my main router and have PiHole and now PiAlert running.

I am not wanting to be paranoid but I  am getting/seeing devices connecting to my network (via WiFi) that I can't identify.

I can't catch them being online.   They just seem to appear in/on the list of devices repeatedly.
Do do have a recent smart phone but it's MAC ADDRESS SPOOFING is turned off - as I don't connect to public WiFis anyway, and it is turned off most of the time anyway.

![Screenshot from 2023-08-22 16-41-45](https://github.com/leiweibau/Pi.Alert/assets/39888280/150d69be-51d9-4f7a-8d74-1abccc02ad09)

Two things here:
All the `new devices` at the top and a duplicate of `portapi` lower down (in blue).
I have deleted the second entry but it keeps coming back for reasons unknown.
(which may be the same reason the other `unknown devices` are coming back too.)

I'll stop here as I may already be making a food of myself.

I'll check if the pages you mentioned above helps.   But if I don't ask, they won't and I will have to ask anyway.  ;)
So here's to hoping they do help, or if they don't someone here can.

**Comment by Just-another-pleb** [comment]
Resolved.
