### ISSUE TITLE
Can't edit devices

### ISSUE THREAD

**Issue by zenalien** [leiweibau/Pi.Alert#153]
Hello, 

Fresh install (no docker) and toggle scan disabled.

Each time I want to rename a device I get this message : 

Error updating device

UPDATE Devices SET
                 dev_Name                 = "Router",
                 dev_Owner                = "(unknown)",
                 dev_DeviceType           = "",
                 dev_Vendor               = "ASUSTek COMPUTER INC.",
                 dev_Model                = "",
                 dev_Serialnumber         = "",
                 dev_Favorite             = "0",
                 dev_Group                = "",
                 dev_Location             = "",
                 dev_Comments             = "",
                 dev_Infrastructure       = "",
                 dev_Infrastructure_port  = "",
                 dev_ConnectionType       = "",
                 dev_StaticIP             = "0",
                 dev_ScanCycle            = "1",
                 dev_AlertEvents          = "0",
                 dev_AlertDeviceDown      = "0",
                 dev_SkipRepeated         = "0",
                 dev_NewDevice            = "0",
                 dev_Archived             = "0"
          WHERE dev_MAC="08:62:66:8f:1c:00" 

attempt to write a readonly database

Thank you for any Help

**Comment by leiweibau** [comment]
Die you follow the instructions on the Help/FAQ page?

**Comment by zenalien** [comment]
My bad, I did not thank you, problem solved.

**Comment by leiweibau** [comment]
Thanks for the feedback.
