### ISSUE TITLE
Speedtest failure

### ISSUE THREAD

**Issue by tcoombs** [leiweibau/Pi.Alert#156]
I've installed the latest Pi.Alert on a RaspberryPI 3b and overall I'm very pleased with it. The only issue I have is that when I try the Speedtest function from the Internet/tool tab there is a brief indication of activity but no confirmation that the test has run. is this a known issue?

**Comment by leiweibau** [comment]
How long did you wait? The speed test takes about 10 seconds for me. Is there anything in the journal about the speed test?

**Comment by tcoombs** [comment]
I have confirmation in the journal to say Speedtest ran but no summary of the results in the GUI.

2023-09-12    15:07:23 | a_002_0255 | Pi.Alert Scans | 192.168.3.232 | Online Speedtest executed
-- | -- | -- | -- | --

**Comment by leiweibau** [comment]
Do you get an error message when you run speedtest-cli directly in the ~/pialert/back/ directory? What file permissions do you have in the directory (ls -al)?

**Comment by tcoombs** [comment]
All kook d good except speedtest reported it can’t connect to the server. I’m think I’m going to rebuild my RPI image from scratch and reinstall pi.alert and test again.

**Comment by leiweibau** [comment]
If you use Pi-hole, maybe the server domain is locked in Pi-hole? The speedtest will dynamically find the fastest server in your area. So it does not always have to be the same server that is tested against.

**Comment by tcoombs** [comment]
I have pihole but disabled blocking to test if this is the problem. Speedtest is still failing and so I’m going to rebuild my RPI and try again. Thanks for your help.

**Comment by leiweibau** [comment]
In looking at your problem, I noticed that the speedtest-cli may not be starting correctly. Since I have to rely on python3, I changed the environment in the speedtest-cli to python3 as well and added a few customizations for python3.11. I will provide another update within the next days.

**Comment by tcoombs** [comment]
Hi, I did a full install yesterday and this did not solve the problem. As a test, I installed speedtest-cli on my second RPI and this also failed. Therefore, as a second test I installed the official Ookla Speedtest app on my second RPI and this worked fine! As a third test, I installed speedtest-cli on a Ubuntu server I have in the cloud and this worked fine! So, now I’m thinking my firewall is the problem. By the way, when I tried speed test-cli —list it did not return a list of servers in my home lab. Therefore, there’s likely a communications problem somewhere!

**Comment by leiweibau** [comment]
> By the way, when I tried speed test-cli —list it did not return a list of servers in my home lab

As far as I understand speedtest-cli, it queries a list of official speedtest servers and picks the fastest server from the closest ones, against which the test is then performed. So you will not find a server of your homelab in the list of speedtest servers.

"speedtest.net" should be reachable.

**Comment by tcoombs** [comment]
Speedtest.net is definitely reachable via the web interface. I can also ping and traceroute. I also just run a speedtest-cli test from my RPI by directly connecting to my active and backup ISP routers to bypass my Firewall. I use Starlink and SFR ISPs. Speedtest-cli still failed on both and so it can now only be a problem with the app!

**Comment by leiweibau** [comment]
Speedtest-cli is a third party app, I can only help here to a limited extent. But I could integrate a 2nd button with another speedtest.

**Comment by tcoombs** [comment]
Hi, thanks again for your help. I fully appreciated that the speedtest-cli is a 3rd party app and so there’s not much you can do to resolve the problem. As the official speedtest app from Ookta is working perfectly it would be great if you could support this app, if possible. By the way, as a feature request would it also be possible to set a daily schedule to run the test and display the results in a table? I think this would be a great enhancement to an already brilliant solution.
