### ISSUE TITLE
Speedtest?

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#158]
Saw another user posted about speedtest, saying that he accessed it from the Internet/tool tab.

Where is this tab?  Can't find it anywhere.

speedtest-cli works fine.

Thanks.

**Comment by leiweibau** [comment]
The tab should be there. I will check this later

**Comment by hspindel** [comment]
It is there under device "Internet".  I just didn't know to look there.  Works fine!

**Comment by hspindel** [comment]
Please close this issue.

**Comment by leiweibau** [comment]
It is a pleasure to work with you 👍

**Comment by hspindel** [comment]
> It is a pleasure to work with you 👍

Likewise.  You are perhaps the most responsive developer I've worked with.
