### ISSUE TITLE
[Feature Request] Configurable timeout for ping command

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#159]
Some of my devices take a long time to respond to ICMP and pialert thinks they are down.

Don't know what timeout pialert is using now, but perhaps it could be configurable?  Preferably on a per device basis.

Thank you.

**Comment by leiweibau** [comment]
There are 2 commands

1. Ping: Reachability
https://github.com/leiweibau/Pi.Alert/blob/d4aeee312fffad1feec44625b45408ecc0138c56/back/pialert.py#L1870

2. Ping: 2 pings to calculate the response time
https://github.com/leiweibau/Pi.Alert/blob/d4aeee312fffad1feec44625b45408ecc0138c56/back/pialert.py#L1880

**Comment by hspindel** [comment]
Ok, I see and understand the code.  I thought perhaps adding a configurable -W parameter to the ping command would do what I'm suggesting, but I tried it and it doesn't seem to work the way I'd expect.
