### ISSUE TITLE
[Feature Request] Support official speedtest app from Ookla ✅ / Daily scheduled run ✅

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#160]
Hi, thanks again for your help. I fully appreciated that the speedtest-cli is a 3rd party app and so there’s not much you can do to resolve the problem. As the official speedtest app from Ookta is working perfectly it would be great if you could support this app, if possible. By the way, as a feature request would it also be possible to set a daily schedule to run the test and display the results in a table? I think this would be a great enhancement to an already brilliant solution.

_Originally posted by @tcoombs in https://github.com/leiweibau/Pi.Alert/issues/156#issuecomment-1722146973_

**Comment by tcoombs** [comment]
Thanks! If I knew myself on how to do this I would advise. Tony

**Comment by leiweibau** [comment]
I have already made some progress with this. The individual stages that I have to work through:

- Create a download function corresponding to the processor platform.
- the user must accept the license (a console interaction of the user is mandatory)
- make sure that the user www-data can also run the test.

In my private environment the speedtest already works, but the whole thing is not yet integrable into an update process.

**Comment by tcoombs** [comment]
Excellent news. Thanks for the update!

**Comment by leiweibau** [comment]
I will try to push all necessary files today or tomorrow (I have to think about timezones), so that it is possible to activate the speedtest manually with a short instruction.

And I also thank you very much.

**Comment by tcoombs** [comment]
Thank you. I’m doing a full PI re-image next week so this is great timing!

**Comment by tcoombs** [comment]
It would be great to have all values but as a initial implementation up/down is fine if it’s quicker for you.

**Comment by leiweibau** [comment]
I would start with ping, server, ISP, down and up, because I enter the values in the journal and don't want to blow it up too much, so that the table layout doesn't break.

**Comment by tcoombs** [comment]
That’s great thanks!

**Comment by leiweibau** [comment]
Update Released.

**Comment by tcoombs** [comment]
Just installed and it’s working great! Thanks for your hard work!

**Comment by leiweibau** [comment]
I am happy to read that. I'm still leaving the feature request open, since I haven't implemented the regular scan yet. When and how I will implement this, I can not say at the moment, because I have to think about how I will deal with now 2 speedtests.

**Comment by leiweibau** [comment]
Update Released with https://github.com/leiweibau/Pi.Alert/commit/489e411f62480e79926cb483204b706515b93a1d
