### ISSUE TITLE
Bug after French language change

### ISSUE THREAD

**Issue by xekil** [leiweibau/Pi.Alert#163]
Hello, after selecting the French language, the majority of buttons no longer work.

Changing language or theme has no effect, etc. Cannot save changes to configuration file, etc.

Impossible to go back to reset the English language.
A restart doesn't change anything, the only solution is to reinstall everything but the problem occurs again as soon as I choose the French language.

Of course I tried on several different browsers and computers and smartphones, all have the same behavior, the buttons no longer work

Thanks for your help

**Comment by leiweibau** [comment]
To reset the language you can delete the language setting file in the "db" directory.

An invalid character may have snuck into the language strings. For the translation I used deepl.com and ChatGPT. I am trying to determine what the problem could be.

**Comment by leiweibau** [comment]
Update including fix released with https://github.com/leiweibau/Pi.Alert/commit/7f9d3aa180c2255144adaa6ddd6552d72bf3025b

**Comment by xekil** [comment]
thank you
