### ISSUE TITLE
cryptography needed for update_vendors

### ISSUE THREAD

**Issue by Waffull** [leiweibau/Pi.Alert#167]
During the manual install process... (I was installing onto an existing pi-hole installation) I had to install cryptography
`pip3 install cryptography`

before `python3 ~/pialert/back/pialert.py update_vendors` would run

**Comment by leiweibau** [comment]
Thank you. I add this to the documentation with https://github.com/leiweibau/Pi.Alert/commit/a85ab05d7a2f42bfbde6cfef48369671ba471507
