### ISSUE TITLE
Reporting an installation update glitch

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#174]
Ran the update script on the latest version.

1) Said installing missing packages: libtext-csv-perl aria2
2) Script bombed out when those packages couldn't be found.
3) Ran apt-get update and tried update script again.
4) Script bombed out because pialert-cli could not be found.
5) Tried install script instead of update script but it failed because target directory already exists.
6) Examined the target directory and noticed that (apparently) the previous upgrade attempt deleted
all the files.
7) Manually created pialert-cli and pialert.py by downloading from the website.
8) Ran the update script again and it worked.

**Comment by leiweibau** [comment]
Thank you for reporting.

**Comment by leiweibau** [comment]
The issue is closed, as there seem to have been no other similar problems since the last update.

**Comment by hspindel** [comment]
I think it likely that this problem would only be seen if the pialert update process needed a package that apt update had not yet made available.  So it's probably a corner case.  It was easy to recover from.

Thanks for looking at it.
