### ISSUE TITLE
Telegram: Sends the message silently. Users will receive a notification with no sound.

### ISSUE THREAD

**Issue by sikousikou** [leiweibau/Pi.Alert#176]
Is it possible to activate the option "disable notification " in telegram setting?

**Comment by leiweibau** [comment]
Just add the string "&notification=no" to the shoutrrr URL (without the quotes)

**Comment by leiweibau** [comment]
Individual configurations can be made within the Telegram API in the configuration file. A reference to the API can be found at https://github.com/leiweibau/Pi.Alert/blob/main/docs/SHOUTRRR.md.

**Comment by sikousikou** [comment]
> Just add the string "&notification=no" to the shoutrrr URL (without the quotes)

thanks work fine
