### ISSUE TITLE
Update script broken.

### ISSUE THREAD

**Issue by tteck** [leiweibau/Pi.Alert#178]
Introducing new features in a future release (Speedtest https://github.com/leiweibau/Pi.Alert/commit/a65d1b389008de258008ad1f4d002781ab2b3dbc) may disrupt the current update script, resulting in an error message like this: `chmod: cannot access '/opt/pialert/back/speedtest/': No such file or directory`.

**Comment by tteck** [comment]
I suggest the creation of a new branch for implementing changes. Once these changes are ready for a new release, they can be merged into the main branch.

**Comment by leiweibau** [comment]
Should be fixed now. You're right. 
Update Released: https://github.com/leiweibau/Pi.Alert/commit/e85a1f4160248b0d32ec4dd97ad6f3729dabd079

**Comment by tteck** [comment]
Now would be a great time to create a new branch called "dev" for implementing changes.
