### ISSUE TITLE
Use pihole API rather than reading the db directly

### ISSUE THREAD

**Issue by danielo515** [leiweibau/Pi.Alert#183]
Hello, and thanks for keeping this fork.
I have my pihole setup in a specific container, and it is not in the same machine as pialert.
Reading the config, I guess this is expected to have the pihole database shared as a volume or something?
Will it be possible to instead use the API?
thanks in advance

**Comment by leiweibau** [comment]
Hello,

when it comes to such concrete technical proposals, I would be happy to receive links/information to get into the topic as well.

As far as I can see, the API is not suitable for obtaining the information needed.
https://github.com/pi-hole/AdminLTE/blob/master/api.php
https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php

As a workaround I could imagine to make a readonly SMB share of the database and mount this share on the Pi.Alert host. In the configuration file the path to this mounted share could be set.

**Comment by danielo515** [comment]
That is a fair take. Even a simple NFS will probably do. Thanks for considering it.
Some nice thing to add to the docs (I couldn't find it) is the DB access requirement

**Comment by leiweibau** [comment]
Will keep this in mind when working on the doc on a regular basis.
