### ISSUE TITLE
NTFY not sending alerts

### ISSUE THREAD

**Issue by modem7** [leiweibau/Pi.Alert#186]
Heya, 

This may be an ID10T issue, but I can't seem to get NTFY to work. 

I've set the following:

```console
# NTFY
#---------------------------
REPORT_NTFY         = True
REPORT_NTFY_WEBMON  = True
NTFY_HOST           = 'https://ntfy.myserver.com'
NTFY_TOPIC          = 'topicname'
NTFY_USER           = 'username'
NTFY_PASSWORD       = 'userpassword'
NTFY_PRIORITY       = 'default'
```

I've tried the following and this works:
```console
curl -u username:password -d "Look ma, with auth" https://ntfy.myserver.com/topicname
```

![image](https://github.com/leiweibau/Pi.Alert/assets/4349962/20186c89-d178-4012-b591-9a011d70df00)

Note, I haven't installed NTFY-cli on the server.
I have checked `requests` is installed:
```console
# pip show requests
Name: requests
Version: 2.31.0
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/local/lib/python3.11/dist-packages
Requires: certifi, charset-normalizer, idna, urllib3
Required-by: fritzconnection, pyunifi
```

Unsure where I may be going wrong. 

On another note, would it also be possible to allow for bearer [tokens](https://docs.ntfy.sh/publish/#access-tokens) as well as username + password?

**Comment by leiweibau** [comment]
Since I have never used "ntfy" myself, I just created an account at Ntfy.sh and entered the data accordingly into the Pi.Alert configuration. Here the event notification and also the test notification works completely without problems.

Have you tried to send a test notification via "pialert-cli"? Errors may be displayed here, which can be used to further isolate the problem.

**Comment by modem7** [comment]
Apologies - this was my own fault. Seems that my Cloudflare bot rules were a bit too tight. 

This is the script that finally helped me figure it out (it's crude, but my Python knowledge is next to zero, no doubt it could be improved):

```python
#!/usr/bin/env python3

import requests
from requests_toolbelt.utils import dump

# To generate the auth token, use echo "Basic $(echo -n 'testuser:fakepassword' | base64)"
# As per https://docs.ntfy.sh/publish/#authentication

response = requests.post("https://ntfy.example.com/topicname",
data="Look ma, with auth",
headers={
    "Authorization": "Basic auth"
})
print(dump.dump_all(response).decode("utf-8"))
```

**Comment by leiweibau** [comment]
No problem
