### ISSUE TITLE
[Feature Request]  Sending alert whenever a new device or a new ip joins the network

### ISSUE THREAD

**Issue by malkatammuz** [leiweibau/Pi.Alert#188]
Sending an alert whenever a new device or a new IP is detected. This could help for security like no unwanted access

**Comment by modem7** [comment]
I certainly already get a notification via NTFY for new devices. 

Sounds like this could be a configuration issue.

**Comment by leiweibau** [comment]
I have thought about the subject again. If you activate the "All Events" option for all devices, you will receive information about changed IPs and when they are connected to the network for known devices. Notifications are already sent for new devices.
