### ISSUE TITLE
[Feature Request] Apprise support

### ISSUE THREAD

**Issue by modem7** [leiweibau/Pi.Alert#192]
To simplify backend config for notifications, one could utilise [Apprise (Github)](https://github.com/caronc/apprise) to allow for multiple notification services, without having to manually add configurations for all of them. 

Requirements: 
1. [Apprise (Pypi)](https://pypi.org/project/apprise/) added to install/update scripts. 
2. Relevant backend config added
3. Readme updated as it could introduce a breaking change if other methods (NTFY, Mail, Pushover, Pushsafer, Telegram) are removed in favour of apprise config.
4. @jokob-sk would need to update the Docker image to reflect changes.

This would definitely require some thinking and testing, but I think it would reduce configuration and backend changes later down the line for notifications.

**Comment by jokob-sk** [comment]
@modem7 Please note my fork has already Apprise supported and leiweibau's and my codebase are very different at this point

**Comment by modem7** [comment]
> @modem7 Please note my fork has already Apprise supported and leiweibau's and my codebase are very different at this point https://github.com/jokob-sk/Pi.Alert ![image](https://user-images.githubusercontent.com/96159884/275100725-bfc8672b-9852-4530-b211-2305e1d5f795.png)

Understood! Thank you for replying! 

Thought I'd include you in as you're part of the readme!

**Comment by jokob-sk** [comment]
Thanks for the ping, let me know if you have any questions - happy to answer 😉

**Comment by leiweibau** [comment]
And I use shoutrrr, to connect to different Services, like Telegram
