### ISSUE TITLE
Work with pihole v6 Beta

### ISSUE THREAD

**Issue by flwilk** [leiweibau/Pi.Alert#196]
I tried Pi.Alert with Pi.Hole_v6(beta) but it did not work. Perhaps because of changing the webserver from lighttpd to civetweb?
I think it's maybe only a missing config of civetweb.
Perhaps also the new REST-API is a solution to get the needed values much easier?

**Comment by leiweibau** [comment]
I watched a video in the last days, which deals with the changes of Pihole. Here it was clearly pointed out that the web server must be uninstalled, because Pihole listens to port 80 for the web interface. Maybe it is possible to change the port of Pihole. Currently I have not yet dealt with this.

**Comment by flwilk** [comment]
I tried serval things, here is what works (so far)
If you do not uninstall lighttpd pihole will use port 8080 and lighttpd is available for pialert.

No nice solution but it works. Perhaps you will find some time to merge to the new Webserver later.

**Comment by lastsamurai26** [comment]
you can also continue to use lighttp, if you don't always want to enter 8080 as port you can also use lighttp as reverse so you don't have to worry that pialert will no longer run.

For my part, I stick with Lighttpd and use it for the web interface of Pihole v6 as a reverse
