### ISSUE TITLE
Error updating pi.alert

### ISSUE THREAD

**Issue by BartEngelen** [leiweibau/Pi.Alert#199]
Hello,

I am new to pi.alert.
When I click on update check it says there is a new update available.
When I run the update script it comes with an error:
Pi.Alert directory doesn't exists: /root/pialert.

Can someone help me with this?

Kind regards,
Bart

**Comment by leiweibau** [comment]
In what kind of environment do you use Pi.Alert (OS name or LXC container)?

**Comment by BartEngelen** [comment]
Sorry, LXC container

**Comment by leiweibau** [comment]
@tteck
Didn't you have a separate update script in the container that starts my update script with parameters?

**Comment by BartEngelen** [comment]
I start the update in the console.

**Comment by leiweibau** [comment]
Which command did you use?

**Comment by tteck** [comment]
I fixed it. I need to rewrite the instructions on the main site. To update Pi.Alert, type "update" or execute `bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)" -s --lxc` in the LXC console.

**Comment by BartEngelen** [comment]
Indeed now it works.
Thanks for the support.
