### ISSUE TITLE
Questions about new features

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#204]
Hi,

How does the "ICMP Monitoring Options" work? I mean what exactly does this do?

And how would I set it to run and how would I disable it if I don't want it? I can't see anything in the documentation how to configure it and the description is vague (sorry).

Also, in regards to the Unifi option, would this read devices listed in Unifi and over-write them in pi.alert? Again, how does this work and is the API key essential or will it work without it?

Many thanks for your help.

**Comment by leiweibau** [comment]
Hello,

> How does the "ICMP Monitoring Options" work? I mean what exactly does this do?

ICMP monitoring. This method is optional. A "ping" is sent to a manually specified IP/hostname/domain name and the response is evaluated. 
It is a simple "ping hostname" command

> And how would I set it to run and how would I disable it if I don't want it? I can't see anything in the documentation how to configure it and the description is vague (sorry).

![IMG_6322](https://github.com/leiweibau/Pi.Alert/assets/105860611/1411af8e-09c0-4af4-beff-9b915e1cce60)

> Also, in regards to the Unifi option, would this read devices listed in Unifi and over-write them in pi.alert? 

It reads the clients and adds those that have not already been recognized.

> API key essential or will it work without it?

The Pi.Alert API Key is not necessary

**Comment by TheCableGuy99** [comment]
Hey,

So if I press the button to turn the ICMP monitoring on do I need to edit the config and tell it where to ping or does it do that itself? I've been trying to edit the config myself and I'm not sure what to enter for the options?
ICMP_ONLINE_TEST   = Presumably an IP to ping?
ICMP_GET_AVG_RTT   = Not sure what to put here?

Noted about Unifi, I'll give this a go...,thanks!

**Comment by leiweibau** [comment]
Yes.

The "ping" command is usually always available, which is why no "location" needs to be specified.

ICMP_ONLINE_TEST specifies the number of pings used to determine whether a device is online

If a device has been recognized as "online", ICMP_GET_AVG_RTT specifies how many further pings are used to calculate an average value for the runtime.

**Comment by TheCableGuy99** [comment]
I think there's some confusion here. I've been thinking this is to ping external hosts to test your online connectivity and how well your connection is (like an addon to the speedtest option). But i'm seeing now there's an ICMP feature in the menu which this clealy works with.

So could I set it up like this:

ICMP_ONLINE_TEST = 5
ICMP_GET_AVG_RTT = 5

If not, what values do you recommend?

Thanks again!

**Comment by leiweibau** [comment]
Please look here https://github.com/leiweibau/Pi.Alert/issues/134 to find out more about the background. 

This depends on the stability of the line or the speed of the devices to be monitored.

Personally, I use "2" to detect the online status and "3" to calculate the average

**Comment by leiweibau** [comment]
> I've been thinking this is to ping external hosts to test your online connectivity

No. This is covered by the "Internet" device.

**Comment by TheCableGuy99** [comment]
Okay thanks for your help with this, I get it now :)
