### ISSUE TITLE
Ongoing Dietpi Install Issues

### ISSUE THREAD

**Issue by holocronology** [leiweibau/Pi.Alert#217]
I used the script to install on dietpi and it appeared to work correctly.

However, if I then go to http://[IP]/pialert/ I get a 404 Not Found error.

I then tried to run the Uninstall script and saw this:

![image](https://github.com/leiweibau/Pi.Alert/assets/65265114/b023f6b2-afa4-4b3d-9152-9924e62b8833)

Leads me to believe that the install script isn't working properly.

Do you need to run it as root or the dietpi user?

**Comment by leiweibau** [comment]
Did you try http://[IP]/pialert/ ?

**Comment by holocronology** [comment]
> Did you try http://[IP]/pialert/ ?

Yeah, I actually wrote that above but formatting made it unclear.

**Comment by leiweibau** [comment]
I will evaluate the installation process under DietPi again and, if necessary, point out special features in a readme

**Comment by leiweibau** [comment]
> I just installed with the script provided on Dietpi, which had pihole also installed, and in install script reported everything OK.

If you plan to install Pi-hole and Pi.Alert, please use the script provided by me to install both. The installation via dietpi-software will break the installation.

**Comment by leiweibau** [comment]
I have just completed an installation on a new DietPi 8.24.1. As the standard DietPi user usually has sudo rights, it was possible to run the installation as user Dietpi. In case of doubt, the installation can also be started with sudo as root. During the installation, I installed both Pi-hole and Pi.Alert. The installation went smoothly and both tools work correctly.

**Comment by holocronology** [comment]
> please use the script provided by me to install both

I had pihole already installed on the dietpi instance. Where is your pihole script? I don't recall seeing that.

**Comment by leiweibau** [comment]
When you start the installation script, it will ask you if you want to install Pi-hole as well, assuming it is not already installed.

**Comment by holocronology** [comment]
Yes, it does. However if you have Pihole installed via Dietpi-Software it will indicated that it is already installed and carry on. There is no indication, that I could see, that having PiHole installed via Dietpi-Software, when installing on Dietpi, is NOGO.
