### ISSUE TITLE
[Feature Request] Device counters in sidebar clickable

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#220]
Hello,
I like new device counters in left menu 
![image](https://github.com/leiweibau/Pi.Alert/assets/16610727/df57824c-66b4-4163-b6a5-7cd6b5dfd402)
I'd love to have them clickable and go to different device sections - orange would go to *New devices* and green go to *Connected*. Now if you click on them they go to the same "homepage" (/pialert/devices.php).
Thank you for consideration.
Radim

_Originally posted by @ramess18 in https://github.com/leiweibau/Pi.Alert/discussions/212_

**Comment by leiweibau** [comment]
Not as easy as I thought. :confused:

**Comment by leiweibau** [comment]
The bootstrap framework used is not designed for "links" within a parent "link" tag. You have to do a lot of trickery to get anything like this implemented. I only see a minimal gain here, which is not in relation to the effort involved. I admit, I thought it would be quick to implement, but unfortunately it's not. I am sorry

**Comment by ramess18** [comment]
OK. I understand. Thanks for the effort!
