### ISSUE TITLE
Issue with gethomepage/homepage widget

### ISSUE THREAD

**Issue by Aerodin** [leiweibau/Pi.Alert#225]
Hello,

I have the Homapage app to list all self hosted services in my network.  I'm currently trying to get the API portion to work.

Here is the original issue I opened with Homepage in case I was doing something wrong but wanted to mention it here too:
https://github.com/gethomepage/homepage/discussions/2568

Per this page it works perfectly:
https://gethomepage.dev/latest/widgets/services/pialert/

Once it was up and running I then enabled login password and changed the password.  I noted the API key from the config file and tried adding it in via API key when I saw that Homepage no longer could pull PiAlert details.  I'm assuming the API key would need to be utilized to make the right calls but even with this setup it wasn't working.  Any advice?

**Comment by leiweibau** [comment]
If I have read the code "homepage" correctly, then this widget was primarily written for the original Pi.Alert.

It does not access the API, but accesses the device list directly. 

```
const widget = {
  api: "{url}/php/server/devices.php?action=getDevicesTotals",
  proxyHandler: genericProxyHandler,
```

This works until the password protection is active. The API works without the password, but when using the API, a json is returned.
So if you want to use the widget, you cannot activate the password protection. If you want to use the API, the code of the widget would have to be adapted.

**Comment by leiweibau** [comment]
> Just trying to get the no-password display I had earlier before

I mistakenly asked you to add "/api/" to the URL. So you would have to remove that again. The ApiKey could also lead to an error.

I would like to go back to the different data that is provided here:

This widget queries the data from the backend directly. The backend outputs the data in this:

```
[56,26,6,0,0,4]
```

My Forkes also outputs this data via the backend without a password. However, since a password makes little sense if the backend itself does not require one, it refuses to output the data if password protection is activated. The API, on the other hand, outputs the data with the API key as follows:

```json
{
"Scanning":"On",
"Last_Scan":"11:35:00",
"All_Devices":60,
"Offline_Devices":30,
"Online_Devices":26,
"Archived_Devices":4,
"New_Devices":0,
"All_Devices_ICMP":4,
"Offline_Devices_ICMP":3,
"Online_Devices_ICMP":1,
"All_Services":5
}
```

I hope I have been able to shed some light on the subject.

**Comment by leiweibau** [comment]
> My Forkes also outputs this data via the backend without a password.

Unfortunately, I have to correct this statement. 

In the browser, if you have already called up the pialert page, it works, but if you try a query via the command line, it does not work. The reason for this is probably that if password protection is deactivated, a session is still created, but without a password. Only this session makes it possible to "talk" to the backend. This session is apparently not created via the command line, or is not used for a second call. At this point, I have to say that there is no way around the API. Even if I offer the data correctly via the API, "homepage" must also use the API.

**Comment by leiweibau** [comment]
This Widget is build for the docker version of Pi.Alert

https://github.com/gethomepage/homepage/blob/main/docs/widgets/services/pialert.md

Please follow the link in the readme to the correct fork.

**Comment by iraklis10** [comment]
```
- Pi.Alert:
        href: http://192.168.1.XXX/pialert/
        icon: pi-alert
        description: Check Network Devices
        widget:
            type: pialert
            url: http://192.168.1.XXX/pialert
```
actually work with this fork too. No need for API or setting a password.

**Comment by leiweibau** [comment]
thank you for the feedback
