### ISSUE TITLE
Pushover not working

### ISSUE THREAD

**Issue by jbierwiler** [leiweibau/Pi.Alert#233]
Tried to get it working through entering the token as well as user email and it just won't go through.

Is there something I might be missing?

**Comment by leiweibau** [comment]
You need these two things from your Pushover Dashboard:

PUSHOVER_TOKEN
- Also called "APP TOKEN" or "API TOKEN". This token can be queried on the pushover page.
- https://pushover.net/api#registration

PUSHOVER_USER
- Also called "USER KEY". This key is displayed right after login on the start page.

Pushover should actually work. I have also configured it myself and use it.

**Comment by jbierwiler** [comment]
That got it working, I didn't realize it needed to be an API token, thanks!

**Comment by leiweibau** [comment]
I am glad that I was able to help
