### ISSUE TITLE
No messages are sent after the update

### ISSUE THREAD

**Issue by Interfud** [leiweibau/Pi.Alert#236]
Test Reporting...
Sending report by email...
Traceback (most recent call last):
File "/root/pialert/back/pialert_reporting_test.py", line 308, in
sys.exit(main())
^^^^^^
File "/root/pialert/back/pialert_reporting_test.py", line 91, in main
res = sending_notifications_test('noti_Timerstop')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/pialert/back/pialert_reporting_test.py", line 128, in sending_notifications_test
send_email (notiMessage, notiMessage)
File "/root/pialert/back/pialert_reporting_test.py", line 274, in send_email
smtp_connection.login (SMTP_USER, escaped_password)
File "/usr/lib/python3.11/smtplib.py", line 750, in login
raise last_exception
File "/usr/lib/python3.11/smtplib.py", line 739, in login
(code, resp) = self.auth(
^^^^^^^^^^
File "/usr/lib/python3.11/smtplib.py", line 662, in auth
raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9 https://support.google.com/mail/?p=InvalidSecondFactor w11-20020a056512098b00b0050e8ea87dcesm1401366lft.169 - gsmtp')

**Comment by leiweibau** [comment]
You are right. I have just set up a Gmail account as a test and was confronted with the same error. The error message also refers to the problem.

```
Application-specific` password required. 
For more information, go to https://support.google.com/mail/?p=InvalidSecondFactor
```

I followed the instructions and created an app-specific password and saved it in the Pi.Alert Config. After that everything worked as it should. Unfortunately, I cannot explain why this effect occurred with the update.

**Comment by Interfud** [comment]
How to set this up in the config?
Thanks!

**Comment by leiweibau** [comment]
## Part one:

Create & use app passwords
Important: To create an app password, you need 2-Step Verification on your Google Account.

If you use 2-Step-Verification and get a "password incorrect" error when you sign in, you can try to use an app password.

- Go to your [Google Account](https://myaccount.google.com/).
- Select Security.
- Under "Signing in to Google," select 2-Step Verification.
- At the bottom of the page, select App passwords.
- Enter a name that helps you remember where you’ll use the app password.
- Select Generate.
- To enter the app password, follow the instructions on your screen. The app password is the 16-character code that generates on your device.
- Select Done.

## Part two:

Set password in Pi.Alert
- Open settings page
- Scroll at the bottom to the Config File Editor
- Set the App password
   `SMTP_PASS         = 'YOUR 16-CHARACTER CODE' `

**Comment by Interfud** [comment]
Thanks!
