### ISSUE TITLE
[Feature Request] Customizable columns for device list 

### ISSUE THREAD

**Issue by Porencephaly** [leiweibau/Pi.Alert#245]
It would be great to have the ability to change the order of the columns in the device list. (ie. being able to move "Last IP" directly next to "name"). 

Another nice feature, though less important than the above request, would being able to change the width of the columns and have it remain at the configured width instead of automatically changing based on the length of the longest name displayed. In case it's not clear, I'm thinking something somewhat similar to Excel in function. 

This is similar to Feature Request #63 though adds some new functionality

Thanks for your hard work!

**Comment by leiweibau** [comment]
Thank you for a constructive suggestion for improvement. :thumbsup: 
I have to say at this point that I will not be implementing this. I admit that this is far too much effort for me, which can also lead to many sources of error creeping in during implementation, and debugging Javascript is no fun for me. :cursing_face: 
I hope you understand that.

If someone makes a pull request in this regard, I would be happy to take a look at it.

**Comment by leiweibau** [comment]
Working on (https://github.com/leiweibau/Pi.Alert/issues/257) influences this feature request, because I explicitly address column IDs there. If the order changes, the predefined filter, which is dependent on the relevant column ID, will no longer work correctly.
