### ISSUE TITLE
graph misleading

### ISSUE THREAD

**Issue by JYewdall** [leiweibau/Pi.Alert#25]
I have 16 Devices, 1 Archived with 14 connected but the graph shows online/offline/
![pialert](https://user-images.githubusercontent.com/83168469/185809433-c41c374f-8519-4e31-9ae5-c258acd77c94.jpg)
archived  27/-10/0 or 28/-11/0 throughout the day?

**Comment by leiweibau** [comment]
The graph is displayed completely wrong. If you call `python3 ~/pialert/back/pialert.py 1` from the command line, does an error message appear?

What output appears after entering the command `sqlite3 ~/pialert/db/pialert.db "pragma table_info('Online_History');`

**Comment by JYewdall** [comment]
Pi.Alert 3.6_leiweibau (2022-08-15)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-08-22 09:11:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......: 13
        arp-scan Method....: 10
        Pi-hole Method.....: +0
        New Devices........: 0

    Devices in this cycle..: 13
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...
        Names updated:   0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...

Reporting...
    Formating report...
    No changes to report...
    Notifications: 0

DONE!!!


***@***.***:~ $ sqlite3 ~/pialert/db/pialert.db "pragma
table_info('Online_History');
>







John Yewdall
Email:  ***@***.***
Phone: 07795801495

**Comment by leiweibau** [comment]
Sorry ist Mist be
`sqlite3 ~/pialert/db/pialert.db "pragma table_info('Online_History');"`

**Comment by leiweibau** [comment]
Background: The "Offline" devices (in your case -10) are calculated. The script determined from the database the number of all devices and then subtracts all "Online" and "Archived" devices (also determined from the database). Actually no negative numbers can arise here. During the development I had sporadically similar cases, which were eliminated by emptying the browser cache.

**Comment by JYewdall** [comment]
***@***.***:~ $ sqlite3 ~/pialert/db/pialert.db "pragma
table_info('Online_History');"
0|Index|INTEGER|0||1
1|Scan_Date|TEXT|0||0
2|Online_Devices|INTEGER|0||0
3|Down_Devices|INTEGER|0||0
4|All_Devices|INTEGER|0||0
5|Archived_Devices|INTEGER|0||0

John Yewdall
Email:  ***@***.***
Phone: 07795801495

**Comment by leiweibau** [comment]
to verify the data in the db, can you run
`sqlite3 ~/pialert/db/pialert.db "SELECT * FROM Online_History ORDER BY Scan_Date DESC LIMIT 10"` please?

**Comment by JYewdall** [comment]
***@***.***:~ $ sqlite3 ~/pialert/db/pialert.db "SELECT * FROM
Online_History ORDER BY Scan_Date DESC LIMIT 10"
976|2022-08-22 09:55:00|27|-10|17|0
975|2022-08-22 09:50:00|27|-10|17|0
974|2022-08-22 09:45:00|27|-10|17|0
973|2022-08-22 09:40:00|27|-10|17|0
972|2022-08-22 09:35:00|27|-10|17|0
971|2022-08-22 09:30:00|27|-10|17|0
970|2022-08-22 09:25:00|27|-10|17|0
969|2022-08-22 09:20:00|27|-10|17|0
968|2022-08-22 09:15:00|27|-10|17|0
967|2022-08-22 09:11:00|27|-10|17|0

John Yewdall
Email:  ***@***.***
Phone: 07795801495

**Comment by leiweibau** [comment]
0 archived devices
17 devices at all
27 online devices on CurrentScan
Offline = 17 - 27 - 0
Offline = -10

The task now is to find out why there are more devices detected as "online" than devices in total.

`sqlite3 ~/pialert/db/pialert.db "SELECT cur_MAC,cur_IP,cur_ScanMethod FROM CurrentScan"`

This command displays all devices detected in the last scan (Mac, IP and source).

**Comment by leiweibau** [comment]
I'm not sure yet, but I'm afraid it's related to ipv6. Arp is a method to discover neighboring hosts in ipv4 environment. At the moment Pi.Alert is not yet fit for ipv6

**Comment by JYewdall** [comment]
***@***.***:~ $ sqlite3 ~/pialert/db/pialert.db "SELECT
cur_MAC,cur_IP,cur_ScanMethod FROM CurrentScan"
00:40:c7:ee:02:b8|192.168.158.30|arp-scan
00:04:23:a5:f3:e7|192.168.158.37|arp-scan
b8:27:eb:c0:4f:12|192.168.158.71|arp-scan
00:0b:82:fd:f7:6c|192.168.158.76|arp-scan
d8:38:0d:01:a9:d0|192.168.158.111|arp-scan
08:eb:74:9d:ad:04|192.168.158.180|arp-scan
00:d8:61:9e:b0:ac|192.168.158.198|arp-scan
1c:fe:2b:5f:00:56|192.168.158.181|arp-scan
90:73:5a:52:db:51|192.168.158.196|arp-scan
c8:6c:3d:63:4f:f5|192.168.158.200|arp-scan
08:cc:27:71:f9:7c|192.168.158.187|arp-scan
00:fc:8b:50:b5:cf|192.168.158.186|arp-scan
Internet|81.107.144.63|queryDNS
dc:a6:32:5a:26:54|192.168.158.72|local_MAC
00:40:c7:ee:02:b8|192.168.158.30|arp-scan
00:04:23:a5:f3:e7|192.168.158.37|arp-scan
b8:27:eb:c0:4f:12|192.168.158.71|arp-scan
00:0b:82:fd:f7:6c|192.168.158.76|arp-scan
d8:38:0d:01:a9:d0|192.168.158.111|arp-scan
08:eb:74:9d:ad:04|192.168.158.180|arp-scan
00:d8:61:9e:b0:ac|192.168.158.198|arp-scan
08:cc:27:71:f9:7c|192.168.158.187|arp-scan
90:73:5a:52:db:51|192.168.158.196|arp-scan
c8:6c:3d:63:4f:f5|192.168.158.200|arp-scan
1c:fe:2b:5f:00:56|192.168.158.181|arp-scan
Internet|81.107.144.63|queryDNS
dc:a6:32:5a:26:54|192.168.158.72|local_MAC
***@***.***:~ $



John Yewdall
Email:  ***@***.***
Phone: 07795801495

**Comment by JYewdall** [comment]
Can we have the ability to hide that graph?

John Yewdall
Email:  ***@***.***
Phone: 07795801495

**Comment by leiweibau** [comment]
Okay, no ipv6 problem.
Each host is in the database twice after the scan. Now the question is: why?

Okay. I'll get to it today and create a way to hide the graph. But the actual question remains.

**Comment by leiweibau** [comment]
With this commit, the graph is optional https://github.com/leiweibau/Pi.Alert/commit/56269f8fbae96b55555c921fa5cff6879ea329bc

**Comment by JYewdall** [comment]
How do I install it.

**Comment by leiweibau** [comment]
Download https://github.com/leiweibau/Pi.Alert/archive/refs/heads/main.zip

Unpack and then copy the folder "front" to "~/pialert/" and replace the existing folder. After that, you can disable the graph on the maintenance page.

**Comment by JYewdall** [comment]
Thanks. Graph now disabled.

**Comment by leiweibau** [comment]
After fixing the other error, the graph should work again in your case as well. The corresponding commit is https://github.com/leiweibau/Pi.Alert/commit/ba082821c768bd0800cdd7026abcca22fa0a12a5, in case you are interested

**Comment by JYewdall** [comment]
now working. Thanks
