### ISSUE TITLE
Permissions being reset on database

### ISSUE THREAD

**Issue by jbierwiler** [leiweibau/Pi.Alert#250]
Twice now the database permissions were reset which caused it to stop processing updates to the database.

I noticed it this morning and looking at the events log it seemed to s top on 1/28th at 11:45pm since that is the last event I see before it reconnected today after fixing the permissions. 

I had originally thought it was perhaps the updates that did it, but that timeline doesn't match up.

![image](https://github.com/leiweibau/Pi.Alert/assets/9615039/8255605d-729f-40b5-bf95-6af909e598a7)

**Comment by jbierwiler** [comment]
For the record running the permissions fix fixed it, more hoping you have an idea of WHY it might be breaking.

I did add a second > into the crontab for the logging so I can see a bigger log and hopefully pinpoint where the failure is happening.

**Comment by leiweibau** [comment]
The status box on the settings page should primarily serve as an indicator for the correct permissions. Here you will find the line with the date of the last change to the database file. This should be as up-to-date as possible, i.e. within the 2-3 minute time window of the last scan. Neither in the backend nor in the frontend is there a function that changes the file authorization of the database. For now, I can only imagine an external influence. It would be interesting to know what the changed permissions are. 
I will have another look at the code later to check whether I can offer you a quick fix if the error recurs.

**Comment by leiweibau** [comment]
Since I have not yet experienced this error and cannot reproduce it, you are welcome to test this extended pialert.py version. [Commit](https://github.com/leiweibau/Pi.Alert/commit/4833824cc2cd9fffc5e1d947809f794f3e81d68b)

[pialert.py](https://raw.githubusercontent.com/leiweibau/Pi.Alert/4833824cc2cd9fffc5e1d947809f794f3e81d68b/back/pialert.py)
This file must be saved in the directory $HOME/pialert/back/. Make a backup of the old version first.

**Comment by jbierwiler** [comment]
Thank you for looking, I'll take a look at that.

I agree, I have no idea what caused it so I'm keeping a very close eye on everything. 

I'll let you if I see it again.
