### ISSUE TITLE
Validation in maintenance.php don´t work

### ISSUE THREAD

**Issue by sourceforge807** [leiweibau/Pi.Alert#26]
Dear leiweibau,

first, thank you for your work of this addon of pialert.

Now i found possible a bug in the maintenance.php. At my installation this site show no content after the header. After debugging i found that the if statement from the skin- and languageselector is not working.

This solves the Problem:
//if (submit && isset($_POST['skinselector_set'])) {
if (isset($_POST['skinselector_set']) && isset($_POST['skinselector'])) {

and:

//if (submit && isset($_POST['langselector_set']) {
if (isset($_POST['langselector_set']) && isset($_POST['langselector'])) {

And in the es_es.php language file there are some unfilled variables:

$pia_lang['Maintenance_Github_package_b'] ='';
$pia_lang['Maintenance_Tool_loginenable'] ='';
$pia_lang['Maintenance_Tool_loginenable_text'] ='';
$pia_lang['Maintenance_Tool_loginenable_noti'] ='';
$pia_lang['Maintenance_Tool_loginenable_noti_text'] ='';
$pia_lang['Maintenance_Tool_logindisable'] ='';
$pia_lang['Maintenance_Tool_logindisable_text'] ='';
$pia_lang['Maintenance_Tool_logindisable_noti'] ='';
$pia_lang['Maintenance_Tool_logindisable_noti_text'] ='';

Thank you for your work!!

**Comment by leiweibau** [comment]
I just installed the current package into a virtual machine and cannot reproduce your problem with language and skin selection. However, I have adopted your workaround.

Yes, the Spanish language file is missing a few translations in the current package. The contributor of the translation has not pushed a current version yet. I have added the missing translations (hopefully correct) in my 2nd branch with the help of deepl.com
