### ISSUE TITLE
[Feature Request] Notification Templates / ntfy config

### ISSUE THREAD

**Issue by upD8R** [leiweibau/Pi.Alert#261]
Hi there,

I just realized there are notification templates part of the installation - are they maintained during an upgrade if I change them or do you plan to support custom templates?

A second feature request:
Started to use ntfy.sh - could you please make the "Click" option optional/configurable in the pi.alert settings (simple yes/no would be good, and as a bonus a configurable URL instead of the default pi.alert URL)?

Thanks in advance and pls keep going ;-)

**Comment by leiweibau** [comment]
> I just realized there are notification templates part of the installation - are they maintained during an upgrade if I change them or do you plan to support custom templates?

Yes, these are overwritten during an update.

> Started to use ntfy.sh - could you please make the "Click" option optional/configurable

I'll take a look at this

**Comment by leiweibau** [comment]
The first part of your wish will be released with the next update.

Could you help me understand why you want to submit a separate URL for ntfy that is different from the Pi.Alert dashboard?

**Comment by upD8R** [comment]
Thanks in advance 👍🏻

I don't have a specific use case in mind but I'm a big fan of flexibility. I'm currently not exposing Pi.Alert outside of my own network but if I would, it would be different FQDN, wouldn't it?

**Comment by upD8R** [comment]
Also using VPN here but there might be people who are using reverse proxy or similar mechanisms ...

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/c96da56cd10c277feca9c36fc1b45e715f00bf2b
The release does not yet have the option of storing an individual URL, but I'll keep it in mind.
