### ISSUE TITLE
Mqtt doesn't work as expected

### ISSUE THREAD

**Issue by mironalessandro** [leiweibau/Pi.Alert#266]
Hello is the first time that i'm trying to use mqtt broker on pi alert to send all infos to my home assistant instance.

I already set up all the parameters of my mqtt broker(i have a lot of other services on this broker)

The log of pi.alert says this: 

23:53:15 [2024-03-02 23:53:15+01:00] [Test] START Test: MQTT
23:53:15 [Notification] Udating API files
23:53:16 [2024-03-02 23:53:16+01:00] START Run: MQTT
23:53:16 [MQTT](publisher) In script
23:53:16 [Database] Opening DB
23:53:16 [plugin_helper] reading config file
23:53:16 [MQTT](publisher) In script
23:53:16 [Database] Opening DB
Traceback (most recent call last):
  File "/home/pi/pialert/front/plugins/_publisher_mqtt/mqtt.py", line 363, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/pialert/front/plugins/_publisher_mqtt/mqtt.py", line 61, in main
    mqtt_start(db)
  File "/home/pi/pialert/front/plugins/_publisher_mqtt/mqtt.py", line 255, in mqtt_start
    client = mqtt_create_client()     
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pialert/front/plugins/_publisher_mqtt/mqtt.py", line 239, in mqtt_create_client
    client = mqtt_client.Client('PiAlert')   # Set Connecting Client ID    
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myenv/lib/python3.11/site-packages/paho/mqtt/client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details

23:53:16 [Plugins] ⚠ ERROR - enable LOG_LEVEL=debug and check logs
23:53:16 [Plugins] No output received from the plugin MQTT - enable LOG_LEVEL=debug and check logs
23:53:16 [2024-03-02 23:53:16+01:00] END Run: MQTT
23:53:16 [Test] END Test: MQTT

i just check with MQTT Explorer and i don't see anything. Seems a bug or something like this. 

I'm using the last public version of pi.alert. 

#App updates 	
#You are up-to-date. Check out what [I am working on](https://github.com/jokob-sk/Pi.Alert/issues/138).
#Built on	2024-02-16
#Installed version	v24.2.17

**Comment by jokob-sk** [comment]
Hey @mironalessandro ,

Looks like you posted this in the incorrect fork. Please check this issue on my fork: https://github.com/jokob-sk/Pi.Alert/issues/580

Thanks,
jokob
