### ISSUE TITLE
[Feature Request] Add PUSHOVER sound option to specify sound

### ISSUE THREAD

**Issue by johnny-tknoska** [leiweibau/Pi.Alert#268]
It would be great to add a PUSHOVER_SOUND setting in pialert.conf at the pushover settings section to specify the sound for notifications (https://pushover.net/api#sounds).

**Comment by leiweibau** [comment]
Okay. I will work on that in the next few days.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/065eb76cc8720ba9f931703588b34e21441fb836
