### ISSUE TITLE
[Bug] root user without sudo package

### ISSUE THREAD

**Issue by govwin** [leiweibau/Pi.Alert#269]
If logged in with root user and `sudo` is not installed, the install script fails. 
Please change the install script: if current user is already root, then skip `sudo`. 
The work around is to install `sudo`.

**Comment by accessiblepixel** [comment]
I experienced the same issue when I just installed using the installer script too :)

**Comment by leiweibau** [comment]
I will add the "sudo" package to the installation script

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/065eb76cc8720ba9f931703588b34e21441fb836
