### ISSUE TITLE
Allow configuring notification settings so default is to send if opt-in vs opt-out

### ISSUE THREAD

**Issue by jaxley** [leiweibau/Pi.Alert#270]
Currently, I looks like alerts are sent for all types by default unless you go in and manually configure every device to disable certain alerts types. This results in a really noisy system that hides information for devices I really care about. I get connect and disconnect notifications but I don't care about those unless it's a new device. 

The only way it seems I can tune this is to opt out of alerts one device at a time. This is tedious.

Would love to have default to send nothing unless enabled for a select set of devices. Has there been thought about simplifying tuning of alerts?

Cheers

**Comment by leiweibau** [comment]
There is a bulk editor with which you can switch off the alarm for all devices at once. Perhaps this will help you a little.

https://github.com/leiweibau/Pi.Alert/blob/main/docs/BULKEDITOR.md

If the default setting for a device is "no notification", Pi.Alert can no longer perform its task of notifying you of new devices. There is no distinction between the "default setting" for a known device and the "default setting" for a new device, as every known device was once a new device.

**Comment by leiweibau** [comment]
Closed due to missing feedback
