### ISSUE TITLE
Universal time / local time

### ISSUE THREAD

**Issue by marktn** [leiweibau/Pi.Alert#276]
Hi,

The local time is okay, only Pi Alert is using Universal Time.
How to change that? 

root@pialert:~# timedatectl status
                Local time: Tue 2024-03-19 21:51:08 CET
                Universal time: Tue 2024-03-19 20:51:08 UTC
                 RTC time: n/a
                Time zone: Europe/Amsterdam (CET, +0100)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no

**Comment by leiweibau** [comment]
Go to the „Help/FAQ“ page and follow the instructions from the first entry „The clock on the top right and the times of the events/presence are not correct (time difference).“

**Comment by marktn** [comment]
Found it! Type mistake of myself,,,
