### ISSUE TITLE
[BUG] Error Updating Pi.Alert

### ISSUE THREAD

**Issue by sstiju** [leiweibau/Pi.Alert#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

During the update process using the command “bash -c “$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)””, I receive the following error message: “Pi.Alert directory doesn’t exist: /root/pialert”. 
PiAlert is running in an LXC container on Proxmox. The installation directory for PiAlert is /etc/.

### Environment

Debian 12.2
LXC
Proxmox 8.1

**Comment by leiweibau** [comment]
https://github.com/leiweibau/Pi.Alert/issues/281
