### ISSUE TITLE
[Bug] Device's selected Uplink Target shows a number, not the device name.

### ISSUE THREAD

**Issue by ajtatum** [leiweibau/Pi.Alert#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

When editing a device, when you click on the dropdown for "Uplink Target", it shows a list of possible devices by name. However, once an "Uplink Target" is selected, it shows just a number. Upon saving and viewing the device again, it still shows a number, which makes it difficult to tell what the "Uplink Target" is.

Here are some screenshots:
![thorium_S9cVIhSll9](https://github.com/leiweibau/Pi.Alert/assets/318022/ea7a1e8a-fe3b-4fbe-a67b-123f2bf59903)

![thorium_1qaNU4A3bS](https://github.com/leiweibau/Pi.Alert/assets/318022/c29ad71d-bbc8-415f-a4f3-9457278735f3)

### Environment

**OS:** Debian 12
**Installation Method:** [Used the Proxmox script by tteck](https://tteck.github.io/Proxmox/). Which creates an LXC by running the following command:

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/pialert.sh)"`

### Anything else?

I may not have noticed it before, but I thought at one point the Edit Device screen showed the Uplink Target's name.

**Comment by leiweibau** [comment]
This is not a bug, but exactly as intended. The number is saved, not the name

**Comment by ajtatum** [comment]
That makes sense. It would be much easier to verify that Uplink Target if the matching number could be shown in the drop-down menu. I would greatly appreciate it!
