### ISSUE TITLE
[Bug] Tiny bit of text untranslated as part of new nmap functionality.

### ISSUE THREAD

**Issue by accessiblepixel** [leiweibau/Pi.Alert#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

Hi!

I installed the new update with the nmap result caching and noticed a bit of text that wasn't in my own locale. When you go back to a page and see the cached results it says ``Es befinden sich 1 Scan-Ergebnisse in der Datenbank`` which if my German is good enough is basically There's one scan in the database.

Thanks :)
Hope you're well. (Everything else is working as expected)

**Comment by leiweibau** [comment]
I hereby certify that you have a sound knowledge of German 😉

Thanks for the message, I'll take care of it

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/8f9738669bbc3204d1804ab0cfd507d191ac71f0
