### ISSUE TITLE
[Bug] Initial database was missing

### ISSUE THREAD

**Issue by xxLexanixx** [leiweibau/Pi.Alert#294]
There are no devices from my network in the list. The log file shows the following error

Pi.Alert v2024-04-14
---------------------------------------------------------
Executing user: root

Scan Devices
    Timestamp: 2024-04-15 09:00:00

Prepare Scan...
    Force file permissions on Pi.Alert db...
        DB permission mask: 775
        DB Owner and Group: root:www-data
Traceback (most recent call last):
File "/root/pialert/back/pialert.py", line 3088, in
    sys.exit(main())    
             ^^^^^^
File "/root/pialert/back/pialert.py", line 95, in main
    res = scan_network()
         ^^^^^^^^^^^^^^
File "/root/pialert/back/pialert.py", line 668, in scan_network
    scanCycle_data = query_ScanCycle_Data (True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/pialert/back/pialert.py", line 784, in query_ScanCycle_Data
    sql.execute ("""SELECT cic_arpscanCycles, cic_EveryXmin
sqlite3.OperationalError: no such table: ScanCycles

**Comment by xxLexanixx** [comment]
new install the premission on the db is correctly
![image](https://github.com/leiweibau/Pi.Alert/assets/16607717/e0729dd2-be39-4d55-9cc9-6ed5175f94fb)

**Comment by leiweibau** [comment]
I have just realized with horror that the database folder is empty, because the database should be larger than 4kb. I will fix this in the next 1-2 hours.

**Comment by xxLexanixx** [comment]
Thanks!

**Comment by leiweibau** [comment]
Can you try it again?

**Comment by leiweibau** [comment]
I have just done a new installation. The problem should be solved.
