### ISSUE TITLE
[Feature Request] Pause button for ICMP queries

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#296]
I propose a "pause" button for ICMP queries on a per device basis.  This would have the effect of temporarily skipping the ICMP poll for that device.

This would be useful in the case in which I know a particular device is going to be down for an extended time, but I don't want to delete it from the database so it can be monitored when it comes back online.  It would make polling more efficient by skipping devices that are known that won't respond.

**Comment by leiweibau** [comment]
Something like "Archived" or "Do not scan for x hours or days"?

**Comment by hspindel** [comment]
Thank you.

Maybe archived, if archived means it can be easily resurrected for scanning when desired.

I think "do not scan for x" would be less useful because it would require knowing in advance how long the device would be down.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/91d0f5770f2498e084d0167b202029f841974e4c
