### ISSUE TITLE
[Multi-VLAN scanning]

### ISSUE THREAD

**Issue by dustingrady** [leiweibau/Pi.Alert#299]
It would be very nice to be able to scan across multiple VLANS by specifying the IP ranges (such as 192.168.0.0/16).

Currently, it appears to only scan the /24 of the network it is installed on.

**Comment by dustingrady** [comment]
Thanks so much for the reply!
So if I have this running on a trunk'd interface, I should just be able to specify as follows using the same interface?

`SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=ens18', '192.168.2.0/24 --interface=ens18', '192.168.3.0/24 --interface=ens18' ]`

**Comment by leiweibau** [comment]
It may be that this also works. I have only tried it a few times in a virtual environment with several interfaces. With the virtual interfaces, I actually had these in mind

```
SCAN_SUBNETS = [ '192.168.1.0/24 --interface=ens18', '192.168.2.0/24 --interface=ens18:0', '192.168.3.0/24 --interface=ens18:1' ]
```

**Comment by dustingrady** [comment]
Ah, so each interface would be assigned to a different VLAN. That makes sense.
Is there by chance a way to scan the different `SCAN_SUBNETS` definitions via ICMP (iterating over a range of IPs) or is that not currently supported?

**Comment by leiweibau** [comment]
> Is there by chance a way to scan the different SCAN_SUBNETS definitions via ICMP (iterating over a range of IPs) or is that not currently supported?

Unfortunately not. This option is not available at the moment. I have addressed the difficulty of implementation here.

https://github.com/leiweibau/Pi.Alert/issues/271#issuecomment-1992650670

https://github.com/leiweibau/Pi.Alert/issues/272#issuecomment-2021257018

https://github.com/leiweibau/Pi.Alert/issues/272#issuecomment-2021531373

**Comment by dustingrady** [comment]
I was actually able to accomplish this using 1 Pi Alert instance and setting multiple network interfaces on the Proxmox instance that hosts the VM. I then setup each interface to the corresponding VLAN using the `/etc/network/interfaces` config. This works for me, but I understand it is not a straight forward solution.

**Comment by dimatx** [comment]
> I was actually able to accomplish this using 1 Pi Alert instance and setting multiple network interfaces on the Proxmox instance that hosts the VM. I then setup each interface to the corresponding VLAN using the `/etc/network/interfaces` config. This works for me, but I understand it is not a straight forward solution.

This helped me as I'm also running proxmox. Thanks!

**Comment by dustingrady** [comment]
No problem @dimatx, glad it helped someone.
