### ISSUE TITLE
[Documentation] List of all settings?

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#301]
Hi,

I was going through the pi.alert config and just wondering what some of the settings were and what to put in some of the fields.

For example just one of them is pushover:
# Pushover
# ----------------------
REPORT_PUSHOVER         = False
REPORT_PUSHOVER_WEBMON  = False
PUSHOVER_TOKEN          = ''"
PUSHOVER_USER           = ''"

I know what some of the settings should be but no idea on others like "REPORT_PUSHOVER_WEBMON" or  "PUSHOVER_USER" (should this be my email address?).

Another is:
# Special Protocol Scanning
# ----------------------
SCAN_ROGUE_DHCP        = True
DHCP_SERVER_ADDRESS    = ''

Does this only work with some DHCP servers or all?

I'm just wondering if there's a page with all settings explained and what to put in each field because I cannot find one and it would be helpful? Especially as new features are added?

Thanks.

**Comment by leiweibau** [comment]
Yes, this page exists: Help/FAQ.
It is not quite complete, but most of it is there.

**Comment by leiweibau** [comment]
Is marked here (https://github.com/leiweibau/Pi.Alert/issues/312) as a topic to be documented.
