### ISSUE TITLE
[Bug] Issue when editing config file from WebUI

### ISSUE THREAD

**Issue by Striffly** [leiweibau/Pi.Alert#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

When I edit the configuration file from the WebUI interface, I get an error 500 related to `front/php/server/files.php`, because the script can't write to `config/pialert.conf` file.

### Environment

**OS**: Debian 12
**Environment**: native
**Platform**: Arm

### Anything else?

This error is due to the fact that the user `www-data` does not belong to the group of the user (for example: `joe`) in which the pialert folder is located (`/home/joe`).
One solution would be to create a dedicated user (`pialert`) in which the installation would be performed, and add `www-data` to the `pialert` group.

**Comment by leiweibau** [comment]
What is your setup? With a freshly installed Debian 12, the default user is not configured as "sudoer". Did you install Pi.Alert as root, or did you configure your user as "sudoer"?

**Comment by Striffly** [comment]
I use a Debian 12 with PiHole & PiVPN, & with a custom user who is sudoer (no propblem when installing PiHole & PiVPN).

**Comment by leiweibau** [comment]
I have set up a virtual machine for testing with the Debian 12.5 ISO. I had to do the following things before installing Pi.Alert

1. add the user to the sudo group
2. install the package "curl", as this does not seem to be included in the standard installation of Debian 12 (the installation script is updated here).

Then I did an installation with "sudo", which results in Pi.Alert being installed under "/root". Afterwards, the "pialert.conf" could be edited and saved as desired via the web interface.

Here are the permissions of the file after successful authorization via the web interface.

<img width="525" alt="pialert" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/26d672e0-d923-4f02-84f2-087f53e9d485">
<img width="624" alt="config" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/84c9cb54-c8d3-4c5a-8368-d55185f41b28">

**Comment by leiweibau** [comment]
I then deleted Pi.Alert again and reinstalled it under the user I had set up during the installation. Again, everything works as expected.

Here are the permissions of the file after successful editing via the web interface.

<img width="534" alt="pialert" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/f8162c57-3c13-452e-a793-488cc6e830a8">
<img width="611" alt="config" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/dad8477a-be51-4058-9167-4917f914c74a">

**Comment by Striffly** [comment]
Okay, I'll do a double check about this
Thank you for your follow-up
