### ISSUE TITLE
[Bug] Scan log only shows "A terminal is required to read the password"

### ISSUE THREAD

**Issue by dustingrady** [leiweibau/Pi.Alert#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

When checking the `Scan` log, the following is displayed:

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

### Environment

Debian 12 with the one-step installer

### Anything else?

I'm not sure if it's the intention or not, but PiAlert seems to need WAN access to run. I'm trying to run this internally with no internet access to the outside world (I do not need to track my WAN IP, only RFC1918 ones)

**Comment by leiweibau** [comment]
I know https://github.com/leiweibau/Pi.Alert/issues/128#issue-1779345163

Is everything else working correctly? If this is the case, I will close the issue again.

**Comment by leiweibau** [comment]
Or, maybe you missed the point with this command:
`sudo $HOME/back/pialert-cli set_sudoers`

**Comment by leiweibau** [comment]
I am closing this issue due to lack of feedback
