### ISSUE TITLE
Pi.Alert doesn't send out alert email?

### ISSUE THREAD

**Issue by taintran** [leiweibau/Pi.Alert#31]
Can you please help why Pi.Alert doesn't send out alert email?

/home/pi/pialert/config/pialert.conf

```
# Mail-Account Settings

# ----------------------
SMTP_SERVER       = 'smtp.mail.yahoo.com'
SMTP_PORT         = 587
SMTP_USER         = '_____@yahoo.com'
SMTP_PASS         = '__________'
SMTP_SKIP_TLS	  = False
SMTP_SKIP_LOGIN	  = False

# Mail Reporting
# ----------------------
REPORT_MAIL       = True
REPORT_FROM       = 'Pi.Alert <' + SMTP_USER +'>'
```

/home/pi/pialert/log/pialert1.log

```
Pi.Alert 3.7.6_leiweibau (2022-10-14)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-10-16 21:25:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......: 79
        arp-scan Method....: 73
        Pi-hole Method.....: +0
        New Devices........: 0

    Devices in this cycle..: 79
        Down Alerts........: 1
        New Down Alerts....: 1
        New Connections....: 0
        Disconnections.....: 4
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name.......................................................................................................................
        Names updated:   0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...
    Calculate Activity History...

Reporting...
    Formating report...
    No changes to report...
    Notifications: 0

DONE!!!
``` 

Thank you so much!

**Comment by leiweibau** [comment]
The log above says "No changes to report...", so there is no mail. This version of Pi.Alert has a button to test notifications. Did this button send an eMail?

`~/pialert/back/pialert-cli reporting_test` can also send a notification with optional error messages.

**Comment by leiweibau** [comment]
Maybe the solution to your problem is the missing check mark at "Alert All Events". If this checkbox is not enabled, there is no reporting at all for this device, if I read the source code correctly.

```   
 # Disable reporting on events for devices where reporting is disabled based on the MAC address
    sql.execute ("""UPDATE Events SET eve_PendingAlertEmail = 0
                    WHERE eve_PendingAlertEmail = 1 AND eve_MAC IN
                        (
                            SELECT dev_MAC FROM Devices WHERE dev_AlertEvents = 0
						)""")
```

This part of the code comes from the main project.

**Comment by taintran** [comment]
> The log above says "No changes to report...", so there is no mail. This version of Pi.Alert has a button to test notifications. Did this button send an eMail?
> 
> `~/pialert/back/pialert-cli reporting_test` can also send a notification.

```
pi@raspberrypi:~ $ ~/pialert/back/pialert-cli reporting_test

Pi.Alert 3.7.6_leiweibau (2022-10-14)
---------------------------------------------------------

Test Reporting...
    Sending report by email...
    Skip PUSHSAFER...
    Skip NTFY...
    Skip Telegram...

DONE!!!


Test executed
```

Test is executed but still no email

**Comment by taintran** [comment]
> Maybe the solution to your problem is the missing check mark at "Alert All Events". If this checkbox is not enabled, there is no reporting at all for this device, if I read the source code correctly.
> 
> ```
>  # Disable reporting on events for devices where reporting is disabled based on the MAC address
>     sql.execute ("""UPDATE Events SET eve_PendingAlertEmail = 0
>                     WHERE eve_PendingAlertEmail = 1 AND eve_MAC IN
>                         (
>                             SELECT dev_MAC FROM Devices WHERE dev_AlertEvents = 0
> 						)""")
> ```
> 
> This part of the code comes from the main project. I am already testing a possible solution to optimize this behavior

Yes, the checkbox of "Alert All Events" is unchecked. But I did checked the box "Alert Down" and save, and then a few minutes later unplug the device to make it down. Pi.Alert recognized the device is down but still no email.

**Comment by taintran** [comment]
I also
1. Add port 587 to the router setting for port forwarding 
2. Tried the app passwords https://support.google.com/accounts/answer/185833?hl=en for SMTP_PASS field. But still no email is sent out.

```
# Mail-Account Settings
# ----------------------
SMTP_SERVER       = 'smtp.gmail.com'
SMTP_PORT         = 587
SMTP_USER         = '________@gmail.com'
SMTP_PASS         = '_______________'
SMTP_SKIP_TLS	  = False
SMTP_SKIP_LOGIN	  = False

# Mail Reporting
# ----------------------
REPORT_MAIL       = True
```

anywhere in the configuration or log that you can help me check?

**Comment by leiweibau** [comment]
You did not receive a test email? Did you check your spam folder? Have you tried another mail account? 
I just worked on the notification and sent dozens of mails. I can't imagine any program error here (of course I can't exclude it either)

No port forwarding is necessary here. In your case it is completely wrong. Please take it out of your router.

**Comment by taintran** [comment]
> You did not receive a test email? Did you check your spam folder? I just worked on the notification and sent dozens of mails. I can't imagine any program error here (of course I can't exclude it either)
> 
> No port forwarding is necessary here. In your case it is completely wrong. Please take it out of your router.

I just re-test with 
~/pialert/back/pialert-cli reporting_test
and it works now. Probably 1 & 3 solve the issue. 
1. Sent a regular email from SMTP_USER email address to REPORT_TO email address to make sure it not list as Spam/Junk.
3. Tried the app passwords https://support.google.com/accounts/answer/185833?hl=en for SMTP_PASS field.

**Comment by taintran** [comment]
> You did not receive a test email? Did you check your spam folder? I just worked on the notification and sent dozens of mails. I can't imagine any program error here (of course I can't exclude it either)
> 
> No port forwarding is necessary here. In your case it is completely wrong. Please take it out of your router.

I just re-test with 
```
~/pialert/back/pialert-cli reporting_test
```
and it works now. Probably these solve the issue. 
1. Sent a regular email from SMTP_USER email address to REPORT_TO email address to make sure it not list as Spam/Junk.
2. Tried the app passwords https://support.google.com/accounts/answer/185833?hl=en for SMTP_PASS field.

Thank you so much.

**Comment by leiweibau** [comment]
I have just tested sending mail via gmail and could not find any errors. I'm glad you were able to solve the problem.

As already written, I will revise the notification behavior a bit. In the next days I will provide an update package.
