### ISSUE TITLE
[Bug] Fixed MAC addresses are detected as "Random MAC"

### ISSUE THREAD

**Issue by waywit** [leiweibau/Pi.Alert#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

I have different AVM FritzRepeater 2400, 3000 and 3000 AX in my network. All with fixed IPs over pi.hole DHCP MAC mappings, but they are all detected as "Random MAC". I also have this issue with some of my proxmox lxc and VMs, but some are detecxted correctly. I have no idea how this mechanism works and a random MAC is detected, so I have no idea what to change?!?!

### Environment

Raspberry Pi 4 with 4 GB RAM and SSD boot drive, newly setup with actual RaspiOS together with a pi.hole installed. Pi.Hole is DHCP and DNS server in network. Fritzbox 7590 for internet access without DHCP.

### Anything else?

Perhaps this is no Bug, but I have no Idea what I can do to remove these "Random Mac" badge, because of this I cannont use the Manufacturer field... :-( Perhaps someone can help me with that.

By the way, great piece of software and a lot better then the original version I used some years ago....

**Comment by leiweibau** [comment]
This is not a bug.

> I have no idea how this mechanism works and a random MAC is detected, so I have no idea what to change

MAC address schemes are classified as "random" MAC addresses:
x2:xx:xx:xx:xx:xx:xx
x6:xx:xx:xx:xx:xx:xx
xA:xx:xx:xx:xx:xx:xx
xE:xx:xx:xx:xx:xx:xx

You can find out more about the background here.
https://en.wikipedia.org/wiki/MAC_address#Locally_administered_address

> By the way, great piece of software and a lot better then the original version I used some years ago....

Thanks for the praise

**Comment by leiweibau** [comment]
Is marked here (https://github.com/leiweibau/Pi.Alert/issues/312) as a topic to be documented.
