### ISSUE TITLE
[Bug] Error when looking for Rogue DHCP

### ISSUE THREAD

**Issue by sgr78** [leiweibau/Pi.Alert#313]
Hello,
Maybe It's me, I may have something overlooked, configuration issue or Is it PiAlert issue, here it goes.
I'm having this Issue a long time (six months or more and still researching It)..
I have two Instances of PiAlert one for production and one for tests, 
The first Instance is a VM with no Issues at all and the second one is a bare deploy on a Pi 5 with Pi OS Lite,
On the Pi 5 I have two IF, Eth0 and Wlan0 which are actively connected for redundancy,
with preset ip pool based on mac address from my main router, yet Pi device is set to AUTO and sends request properly and gets offer..

The Issue is when the Rogue DHCP runs I always get on the Pi 5
```
Looking for Rogue DHCP Servers...
    Detection Error
```
I have ran
and concluded sucessfuly with no errors at all
```
nmap --script broadcast-dhcp-discover
nmap --script broadcast-dhcp-discover -e eth0
nmap --script broadcast-dhcp-discover -e wlan0
dhclient -d -nw eth0
dhclient -d -nw wlan0
ip route | grep default
```
I also peeked at the source code of pialert on the Rogue DHCP Section and ran
`nmap --script broadcast-dhcp-discover 2>/dev/null | grep "Server Identifier" `
Which also concluded successfully and returned as expected two Server Identifiers because of Eth and Wlan 
(with same DHCP server IP, as it is connected on the same network)

Yes I have tried disabling one of the two IF, just to test if the Issue is caused by multiple enabled IF with multiple DHCPs (even though it is the same server on both) but no dice...

I'm running out of Ideas here and any help/guidance will be much welcomed and appreciated!

**Comment by leiweibau** [comment]
The "Detection Error" error is output if the "validate_dhcp_address" function returns a "False", i.e. it is not a valid IPv4 address according to the function. It would now be useful to check what output the command `sudo nmap --script broadcast-dhcp-discover 2>/dev/null | grep "Server Identifier" | awk '{ print $4 }'` returns for the device in question and what the difference is to the other device.

**Comment by sgr78** [comment]
It works on both systems
On the VM with one IF, I get only one IP response

On the Pi 5, I get two similar IP 
(the same DHCP Server as above but twice due to eth and Wlan being actively connected), no errors at all.

I expected to get a message in PiAlert like 
```
DHCP server found: IP address
Too many or Duplicate DHCP address
```
Instead on PiAlert I only get _Detection Error_...

**Comment by sgr78** [comment]
Nmap_DHCP_Server
dhcp_server table reads
`10.10.10.110.10.10.1`
the two IPs "bonded"together

I have edited the  pialert.py, as per your Instructions
and replaced the section with
`def validate_dhcp_address(ip_string):
   return True`

**Comment by leiweibau** [comment]
Okay 10.10.10.110.10.10.1 is def. wrong

**Comment by sgr78** [comment]
> Okay 10.10.10.110.10.10.1 is def. wrong

and just got a message in a Noice Red Background
```
Rogue DHCP Server
Detected Server(s): 10.10.10.110.10.10.1
```

**Comment by leiweibau** [comment]
Now that we know where the error is, you can undo the change. I now have to see how I can prevent this error with the connected IP addresses.

**Comment by sgr78** [comment]
> Now that we know where the error is, you can undo the change. I now have to see how I can prevent this error with the connected IP addresses.

Thanks, glad to be of help and glad that a solution Is on the way!! 👍

**Comment by leiweibau** [comment]
> and glad that a solution Is on the way

I haven't written anything about a solution yet 😉

**Comment by leiweibau** [comment]
Background:
With the scan, I have so far assumed that only one DHCP server is output. With the expected result, I remove the line break. However, since in your case (several interfaces) 2 servers are output, the line break is removed here, which leads to this "invalid" IP.

**Comment by leiweibau** [comment]
Can you try this fix?

https://raw.githubusercontent.com/leiweibau/Pi.Alert/d32a914dd67ea16a634a01754f7b49c3425b0862/back/pialert.py

**Comment by sgr78** [comment]
> Can you try this fix?
> 
> https://raw.githubusercontent.com/leiweibau/Pi.Alert/d32a914dd67ea16a634a01754f7b49c3425b0862/back/pialert.py
On It,
Applied it and patiently waiting!

**Comment by leiweibau** [comment]
> Detection Error

Can you take another look at the table in the database to see what it says?

**Comment by sgr78** [comment]
> > Detection Error
> 
> Can you take another look at the table in the database to see what it says?

It was showing only one entry per line
BUT
I proceeded and cleared the table and re uploded the modded DB 
It has been Three or Four runs till now and the Issue seems to be gone
```
Looking for Rogue DHCP Servers...
    One DHCP Server detected......: 192.168.178.1 (valid)
```
I have redownloaded the database and Inspected the table
It has populated now more rows (_31_) than before (_12_) with single IP entries,
I guess the cleanup did help...

**Comment by leiweibau** [comment]
Excellent. I will release this fix with the next update

**Comment by sgr78** [comment]
> Excellent. I will release this fix with the next update

Thank you, glad to be of help!
