### ISSUE TITLE
[Feature Request] Rename command buttons on Settings page from On/Off to Enable/Disable

### ISSUE THREAD

**Issue by csadam** [leiweibau/Pi.Alert#317]
The naming of the buttons is very ambiguous because it is not clear that they mean a status or an action.

For example there is the button `Main Scan (arp) Off`. It is not clear what does it mean.
Does it mean that it is currently Off, and I have to press the button to turn it On? Or is it On actually and the button turns it off?
Or on the GUI tab,  it says `Dark Mode On`. But it is not in dark mode, why is it On then?

By renaming these buttons to an action like `Disable Main Scan (arp)` or `Enable Dark Mode` would make much easier to understand what they actually do.

**Comment by leiweibau** [comment]
Valid point. I'll think about it.

**Comment by leiweibau** [comment]
I am closing this feature request because there is nothing else to test here. The change will be implemented with the next update
