### ISSUE TITLE
No Scan and Install error

### ISSUE THREAD

**Issue by nallej** [leiweibau/Pi.Alert#32]
Can only get the WAN nothing else.
It looks like on module is missing
I'm getting this error:  /pialert/back/pialert.py", line 30, in <module>  import requests
In the following logs: pialert.1 and pialert.IP and pialert_install

**Comment by nallej** [comment]
Looks like there is a typo in pialert-install.sh
line 398       sudo apt-get install python3 pip -y                             2>&1 >> "$LOG"
should be       sudo apt-get install python3-pip -y                             2>&1 >> "$LOG"

Did test by manuallu installing pip and requests. Got scanning to work.

Thanks for a great fork. I will cover it in my blog later this week.

**Comment by leiweibau** [comment]
thanks. I will take a look at the install script.
