### ISSUE TITLE
[Bug] Minor issue: Wrong alarm setting after adding new Webservice

### ISSUE THREAD

**Issue by upD8R** [leiweibau/Pi.Alert#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

If I add a new webservice and I tick in the initial dialogue to (only) report "Down" everything looks fine. But actually if you look to the new settings page of this webservice, it's exactly the opposite: "Down" is not ticked but all "events" are ticked.

### Environment

Debian Buster, native on Raspberry Pi 4

**Comment by leiweibau** [comment]
Thank you very much. Fix will be released with the next update.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/df78557cf6ea4b6519b7ceb363f7d2c9aad73acc
