### ISSUE TITLE
[Feature] Pi.Alert Satellites

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#322]
### What do I want to achieve with this feature?
My plan is to create a way to capture multiple, possibly separate, networks with one Pi.Alert installation. Examples here could be another residence or a network that you manage for friends or family.

### How should this feature be implemented?
I have created a companion script ([leiweibau/Pi.Alert-Satellite](https://github.com/leiweibau/Pi.Alert-Satellite)) based on Pi.Alert, which works without a GUI or database. This script must be installed on a dedicated system which is located in the respective network. The configuration parameters of the satellite are created via Pi.Alert and must be entered in the configuration of the satellite. The satellite can then either directly or indirectly (via a second web server) provide the encrypted scan results to the Pi.Alert installation, which processes them as part of its own scans.

### What already works?
The satellite already works in a basic way. The scans are executed and the scan results are sent directly to the Pi.Alert API, or indirectly (proxy mode) to a 2nd web server.
- implementation of the configuration in the UI
- Several new configuration parameters
- a separate API, which only receives the data in "proxy mode" or also performs decryption in normal mode.
- Creating the satellite configuration parameters in the Pi.Alert GUI
- Add new parameters to Config File Editor
- Add db connection to API in direct transfer mode (not required for proxy mode)
- Editing or deleting a satellite
- Include the operations performed to the journal
- Downloading and decrypting satellite data when using the proxy mode
- Installation script for the satellite. However, configuration steps are still required after installation
- Improved structure for the presentation of devices
- Extend bulk editor
- Processing of the satellite data
- ### Milestone reached 🎉
- Notification on "Inter-Satellite movement"
- Adapting the notifications
- Thanks to the Uranus moons Miranda, Juliet, Ophelia and Ariel for their support during the development 😉
- Documentation

What still needs to be done ?
- testing, testing, testing
- Documentation 

### Progress

| <img width="213" alt="navbar" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/261c3040-a853-48b7-bcdd-5a7f190a2c26"> | <img width="1192" alt="settings" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/68c2b05b-b8fa-48bb-b3ab-9cf58cdc746e"> |
| ------ | ------ | 
| <img width="1426" alt="satellite" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/d4d8f85c-d9c5-4703-914c-3bc1088e5a0d"> |  <img width="487" alt="Notifications" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/f7962fc7-7da4-473f-b3b5-28aab5b377e4"> |
| <img width="498" alt="satinfo" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/4972f1f5-6475-4ea9-aa68-74d049a4bbcb"> | <img width="625" alt="satellite_preconfig" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/5b25a783-4cb1-4995-b1e1-af65396861b0"> |

**Comment by leiweibau** [comment]
> is this new feature a script you run on a remote network that then reports back to your own network so you can manage that network also

That's the plan. All devices are written to the Devices table (means devices with MAC as primary identifier). But each satellite gets a view that only includes its own device list. As before, the top item "Geräte" (Devices) will include all locally detected devices. For this reason, you can see independent badges for "online" or "new" in the picture. Maybe I will make a view for "all" devices. The advantage of writing everything in the device table is that I can use the existing presence page.

I apologize that the screenshots are localized in German. The string translations always come at the end.

But I'm a bit scared for your question about the network page 😉. Theoretically, the page shouldn't care, but I haven't tried it yet. It's a lot of work to extend all the scripts, apart from the network page, so that everything looks and works properly.

**Comment by leiweibau** [comment]
> Question about how the satellites communicate, are you going to need a port open and they report to the main server?

No. The satellite makes an HTTP API call and sends an encrypted JSON as a payload via POST.

You can configure the satellite in 2 ways.
1. it calls the API directly from Pi.Alert (Proxy Mode = False)
2. it calls the API on an independent web server (Proxy Mode = True)

You can have a look here:
https://github.com/leiweibau/Pi.Alert-Satellite/blob/main/docs/PROXY_MODE.md

In Pi.Alert it works as follows:
In the 1st configuration, the scan results are already available, decrypted by the API, and can be processed.
In the 2nd configuration, the proxy mode must also be activated in Pi.Alert so that Pi.Alert calls the mentioned independent web server and loads the encrypted data. This is then decrypted and also processed.

While a satellite can only work in one mode, Pi.Alert can use both modes in parallel, i.e. one satellite can call the Pi.Alert API directly and another satellite can use the proxy mode.

**Comment by leiweibau** [comment]
Released with https://github.com/leiweibau/Pi.Alert/commit/6164a07b725c0f36e2165680f9a43d35a4b56052

**Comment by leiweibau** [comment]
‼️ The "predefined filter" function does not yet work for devices that are recognized by satellites.

**Comment by lastsamurai26** [comment]
I answer here 
I guess i found a translation issue 
![image](https://github.com/leiweibau/Pi.Alert/assets/3257844/d1e391cf-194b-4abd-84ed-6831405b11d5)

The red maked one should be lower case -> bereits not Bereits 

For me it works good, i need to use the proxy mode but it works, so i don't need to expose ports between pialert and satellite because the satellite is sending to proxy and pialert is downloading 👍

**Comment by leiweibau** [comment]
> It was a bit tricky to configure but it works

Is it the configuration as such that was a bit difficult, or did I forget something in the documentation?

**Comment by lastsamurai26** [comment]
I had some problems with my web server which didn't really want to work. 
It was also not clear which satellite.php I should use until I found the api folder inside of the pialert_satellite folder and then everything worked.

That was the only thing I had to find myself, but otherwise everything was great

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/bf1bf71aaad31459d3a5ee21e53152da960b314b
