### ISSUE TITLE
Presence is missing until device "down"

### ISSUE THREAD

**Issue by 4Arthur2** [leiweibau/Pi.Alert#323]
Hello,
for some time now, I can no longer see the presence of about 80% of the online devices. If I disconnect a device from the network and leave it disconnected until the next scan is running, the device is displayed with DOWN. Now I can see the presence bar.

You've an Idea ?
Best regards
Daniel

**Comment by leiweibau** [comment]
This is most likely due to the DAYS_TO_KEEP_EVENTS parameter in pialert.conf. It is set to 90 by default, but can also be set higher (currently 250 in my case).
Especially with devices that are permanently on, it can happen that the "session start" is older than 90 days and is then deleted.

**Comment by 4Arthur2** [comment]
Thanks for the answer,
Ok, but the Mobile Wifi devices (Smartphone, Notebooks Tablets ..... ) will disappear after 90/250 days and never again visible in "Presence" because the  "session start" is no more in the Database. Is it possible to set this after 90/250.
I like PI Alert very much and I will keep it longer than 250 Days :-)

Cu
Daniel

**Comment by leiweibau** [comment]
You can enter any value. If the database becomes too large or Pi.Alert becomes too slow, you must adjust the value again

**Comment by leiweibau** [comment]
The next update will address this behavior.
