### ISSUE TITLE
DB readonly 

### ISSUE THREAD

**Issue by alexpi4** [leiweibau/Pi.Alert#326]
database  readonly  message. how can I solve ?

**Comment by leiweibau** [comment]
Look at https://github.com/leiweibau/Pi.Alert/discussions/309

**Comment by alexpi4** [comment]
It simply happens when I try to change anything in an existing registration, for example the name or location.. anything I try to change and save looks like the message.

**Comment by alexpi4** [comment]
but with 160 items, it could be that the DB was still in use, I'll follow up. but thanks for the assistance! thakx

**Comment by leiweibau** [comment]
You can make your changes in Settings Pi.Alert for different periods of time without interruption and then restart Pi.Alert.
