### ISSUE TITLE
Cannot save the device after update 

### ISSUE THREAD

**Issue by taintran** [leiweibau/Pi.Alert#33]
After updating pi.alert by running this script
```
curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh | bash
```
now pi.alert cannot save the device setting

"Error updating device"
"UPDATE Devices SET ...... "
"attempt to write a readonly database"

I try these but it still not letting me update device info

```
python ~/pialert/back/pialert.py update_vendors


sudo apt-get install pip
python3 -m pip install requests
```

**Comment by leiweibau** [comment]
Hallo. I will check the updatescript later this day. On the Help/FAQ page of Pi.Alert you can find a possible solution for this problem.

[I get the message that the database is read only.]

Check in the Pi.Alert directory if the database folder (db) has been assigned the correct permissions:
drwxrwx--- 2 (your username) www-data
If the permission is not correct, you can set it again with the following commands in the terminal or the console:
sudo chgrp -R www-data ~/pialert/db
chmod -R 770 ~/pialert/db 
If the database is still read-only, try reinstalling or restoring a database backup from the maintenance page.

**Comment by taintran** [comment]
> I've changed the updatescript and add the commands from above, but i could not test it at the moment.

Thanks for updating the script. I re-run 
```
curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh | bash
```
and it is working now.

**Comment by leiweibau** [comment]
Thank you for reporting and your feedback

**Comment by taintran** [comment]
> Thank you for reporting and your feedback

Now the test notification doesn't work.
```
pi@raspberrypi:~ $ ~/pialert/back/pialert-cli reporting_test
bash: /home/pi/pialert/back/pialert-cli: Permission denied
```

**Comment by leiweibau** [comment]
can you please run the command
`ls -al ~/pialert/back/`

**Comment by taintran** [comment]
> can you please run the command `ls -al ~/pialert/back/`

pi@raspberrypi:~ $ ls -al ~/pialert/back/
total 184
drwxr-xr-x 3 pi pi  4096 Oct 26 09:44 .
drwxr-xr-x 9 pi pi  4096 Oct 22 13:38 ..
-rw-r--r-- 1 pi pi   176 Oct 22 13:38 ._pialert-cli
-rw-r--r-- 1 pi pi  8358 Oct 22 13:38 pialert-cli
-rw-r--r-- 1 pi pi   176 Oct 22 13:38 ._pialert.py
-rw-r--r-- 1 pi pi 68819 Oct 22 13:38 pialert.py
-rw-r--r-- 1 pi pi  4592 Oct 22 13:38 report_template.html
-rw-r--r-- 1 pi pi   176 Oct 22 13:38 ._report_template.txt
-rw-r--r-- 1 pi pi   424 Oct 22 13:38 report_template.txt
drwxr-xr-x 6 pi pi  4096 Oct 26 09:44 shoutrrr
-rw-r--r-- 1 pi pi 65334 Oct 22 13:38 speedtest-cli
-rw-r--r-- 1 pi pi  2126 Oct 22 13:38 update_vendors.sh
pi@raspberrypi:~ $

**Comment by leiweibau** [comment]
please run
`cd ~/pialert/back/`
`chmod +x pialert-cli`
`chmod +x pialert.py`
`chmod +x speedtest-cli`
`chmod +x update_vendors.sh`

**Comment by taintran** [comment]
> 

Yes, this works! Thanks.

**Comment by leiweibau** [comment]
I don't understand why you run in this problems. I update the script again. Thank you for reporting.
