### ISSUE TITLE
[Bug] WEBMON not triggering alerts

### ISSUE THREAD

**Issue by upD8R** [leiweibau/Pi.Alert#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

I'm using quite a bunch of endpoint for the web services monitoring, it works as expected in the UI, i.e. the outages or status changes are visible.

But for whatever reason I don't get an alert in Web UI or ntfy.sh. All services are set to alert "down" only. "Normal" alarms work.

### Environment

Raspberry Pi 4, native, running on Debian 11

### Anything else?

Here some values from the config:
```
# WebGUI Reporting
# ----------------------
REPORT_WEBGUI        = True
REPORT_WEBGUI_WEBMON = True

# NTFY
#---------------------------
REPORT_NTFY         = True
REPORT_NTFY_WEBMON  = True
```

**Comment by leiweibau** [comment]
I have just tested in my live environment and unfortunately I cannot reproduce the problem. A service that is only configured to "Down" triggers both a GUI and a pushover notification.

Is it possible for you to stop a service that is only configured to "Down" and is currently online and wait for the next scan? The web service scan is carried out every 10 minutes. When the scan is complete, can you run the following command in the console/terminal in the "pialert/db" directory?

```
sqlite3 pialert.db "SELECT Services_CurrentScan.*, Services.mon_tags
                    FROM Services_CurrentScan
                    JOIN Services ON Services_CurrentScan.cur_URL = Services.mon_URL
                    WHERE Services_CurrentScan.cur_AlertDown = 1 
                    AND Services_CurrentScan.cur_LatencyChanged = 1
                    ORDER BY Services_CurrentScan.cur_DateTime"
```

This command should show you the relevant "Down" service.

Are you using the latest version?

**Comment by upD8R** [comment]
I think it never worked. Anyway, I just tested it and the SELECT statement delivers an empty result.

**Comment by leiweibau** [comment]
Does the log file show any anomalies when a "down" service is reported?

```
Start Services Monitoring...
    Prepare Logfile...
    Get Services List...
    Flush previous scan results...
    Check Services...
    Services Monitoring Changes...
        Changed StatusCodes.....: 1
        Changed Reachability....: 1
```
But not that there is a misunderstanding here. "Down" means "unreachable", the request gets a timeout

**Comment by upD8R** [comment]
Ah, okay, that might be the issue then - down means here 502, as the actual service is not reachable but the reverse proxy is obviously still responding.

So I'm going to change the setup top report all events, let's see if this fixes my issue. Thanks!

**Comment by leiweibau** [comment]
However, you are not wrong with your expectation. 5xx is also unreachable. I'll give it some time to sink in and think about whether I'll add the 5xx code to the down notification.

**Comment by upD8R** [comment]
Works as you said, so it's fine for me now.
