### ISSUE TITLE
[Bug] Update error

### ISSUE THREAD

**Issue by A30BL** [leiweibau/Pi.Alert#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

My Pi.Alert runs on Proxmox 8.2.2 (LCX container). Today, I tried to update Pi.Alert from version 2024-06-12 to version 2024-07-04.
All scan were stopped. I started the update as root, but the update stopped with the message "Pi.Alert directory doesn't exists: /root/pialert".
The last update to version 2024-06-12 was without errors.

### Environment

Linux pialert 6.8.4-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (2024-05-02T11:55Z) x86_64 GNU/Linux

**Comment by leiweibau** [comment]
Which command did you use for the update?

**Comment by A30BL** [comment]
I created the directory /root/pialert and started the update again. Now it stops a little bit later.

`############################################################
 Pi.Alert Update
############################################################
Fri Jul  5 15:53:33 CEST 2024
Logfile: pialert_update_2024-07-05_15-53.log

- Checking Python...
Python 3 is installed on your system
mac-vendor-lookup is already installed
fritzconnection is already installed
routeros_api is already installed
pyunifi is already installed
- Stopping Pi.Alert...
environment: line 86: /root/pialert/back/pialert-cli: No such file or directory`

**Comment by A30BL** [comment]
> Which command did you use for the update?

Update command: 
bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)"

**Comment by leiweibau** [comment]
Did you use @tteck helper scripts for in installation? If yes, then the correct update command is: `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/pialert.sh)"` 
This should also have been included in the update notes.

In which directory was Pi.Alert installed?

**Comment by A30BL** [comment]
Thanks for the hint, the cli command "update" did the trick...
