### ISSUE TITLE
Possibility to block via iptables

### ISSUE THREAD

**Issue by ace16vitamine** [leiweibau/Pi.Alert#34]
Great Fork!

I am missing a possibility to block new IPs in the case that the IP is marked as new and pi alert is working as default router.

Currently, I am working with a short script and running via cron. Not optimal, but its working for me.

#Flush aller bestehenden Rules (nicht optimal aber läuft)
/usr/sbin/iptables -F

#Auslesen der NewDevices und schreiben in die die Datei newips
sqlite3 /home/pi/pialert/db/pialert.db  "select dev_LastIP from Devices where dev_NewDevice like 1;" > /home/pi/pialert/db/newips

#Schleife für jede Zeile (IP; $a)
cat /home/pi/pialert/db/newips | while read a

do

#Erstellen der IPTables Regeln (nicht optimal aber läuft)
#Alternativ: Ansprechen der FW API

/usr/sbin/iptables --append FORWARD --protocol tcp --src $a --jump REJECT
/usr/sbin/iptables --append FORWARD --protocol udp --src $a --jump REJECT
done

**Comment by leiweibau** [comment]
Super Idee. Ich gebe zu, mit iptables habe ich mich noch nie großartig beschäftigt. Ich habe jedoch schon bei meinen Erweiterung mitunter Bauchschmerzen gehabt, was der User www-data schon alles darf. Ihn noch in der Firewall rumschreiben lassen, wäre eine Grenze, die ich nicht überschreiten möchte. Ich habe auch schon die Idee fallen lassen, ein beliebiges Script nach dem Scan auszuführen, um zusätzliche Funktionen zu bieten.

**Comment by ace16vitamine** [comment]
So mache ich das aktuell ja auch. Nach dem Scan führe ich das Script aus. Jedoch besser währe kein iptables -F (alles löschen) sondern nur die löschen, die nicht mehr neu sind. Dazu müsste man bei Devices evtl. das Feld der_blocked erweitern. Wird ein Gerät als neu erkannt wird eine passende iptables Rule ausgeführt
