### ISSUE TITLE
update from web

### ISSUE THREAD

**Issue by javifly** [leiweibau/Pi.Alert#342]
hello, I have seen that a new update has been released a few days ago but it can not be applied from the control web, but it is applied with commands from linux. I have ADguard and the new version updates are done from the web with a single click, is not contemplated to add this system in pi alert?

**Comment by leiweibau** [comment]
Hello,

There have already been one or two questions about this. I understand that this would certainly be a significant gain in convenience, but I am not planning to implement this.

My reasoning here is as follows:
- the AdguardTeam consists of 25 members, I am alone 😉. It's not really an argument, just an observation 
- my update process is interactive to make it clear to the user that certain things are important. That would be difficult via a web update
- I also see an additional source of error here
- the user www-Data would need more rights to be able to install software (I already struggle with every entry in the sudoer files)

**Comment by javifly** [comment]
ok, I understand...
