### ISSUE TITLE
[Bug] Getting notifications even though the option is turned off.

### ISSUE THREAD

**Issue by DRIV3R78** [leiweibau/Pi.Alert#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

I selected all my devices (about 50) an deactivated the option "Alert Down".
All checkboxes are unchecked. Still getting down notification emails.

I activated and deactivated the checkboxes but the behaviour does not change

### Environment

Raspberry Pi 3 B+

**Comment by leiweibau** [comment]
> I selected all my devices (about 50) an deactivated the option "Alert Down".
All checkboxes are unchecked.

Are all (“Alert All Events” and “Alert Down”) or only “Alert Down” deactivated?
“Alert All Events” means all events. These would be IP changes, offline, online, changes between satellites and, depending on the modules used, also changes to the SSL certificate or HTTP status code changes.

When you open the Bulk Editor, you can see from the font color which notifications are activated for the individual hosts. If you don't want any notifications, they should all be white/black (depending on the theme).
https://github.com/leiweibau/Pi.Alert/blob/main/docs/BULKEDITOR.md

**Comment by DRIV3R78** [comment]
All checkboxes are unchecked. The devices are white in the bulk editor

![IMG_1332](https://github.com/user-attachments/assets/543c741a-4178-4d81-bcd7-e85a6aae19ff)

**Comment by leiweibau** [comment]
What you are showing me are the fields for editing. I mean the box at the top when you open the bulk editor

https://raw.githubusercontent.com/leiweibau/Pi.Alert/assets/bulkeditor_list.png

**Comment by DRIV3R78** [comment]
It is a fresh Raspberry Installation (64bit Bullseye) with your installation line
`bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh)"`

![Bulk](https://github.com/user-attachments/assets/54a07743-5c01-4369-aef2-5bb723f88045)

**Comment by leiweibau** [comment]
Is it a “Devices Down” or an “Events” notification? Does this only occur with a specific host, or with all hosts?

**Comment by DRIV3R78** [comment]
Hi,

I change nothing except the subnets to scan.
Maybe the issue is related to rights?

I have no issues except the message thing.

At first I forgot to use sudo with the installation command with I caught up on.

**Comment by leiweibau** [comment]
> Maybe the issue is related to rights?

No, I don't think so yet, otherwise the scan wouldn't even start. Apart from that, the database itself is checked for the correct permissions before the scan and set if necessary.

You can run the “Delete Events” function under “Settings” -> “Maintenance” and check whether the error disappears.

> At first I forgot to use sudo with the installation command with I caught up on

That should be less of a problem. If the command is executed with sudo, Pi.Alert is installed under the user root, otherwise under the current user. In either case, 2 files are created under “/etc/sudoers.d/”, which take care of the necessary permissions.

**Comment by DRIV3R78** [comment]
I deleted the events. Unfortunatly the problem persists.
Can I debug this?

**Comment by leiweibau** [comment]
> Can I debug this?

1. Does this only occur with a specific host, or with all hosts?
2. Check db file permissions
3. Check "Last Update" on the settings page (status box)
4. What does the “Scan” log look like (Settings page -> Log Viewer)?

**Comment by DRIV3R78** [comment]
1. it occurs with all hosts
2. How do ich check the db file permissions.
3. Last Update is 27.07. 16:15
4. `Pi.Alert v2024-07-17
---------------------------------------------------------
Executing user: root

Scan Devices
    Timestamp: 2024-07-27 16:15:00

Scanning...
    arp-scan Method...
    arp-scan: Multiple interfaces
    Pi-hole Method...
        ...Skipped
    DHCP Leases Method...
        ...Skipped
    Fritzbox Method...
        ...Skipped
    Mikrotik Method...
        ...Skipped
    UniFi Method...
        ...Skipped
    Satellite Import...
        ...Skipped

Processing scan results...
    Processing ignore list...
        Ignore list is empty
    Devices Detected.......: 58
        arp-scan Method....: 56
        Pi-hole Method.....: +0
        Fritzbox Method....: +0
        Mikrotik Method....: +0
        UniFi Method.......: +0
        New Devices........: 0

    Devices in this scan...: 58
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 3
        Disconnections.....: 1
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name........................`
5. Yes I think so :(

I will try to do a clean reinstall.
Somethinfg is broken. I deativated messages (False) but I still get notifications via mail.

**Comment by leiweibau** [comment]
As you can see in the log, no "Down Alert" is triggered here.

If you enter "crontab -e" (without "sudo") in the terminal, you can edit the user cronjobs. Just do a # before each pialert cronjob and check if the error disappears

**Comment by DRIV3R78** [comment]
I’ve done a clean install yesterday evening and the message problem disappeared.

Seems that it had to do with my second installation which I accidentally did.

You can close this issue.
Thanks for your help.

**Comment by leiweibau** [comment]
You're welcome
