### ISSUE TITLE
Installation outdated for Pi OS (bookworm)

### ISSUE THREAD

**Issue by ankonaskiff17** [leiweibau/Pi.Alert#348]
I was setting up Pi-Hole and in process of looking for blocklists found the original Pi.Alert along with your comment about being abandoned so came to your Github repo.
I'm not a programmer but I can figure out some things.
Since I already had Pi-Hole up and running I found what appeared to be an okay entry point to install Pi.Alert
Everything was going well until I got to the step for installing `mac-vendor-lookup` and `fritzconnection` and started getting messages about the packages were externally managed or along those lines. The "How to" page I link to below has a verbatim picture of the error I was getting when trying to install the above.

I have run into various Bookworm issues which this is another. To get those packages installed I had to create a virtual environment, which I did, and they were all able to be installed but this is where my lack of programming skills fail.
I used this web site [How to Install Python Packages in Raspberry Pi OS Bookworm](https://www.makeuseof.com/raspberry-pi-os-bookworm-install-python-packages) that got me able to install but again in a virtual environment which is something I've not dealt with.

I have stopped at step 5 as there is this comment at that site I linked to;
> Note that if you reboot the Raspberry Pi, you will need to reactivate the Python environment to use it again.

I don't really know what my next step should be and how to proceed because I'll certainly be rebooting the Pi or it will reboot itself when there is a hiccup on the grid and my power goes off momentarily.

As a side note which is also Bookworm related, there is now a network manager so making a static IP address is not readily done and the Pi-Hole folks need to revise their Pi-Hole instructions too.

**Comment by leiweibau** [comment]
The user running Pi.Alert should install the packages as follows (the installer actually does the same).

```
pip3 -q install mac-vendor-lookup --break-system-packages --no-warn-script-location
pip3 -q install fritzconnection --break-system-packages --no-warn-script-location
pip3 -q install routeros_api --break-system-packages --no-warn-script-location
pip3 -q install pyunifi --break-system-packages --no-warn-script-location
```

**Comment by ankonaskiff17** [comment]
Thank You. Enjoy vacation.

When you come back, how do you launch Pi.Alert?

**Comment by leiweibau** [comment]
> ...how do you launch Pi.Alert?

What do you mean by this question? The web GUI, or the scan?
The WebGui is most easily started via the IP or the host name (e.g. http://192.168.0.xx/pialert or http://hostname/pialert). The scan is executed every 5 minutes by a cronjob of the user who installed Pi.Alert. If you want to make a lot of changes to the detected devices at the beginning, I recommend pausing Pi.Alert in the settings so that the regular scans do not interfere with the processing of the device data.

If you want to use both Pi-hole and Pi.Alert on one host, I recommend installing both via my provided installation script. Otherwise, something may go wrong when configuring the web server if Pi-hole was already installed.

Translated with DeepL.com (free version)

**Comment by leiweibau** [comment]
Apart from the fact that I first had to add the user to the sudoer group, the installation script ran without errors on a vanilla Debian 12.6.

**Comment by ankonaskiff17** [comment]
Vanilla Debian is different than Raspberry Pi OS is the best way to describe the problem. PiOS made some pretty significant changes to the OS in Bookworm because it broke some other Pi based projects at the project/Github level, not at my level.Rather than checking on Debian, check it using Pi OS.My understanding being that there was enough difference between Debian and Pi OS they decided a name change was needed.https://www.tomshardware.com/news/raspberry-pi-os-no-longer-raspbianWayne Wells
-------- Original message --------From: leiweibau ***@***.***> Date: 8/3/24  4:29 AM  (GMT-05:00) To: "leiweibau/Pi.Alert" ***@***.***> Cc: wsquared58 ***@***.***>, Author ***@***.***> Subject: Re: [leiweibau/Pi.Alert] Installation outdated for Bookworm (Issue #348) 
Apart from the fact that I first had to add the user to the sudoer group, the installation script ran without errors on a vanilla Debian 12.6.

**Comment by leiweibau** [comment]
I will test it too

**Comment by leiweibau** [comment]
I just tested a vanilla Pi OS (bookworm) installation on a Raspberry Pi 3+ (`Linux pialert 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`). Apart from Perl warnings regarding the language settings used, the installation went through without errors. I will also test the combined installation with Pi-hole tomorrow.

Although there was a small error, it has nothing to do with this and there is also a fallback within the script. I'll take the opportunity to have a look at this as well.

**Comment by ankonaskiff17** [comment]
Reading through the reasoning, technical and otherwise as to why they went from calling the OS Raspian to Pi OS, is that it had to do with 64 bit vs 32 bit. All my Pi OS installs have been 64 bit since I stumbled on the fact that Pi 4’s (and earlier) were capable of using a 64 bit OS . What I will say is pretty much my standard method is to follow what the person who wrote the documentation says to do as far as install.  Sometimes that can be a guess as in this case Pi-Hole was already completely installed. So in that type of instance, I have to find what seems like a good entry point. I’m the first to admit I’m making an uneducated guess when I step into that type scenario.

Not being a programmer, I try to follow the authors README.md installation instructions.

 

I have plenty of free time. Would I be better off to do the install of Pi-Hole and Pi.Alert at the same time which I believe is how your README is written. I don’t mind doing that. If I did what was an unusual install it takes me about 30 seconds to format the SD card and start over. I don’t mind doing that if it is best. No need for you to chase an unusual circumstance.

Just for curiosities sake, where are you located? I’m in South Carolina, USA. The land of hillbillies and rednecks.

 




 

 

Wayne Wells

email: ***@***.***

Cell: (803) 553-6091

 

10682 Two Notch Rd.

Apt. 7107

Elgin, SC 29045

**Comment by leiweibau** [comment]
> Reading through the reasoning, technical and otherwise as to why they went from calling the OS Raspian to Pi OS, is that it had to do with 64 bit vs 32 bit

I have also only tested 64bit so far. Now also the combined installation with Pi-hole. There is no error here either. Only the following warning appears in between:
```
WARNING: Cannot open MAC/Vendor file ieee-oui.txt: Permission denied
WARNING: Cannot open MAC/Vendor file mac-vendor.txt: Permission denied
```
The reason for this will be dealt with later during the installation. At this point, I can only recommend that you simply restart the installation on a clean system.

> Just for curiosities sake, where are you located? I’m in South Carolina, USA. The land of hillbillies and rednecks.

I live in Germany. I'm sure there are just as various prejudices for us 😉 
I'm not familiar with the American social and cultural strata, so I can't and won't judge that. However, from the experience of our conversation so far, I cannot confirm your statement. 👍

**Comment by ankonaskiff17** [comment]
Okay.

I’ll just start over with a clean install following the instructions on your Github repo that has the user installing Pi-Hole and Pi.Alert as  a single process.

Thank you for the guidance.

 




 

 

Wayne Wells

email: ***@***.***

Cell: (803) 553-6091

 

10682 Two Notch Rd.

Apt. 7107

Elgin, SC 29045

**Comment by ankonaskiff17** [comment]
Can you refresh my memory as to how to call up your browser window.  I am following your Github instructions and hit an unexpected hardware problem. Nothing that is related to Pi.Alert though.  

 

Pi5 + Pi Official 7” Display problem

 




 

 

Wayne Wells

email: ***@***.***

Cell: (803) 553-6091

 

10682 Two Notch Rd.

Apt. 7107

Elgin, SC 29045

**Comment by leiweibau** [comment]
You mean the WebGUI?
https://github.com/leiweibau/Pi.Alert/blob/main/docs/FIRST_START_GUIDE.md

I just remembered... I haven't checked whether "/pialert" also works if you have specified during installation that the web interface should be made the default page of the web server.

**Comment by ankonaskiff17** [comment]
My intent before this Pi5 issue was to have both on a single Pi5 and 7” screen with default on boot to launch browser with 2 tabs I can toggle back and forth. One tab being the Pi-Hole stats page and second tab being your page.

 

I was not anticipating the Pi hardware causing problems. 

 




 

 

Wayne Wells

email: ***@***.***

Cell: (803) 553-6091

 

10682 Two Notch Rd.

Apt. 7107

Elgin, SC 29045

**Comment by leiweibau** [comment]
If you have solved the Pi 5 problem and installed both with the installation script, this should work 

You can access Pi-hole at http://localhost/admin
Pi.Alert can be reached at http://localhost/pialert

If you access the page from another host, then of course with IP, or hostname, instead of "localhost"

**Comment by ankonaskiff17** [comment]
I just posted a question to the Raspberry Pi official forum.  I  don’t think I will solve the Pi 5 issue myself. I found a post going back and forth between a Pi Software Engineer and an external Software Engineer about a bug  and it was way way way over my head but I found that post because it somewhat described my problem. I’m going to give my post a couple of days to see what and who responds.

 

While these problems are annoying the provide a good learning opportunity.

If nothing turns up I will start fresh with a Pi4 and the display as described with 2 tabs. Do you want me to send a message to you once I have everything up and running?

 




 

 

Wayne Wells

email: ***@***.***

Cell: (803) 553-6091

 

10682 Two Notch Rd.

Apt. 7107

Elgin, SC 29045

**Comment by leiweibau** [comment]
Yes, I would be happy to receive feedback if possible.

**Comment by ankonaskiff17** [comment]
I just got a Patreon email and have not read it yet but the subject
title probably spells it out well enough.
	I'll just drop the blog link but my question is have you done
anything to prepare or there is no conflict between a v6 Pi-Hole and
Pi.Alert.
	I am currently fighting an aggravating 3D printer problem so have
hit pause on doing a clean install of Pi-Hole and your application but I
think I have sorted out my Raspberry Pi 7" screen + Pi 5 NVME boot problems
and since the printer tech support is closed on weekends I was going to
start this project later today.
	Should I wait until after Pi-Hole pushes out v6?

 

	Wayne Wells
email: ***@***.***
Cell: (803) 553-6091

10682 Two Notch Rd.
Apt. 7107
Elgin, SC 29045

**Comment by ankonaskiff17** [comment]
Duh, forgot link
https://pi-hole.net/blog/2024/08/18/preparing-for-the-v6-release/

 

	Wayne Wells
email: ***@***.***
Cell: (803) 553-6091

10682 Two Notch Rd.
Apt. 7107
Elgin, SC 29045
	



_____________________________________________
From: ***@***.*** ***@***.***> 
Sent: Sunday, August 18, 2024 1:57 PM
To: 'leiweibau/Pi.Alert'
***@***.***>
Subject: Pi-Hole v6


	I just got a Patreon email and have not read it yet but the subject
title probably spells it out well enough.
	I'll just drop the blog link but my question is have you done
anything to prepare or there is no conflict between a v6 Pi-Hole and
Pi.Alert.
	I am currently fighting an aggravating 3D printer problem so have
hit pause on doing a clean install of Pi-Hole and your application but I
think I have sorted out my Raspberry Pi 7" screen + Pi 5 NVME boot problems
and since the printer tech support is closed on weekends I was going to
start this project later today.
	Should I wait until after Pi-Hole pushes out v6?

 

	Wayne Wells
email: ***@***.*** ***@***.***> 
Cell: (803) 553-6091

10682 Two Notch Rd.
Apt. 7107
Elgin, SC 29045

**Comment by leiweibau** [comment]
> anything to prepare or there is no conflict between a v6 Pi-Hole and Pi.Alert.

At the moment the situation is that Pi.Alert is not in conflict with Pi-hole 6, but the import of Pi-hole 6 data does not work. The background is that with version 6 the database is constantly blocked so that the data cannot be read. Version 6 now uses an API for this. When the final version 6 of Pi-hole is released, I will work on the support of the new version.

https://github.com/leiweibau/Pi.Alert/discussions/340

**Comment by ankonaskiff17** [comment]
So what I will do is install both as they stand now and then do it again later. 

 




 

 

Wayne Wells

email: ***@***.***

Cell: (803) 553-6091

 

10682 Two Notch Rd.

Apt. 7107

Elgin, SC 29045

**Comment by leiweibau** [comment]
If you now install both, you can update both applications independently of each other in the best case. A new installation of both programs should not actually be necessary. If you switch to v6 before my support, as far as I know you only have to change the PIHOLE_ACTIVE parameter to “False”.

I will test both the update and a new installation during development.

**Comment by leiweibau** [comment]
Update with beta support of Pi-hole 6 beta released with https://github.com/leiweibau/Pi.Alert/commit/cf37c8f9d7241b3ec4779a98ab9bda0a57d8dbcb

**Comment by leiweibau** [comment]
Closed due to inactivity on the original issue
