### ISSUE TITLE
Check for Updates without results

### ISSUE THREAD

**Issue by ace16vitamine** [leiweibau/Pi.Alert#35]
If I klick "Check for Updates" there are no results. After some time the Backup / Wiederherstellg. Page is shown.

**Comment by leiweibau** [comment]
Ich antworte mal auf deutsch, da du diese Sprache anscheinen selbst benutzt.

Der Update Check macht einen PHP curl Request an github. An dieser Stelle müsste sichergestellt sein, dass Pi-Alert Internetzugang hat. Ich habe gerade mal in das Installationsscript geschaut und feststellen müssen das ein php Paket nicht eingetragen ist. Führe mal folgendes aus.

`sudo apt-get install php-curl`

Dann sollte die Funktion gehen.
