### ISSUE TITLE
[Error]  Unable to delete unknown devices or update them

### ISSUE THREAD

**Issue by Alaponuke** [leiweibau/Pi.Alert#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

Hello, I have installed the system yesterday and is working pretty nice, except that some unknown devices can not be deleted or even update the information to archive them or change any properties.
I search about this, and I did not find anything related, sorry if I miss something.
The system is installed without pi-hole in a Linux mint xfce.
**Example or errors:**
![14-08-2024_11-02-32](https://github.com/user-attachments/assets/1faa65da-867b-4115-9fae-6981ca3dfccf)
![14-08-2024_11-03-34](https://github.com/user-attachments/assets/d47be1ea-85dd-4403-96c7-7278abcf41fa)

**Comment by leiweibau** [comment]
And you couldn't solve the problem with any of the information from these sources?

Pi.Alert WebGUI / "Help / FAQ" / "I get the message that the database is read only."

"DB readonly" https://github.com/leiweibau/Pi.Alert/issues/326

"Constant issues with locked database" https://github.com/leiweibau/Pi.Alert/discussions/309

"Can't edit devices" https://github.com/leiweibau/Pi.Alert/issues/153

You would have to give me a little more context and understand this error.
What system is Pi.Alert running on? Are the automatic backups activated that you can possibly fall back on? Does the scan itself work? What does the log file look like? Does the status box on the settings page show a recent date and time, or is the timestamp older than 5 minutes?

**Comment by Alaponuke** [comment]
Thanks for the fast reply I will check all you told me and come back, but the DB is not read only because I can delete not unknown devices, this happens only with unknowns devices, very strange.
_What system is Pi.Alert running on?_
the host of pi.alert is Linux mint xfce and pi.hole is not installed, only pi.alert

I will answers all other question when I get the information..
Regards

**Comment by stanelie** [comment]
Update : 
I manually ran the permission settings from https://github.com/leiweibau/Pi.Alert/blob/main/docs/INSTALL.md and I can now edit my devices without the error message.

Perhaps there is an issue with the one-liner install script compared to the manual install steps, or it has to do with the Bookworm version of Raspbian, which others are also having issues with : https://github.com/leiweibau/Pi.Alert/issues/348

**Comment by leiweibau** [comment]
Thanks for the effort. I will have a look at the relevant part of the installation.

**Comment by leiweibau** [comment]
@Alaponuke 
> the host of pi.alert is Linux mint

I have just installed a Linux Mint VM and found that, unfortunately, I cannot reproduce your problem, but I have been made aware of future sources of bugs with the help of this distribution. At this point, I would like to thank you again and point out how important it is to specify the platform.

**Comment by Alaponuke** [comment]
hello, coming back in my case I also installed with:
bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh)"

 and after applying the manual permissions , the problem goes away and now I can delete the unknown devices!!!

Thanks all of you for helping me on this problem!!

**Comment by leiweibau** [comment]
I'm glad you managed to do it. Unfortunately, I can't understand the problem at the moment. I will keep an eye on it.
