### ISSUE TITLE
[Feature Request] Exclude an IP-Range from the scan

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#357]
Hello.

Is there a way to exclude an ip range from the scan?
I'm asking because I connected pi.alert to my main Mikrotik router that is the DHCP server to 8 different subnets, and some of them I don't care about and I'd like to have them excluded from the scan results. However, since pi.alert is pulling the DHCP lease records straight from the router, I get a dump of every subnet.

I'm not sure if this already an option, but if it is, I was unable to find it.

Thanks!

**Comment by leiweibau** [comment]
This function was once available for test purposes. However, it was removed again because it was not useful for the problem that needed to be solved. 
https://github.com/leiweibau/Pi.Alert/issues/130

I will think about the idea again.

**Comment by stanelie** [comment]
Amazing! Thanks!

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/cf37c8f9d7241b3ec4779a98ab9bda0a57d8dbcb
