### ISSUE TITLE
Field "Letzte Sitzung" is not updated

### ISSUE THREAD

**Issue by ace16vitamine** [leiweibau/Pi.Alert#36]
The Field "Letzte Sitzung" Shows (sometimes) the initiated session - Not the session from the last scan. 

It is not possible to Filter for "Last seen"

**Comment by leiweibau** [comment]
Kannst du hier ein konkretes Beispiel anbringen? Ich kann dir gerade nicht folgen.

**Comment by ace16vitamine** [comment]
Ich mache nachher ein Screenshot. Das Feld "Letzte Sitzung" sollte normalerweise anzeigen, wann der Client zuletzt gesehen wurde. Bei mir werden aber nur alte Daten angezeigt, wann der Client das erste mal gesehen wurde.

**Comment by leiweibau** [comment]
Wenn die 1. Sitzung noch nie unterbrochen wurde, dann zeigt er auch bei mir in "Letzte Sitzung" den Zeitstempel des Startes der 1. Sitzung an (falls du das meintest). Da die 1. Sitzung ja noch nie beendet wurde, kann er nicht anzeigen, wann die letzte Sitzung war, da sie noch läuft. Das habe ich noch nie angefasst bzw. darüber nachgedacht.
