### ISSUE TITLE
[Feature Request] Set default alert mode for newly added devices

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#360]
Hello.

Right now, when a new device is discovered, the "Alert All Events" checkbox is checked by default. I would rather this was not the case. I would like to be alerted just once when the device is first added to the network, and then not get further notifications for this device unless I manually check the "Alert All Events" checkbox.

Thanks!

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/b500f0e35a684b6872de91b2781a666541ac1931
