### ISSUE TITLE
[Feature Request] display mac addresses in the Devices view

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#361]
Hello.

I would like the ability to display mac addresses in the Devices view. Even better, the ability to customize the Devices view columns items.

This is low priority, but I think it would be nice to have.

Thanks!

**Comment by leiweibau** [comment]
You mean like this?

<img width="1130" alt="Bildschirmfoto 2024-08-21 um 21 20 26" src="https://github.com/user-attachments/assets/bae9b5a4-3e6c-4dad-b249-86fb4e278089">

**Comment by leiweibau** [comment]
https://github.com/leiweibau/Pi.Alert/blob/main/docs/guide/002.md#section-3-
