### ISSUE TITLE
[Feature Request] allow concurrent write operations to the database

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#362]
Hello.

95% of the time, when I try to update a device, I get the error message "attempt to write a readonly database". I have to stop the scanning, wait for it to die (this often takes several minutes because it does not necessarily stop), and then only I can make my update. I have some very dynamic networks with hundreds of devices needing editing often, and this is a pain.

Would there be a way to make it so concurrent writes to the database are allowed, so arpscan and me can edit it at the same time?

Thanks!

**Comment by leiweibau** [comment]
The whole thing is not quite trivial, as sqlite is a single-user database. I have built such a function for the journal, but I have to admit that I don't really intend to do the same for the device list.
But that doesn't mean that I can't understand your need.

**Comment by stanelie** [comment]
Is there a reason for arp-scan to be locking the database for so long? Couldn't it write to the database in chunks and leave the database unlocked the rest of the time, allowing the end user to do stuff?

Or is switching to some other multi-user database an option?

**Comment by leiweibau** [comment]
I already use the WAL mode. But if the database says it doesn't want to, then it doesn't want to. The WAL mode does not change the fact that it is a single user DB.

>  It does however lock the whole database when writing, so if you have lots of concurrent writes it is not the database you want

**Comment by stanelie** [comment]
In the StackOverflow article I mentioned, the last comment at the bottom talks about Berkeley DB being compatible with SQlite and multi-user.

Have you had a chance to look at it? I find this intriguing.

**Comment by leiweibau** [comment]
This is ChatGPT's answer to my question about what changes are necessary to a Python script if I want to switch from sqliteDB to Berkeley DB.

> 8 Missing functionalities in Berkeley DB
Since Berkeley DB does not provide an SQL interface, you will need to replace any SQL logic in your code, which can lead to significant changes for more complex queries. You may need to change the structure of your code and data accesses to accommodate this.

> Summary
Migrating from SQLite to Berkeley DB will require significant changes to your Python script, particularly in terms of data access, manipulation and management. Berkeley DB is a simple key/value database, while SQLite is a relational SQL database, which requires different mindsets and programming paradigms.

To make a long story short, I will not change the database myself, but I am open to pull requests

**Comment by stanelie** [comment]
It looks like Berkeley DB implements the sqlite API with a wrapper, so, it might be less work then it would appear : 
https://stackoverflow.com/questions/38629454/how-to-replace-sqlite-with-berkeley-db

Thanks again for having a look, and thanks for pi.alert!

**Comment by leiweibau** [comment]
I have scrolled through a few more documents from Oracle.

A database switch will not take place for the time being.

**Comment by stanelie** [comment]
Thanks for entertaining the idea.

**Comment by stanelie** [comment]
Sorry to be hammering on this issue, but it is really inconvenient for me.

I was monitoring the pialert.1.log file live with " tail -f pialert.1.log", and I saw the "Done!!!" message. Looking at the code, this "Done!!!" message immediately follows a "closeDB()" 7 lines earlier. So, the way I understand it, when the log file reaches this "Done!!!" message, the database should be closed. However, I am still getting the error message "attempt to write a readonly database" at this point when I try to update a device details.

Could the error message be wrong and something else is preventing me from updating the devices records?

**Comment by leiweibau** [comment]
Allow me to ask a few questions so that I can better understand the problem from my side?

- How large is the network? What subnet mask are we talking about?
- Are satellites in use, or is everything scanned by a Pi.Alert instance?
- Have the cronjobs been changed? (Scan every 5 minutes, Internet check every 3 minutes)
- Are Pi.Alert's own cronjobs in use (speed test)?
- How often are edits carried out via the web interface?
- Does the error also occur when all scans are stopped (then there might be a permissions problem)?

**Comment by stanelie** [comment]
- I currently have about 150 devices connected to the one subnet (/23 network) I am currently monitoring, but I would like to be able to monitor all 8 subnets of this building
- I am not using a "satellite" (I do not know what they are and what their purpose is)
- I have not modified the cronjobs
- I am not using the speedtest feature
- Every time a new device connects, and it is not something I want to monitor (a guest connecting to the guest network, I new computer that is not a server or something I want to monitor), I need to disable the "alert for all events" of that device, at least, and untick the "New" flag. Several times per hour. If I don't do it, I get a spammy notification every time the user exits the building for lunch or other event
- The error does not happen when I stop the scan and wait for several minutes after stopping the scan. Each edit necessitates 2-6 minutes every time.

**Comment by leiweibau** [comment]
> I currently have about 150 devices connected to the one subnet (/23 network) I am currently monitoring, but I would like to be able to monitor all 8 subnets of this building

So will more subnets of this size be added?

> I am not using a "satellite" (I do not know what they are and what their purpose is)

It*s a companion script for Pi.Alert, which executes the Pi.Alert scan on an external host and sends the data as encrypted [JSON](https://github.com/leiweibau/Pi.Alert-Satellite/blob/main/docs/JSON_DEMO.md) to a special API. This would at least parallelize the scan across the subnets and thus shorten the scan time. https://github.com/leiweibau/Pi.Alert-Satellite.

> I have not modified the cronjobs

Fine

> Every time a new device connects, and it is not something I want to monitor (a guest connecting to the guest network, a new computer that is not a server of mine or something I don't want to monitor), I need to at least disable the "alert for all events" of that device, and untick the "New" flag. Several times per hour. If I don't do it, I get a spammy notification every time the user exits the building for lunch or other event

This at least gives me more context to the other feature request. I'm thinking about the best way to implement this.

> The error does not happen when I stop the scan and wait for several minutes

So you can rule out a permissions error

**Comment by stanelie** [comment]
The other subnets are not as big, but one of them will be very variable as it is the guests network (we are a theater venue).

Thanks!
