### ISSUE TITLE
[Feature Request] "presence" checkbox

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#363]
It would be nice to have a "Use this device for presence" tick box in the detailed view of the devices, so that when you click on the "presence" button in the left menu, you get only those devices.

I come from Fingbox, and it used to have this feature before Fing paywalled it. It was a very nice feature and I would love to get it back with Pi.Alert.

Thanks.

**Comment by leiweibau** [comment]
That sounds interesting. I'll give it some thought.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/cf37c8f9d7241b3ec4779a98ab9bda0a57d8dbcb
