### ISSUE TITLE
[Feature Request] https support FrontEnd website management 

### ISSUE THREAD

**Issue by Alaponuke** [leiweibau/Pi.Alert#364]
Hi, maybe I am wrong, but I did not find any reference to use https instead http on the frontend of the Pi.alert.
Is this possible to do it right now, or can be possible in the future?

Kind Regards,

**Comment by leiweibau** [comment]
I'm not planning to work on it here. SSL is such a complex topic that I don't want to take on.

What problems do I see here?
- I can only offer selfsigned certs to which every browser reacts differently, at least it feels that way. So in case of doubt, I have to provide support for the different browsers.
- When Pi-hole 6 is released, it will also run on port 443 and problems could arise. Another service may already be provided on 443 on the system.
- I may have to provide support if someone wants to integrate their own certs
- and probably many more things that I can't think of right now

If there is a need, you can find a link for the integration of SSL in lighttpd below.

https://redmine.lighttpd.net/projects/1/wiki/HowToSimpleSSL

**Comment by Alaponuke** [comment]
ok understood is not an easy topic, anyway thanks so much for this great tool!!!
