### ISSUE TITLE
[Feature Request] Possibility to purge Devices "not connected since X Days"

### ISSUE THREAD

**Issue by ace16vitamine** [leiweibau/Pi.Alert#37]
An option to start "mass purge" for all Devices (not seen since X Days) is missing. X means a variable timeframe (Date Field)

**Comment by leiweibau** [comment]
Die Idee ist nicht schlecht. Ich denke mal darüber nach. Vermutlich würde ich aber einen festen Zeitraum (vielleicht 14 Tage oder 1 Monat) festlegen, da das Errorhandling bei fehlerhafter Eingabe dann wegfällt. Mal schauen ...

**Comment by ace16vitamine** [comment]
Kann man auch. Aber ich musste letztens "aufräumen" und das hat sehr lange gedauert...
