### ISSUE TITLE
Missing Temp in the latest version

### ISSUE THREAD

**Issue by lastsamurai26** [leiweibau/Pi.Alert#371]
after the update to the latest version the temp is missing 
![image](https://github.com/user-attachments/assets/568cb0e3-7f74-4806-b17b-3106b337ece8)
![image](https://github.com/user-attachments/assets/786b7f2b-43ed-41b2-ab7c-4bb7c475e5f2)

On the same host i have pihole and there is the temp
What can i check for you?

**Comment by leiweibau** [comment]
Have you tried clearing the cache?

**Comment by lastsamurai26** [comment]
Nice try -.- 
Sometimes i'am Stupid :-D 
Works

**Comment by leiweibau** [comment]
All good. I had this effect myself during development because I worked on both css and JavaScript
