### ISSUE TITLE
[Error] Cannot update using one-liner command. Error: stepping, attempt to write a readonly database (8)

### ISSUE THREAD

**Issue by AnsonCNS** [leiweibau/Pi.Alert#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

Hi there,

I'm getting the following error when trying to update PiAlert using the one-liner command ```bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)"```. I have already disabled scans as suggested by #356.

```
############################################################
 Pi.Alert Update
############################################################
Sun 25 Aug 20:32:19 AEST 2024
Logfile: pialert_update_2024-08-25_20-32.log

- Checking Python...
Python 3 is installed on your system
mac-vendor-lookup is already installed
fritzconnection is already installed
routeros_api is already installed
pyunifi is already installed
- Stopping Pi.Alert...
No timeout is set. Pi.Alert restarts itself with the next scan after 10min.
arp-scan: no process found
/home/rpi4/pialert/back/pialert-cli: line 217: /home/rpi4/pialert/back/../config/setting_stoppialert: Permission denied

Pi.Alert v2024-08-09
---------------------------------------------------------
Executing user: rpi4


Test Reporting...
    Sending report by email...
    Skip PUSHSAFER...
    Skip PUSHOVER...
    Skip Telegram...
    Skip NTFY...
    Save report to file...

DONE!!!


Configured Pi.Alert scans are disabled
Error: stepping, attempt to write a readonly database (8)
```

### Environment

Raspberry Pi 4

**Comment by leiweibau** [comment]
You can do the following:

```
sudo rm /home/rpi4/pialert/config/setting_stoppialert
cd /home/rpi4/pialert/back/
./pialert-cli disable_scan
sudo killall arp-scan
```

Wait a few seconds. In the case that ICMP monitoring or web service monitoring is active, you should check the status box (settings page) of Pi.Alert to see if the scan is still active. If no scan is active here, run the updater again.

```
bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)"
```

**Comment by AnsonCNS** [comment]
Thanks for the quick reply.

I followed your instructions and the readonly error went away when running the update command.

However, it showed some errors about cannot clean up previous version. (sorry I was unable to screenshot the error message)

I then tried to rerun the update command, but I get the following error. 

```
Sun 25 Aug 22:03:07 AEST 2024
Logfile: pialert_update_2024-08-25_22-03.log

- Checking Python...
Python 3 is installed on your system
mac-vendor-lookup is already installed
fritzconnection is already installed
routeros_api is already installed
pyunifi is already installed
- Stopping Pi.Alert...
environment: line 86: /home/rpi4/pialert/back/pialert-cli: No such file or directory
```

The ```back``` directory is now gone and I cannot access the PiAlert page (it gives a 403 Forbidden error)

**Comment by leiweibau** [comment]
The installation is now corrupted.
Without knowing about the errors, I advise you to take the following steps.

- save the database in the directory “/home/rpi4/pialert/db” to another directory outside of pialert e.g. “/home/rpi4/saved_db/”
- rename the directory “/home/rpi4/pialert” or delete it
- start the installer, not the updater
- After the installation, change to the directory “/home/rpi4/pialert/back/”

```
cd /home/rpi4/pialert/back/
./pialert-cli disable_scan 30
```
- delete the database that is delivered with the installation
```
rm /home/rpi4/pialert/db/pialert.db
rm /home/rpi4/pialert/db/pialert.db-shm
rm /home/rpi4/pialert/db/pialert.db-wal
```
- copy the backed up database back to pialert
```
cp /home/rpi4/saved_db/pialert.db /home/rpi4/pialert/db/pialert.db
```
- reset the permissions
```
cd /home/rpi4/pialert/back/
./pialert-cli set_permissions
```
- update the database (this is necessary for the current update)
```
cd /home/rpi4/pialert/back/
./pialert-cli update_db
```
- Start Pi.Alert
```
cd /home/rpi4/pialert/back/
./pialert-cli enable_scan
```

**Comment by AnsonCNS** [comment]
That worked. Thanks heaps!
