### ISSUE TITLE
[Bug] Presence counter tag always shows total device count instead of Presence enabled device count

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#374]
It looks like the Presence counter tag always shows the total device count instead of Presence enabled device count.

**Comment by leiweibau** [comment]
> It looks like the Presence counter tag always shows the total device count instead of Presence enabled device count.

Yes, as it should be. https://github.com/leiweibau/Pi.Alert/commit/26d868b9867fea38e9a8345adf411aef4530a8c0
I may create a separate view of how many devices are hidden later.
