### ISSUE TITLE
[Feature Request] view the vendor field as a column in the Devices view

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#376]
In the "Configure device overview" of the web gui, it is impossible to select the "vendor" field as a column of the web gui devices view. This would be helpful to sort and/or filter similar devices or vendor specific devices.

Thanks!

**Comment by stanelie** [comment]
Also, the ability to create a filter based on the Vendor field would be very nice too.

**Comment by leiweibau** [comment]
A star for the project, as a small recognition for the implemented feature request or the time I took to answer the questions, would also be nice 😉

This is not meant to be begging, but it's the little things that motivate a maintainer to put their free time into a project.

**Comment by stanelie** [comment]
Done! :)

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/b500f0e35a684b6872de91b2781a666541ac1931
