### ISSUE TITLE
Multiple VLANs and DHCP Servers

### ISSUE THREAD

**Issue by ace16vitamine** [leiweibau/Pi.Alert#38]
We have different VLANs. I each of them a Pi-Hole is placed.

It would be nice to merge the DHCP Leases from Pi-Hole and the possibility to work with multiple VLANs and Network ranges, maybe a Pi-Alert Satellite is a great Idea.

**Comment by leiweibau** [comment]
Pi.Alert already merge DHCP Leases, but only from a Pi-hole that runs on the same system. If I understand you correctly, you need the possibility to query the leases from an external DHCP. I don't think that will be possible so easily. I would have to find a way to read the leases from the external server. Maybe a regular query via ssh would be used, which I personally don't like.

On the subject of VLAN / Subnet, take a look at this commit https://github.com/jokob-sk/Pi.Alert/commit/929ea98fcef7d8b8af81181d97a8f9dff16665fe. It's from another fork, but it should work for me as well. Personally, I have not installed this function for me, because incorrect entries in the config file can completely collapse Pi.Alert.

**Comment by ace16vitamine** [comment]
Ich meine das etwas anders.

Angenommen ich habe mehrere DHCP Server mit Pi-Hole im Einsatz mit unterschiedlichen Netzen.

Alternative: Einen Scan Satelliten mit Pi-Alert, der nichts anderes macht als die Scan Informationen an den Master zu übertragen.

**Comment by leiweibau** [comment]
Die Idee gab es ja schon mal im "Haupt"-Pi.Alert. Damals dachte ich mir: "Ist bestimmt leicht bis mittelschwer zu bauen." Mittlerweile sehe ich das etwas anders. 
Die Hauptschwierigkeit liegt in der Datenbank. Wäre es ein separater Datenbankserver, wäre das alles sicher deutlich einfacher. Mit sqlite3 haben wir aber eine lokale Datenbank, die von einem lokalen Benutzer bearbeitet wird. Man müsste also entweder eine deutlich komplexere (viele Datenfelder) API bauen, die auch schreiben kann, oder die Satelliten müssten sich an dem zentralen Pi.Alert z.B. via SSH einloggen und die DB bearbeiten. Dies dürften dann aber nicht mehrere gleichzeitig machen, da die DB sonst kaputtgehen kann.

**Comment by ace16vitamine** [comment]
Die Satelliten könnten auch einfach nur einen Scan machen und mittels HTTP ein Update an den Master senden.

1.2.3.4 Offline Datum Uhrzeit

Der Master müsste dann nur diese Daten aus diesem Aufruf in die Datenbank schreiben oder aktualisieren

**Comment by leiweibau** [comment]
Es sind ja nicht nur die Daten als solche (Mac, aktuelle IP von dieser Mac, Zeitstempel). Dies zu übermittel und in die Datenbank zu schreiben ist leicht. Das Problem ist das weitere Verarbeiten der Daten. Man muss durch den gesamten Stack durch.

Gab es das Gerät schon?
War das Gerät vorher schon online?
Hatte es vorher eine andere IP?
Ist es Archiviert oder nicht?
Solle alles gemeldet werden oder nicht?
Ist es eine zufällige Mac oder nicht?
Ist ein Gerät jetzt nicht mehr da, welches vorher da war?
In der Datenbank muss dies als "Sitzung beendet" gespeichert werden?
Muss ein Alarm für ein nicht gefundenes Gerät ausgelöst werden?
etc

Dazu kommen neue Probleme, wenn ein Gerät von einem Satelliten zu einem andere wechselt.

Das Tool (arp-scan) welches hinter Pi.Alert steht, macht nichts weiter, als eine arp Request an das Netzwerk zu schicken und sich die Antworten zu merken. Es findet im Prinzip nur aktive Geräte mit ihrer IP. Schon die Feststellung, dass ein Gerät "offline" ist, ist Teil der Datenbank und Python Magie. So einen Satelliten zu bauen, ist also nicht trivial. Trotz allen finde ich die Idee gut, sehe mich aber leider nicht in der Lage sie umzusetzen.

**Comment by leiweibau** [comment]
So, mein lieber @ace16vitamine 😉
Da kannst du mal sehen, wie lange ich mir Gedanken darüber gemacht habe. Ich weiß zwar nicht, ob du noch meinen Fork, oder überhaupt noch Pi.Alert oder vielleicht auch NetAlertX verwendest. Aber in den letzten Wochen habe ich im Prinzip deine Idee umgesetzt.

Also, Ja, das Umsetzen deiner Idee war möglich, aber ich hatte trotzdem Recht: Es ist ein Schmerz 😉
Wenn es dich interessiert, Hier geht es zum "Issue" https://github.com/leiweibau/Pi.Alert/issues/322 und hier zum Satelliten https://github.com/leiweibau/Pi.Alert-Satellite

<hr>

So, my dear @ace16vitamine 😉
You can see how long I've been thinking about this. I don't know if you're still using my fork, or even Pi.Alert or maybe NetAlertX. But in the last few weeks I have basically implemented your idea.

So, yes, implementing your idea was possible, but I was still right: it's a pain 😉
If you're interested, click here for the "Issue" https://github.com/leiweibau/Pi.Alert/issues/322 and here for the satellite https://github.com/leiweibau/Pi.Alert-Satellite
