### ISSUE TITLE
IP resolves but pihole.local does not

### ISSUE THREAD

**Issue by fuzzievohs** [leiweibau/Pi.Alert#381]
https://10.69.x.x/admin/ works fine but
https://pihole.local/admin/ gives this:
Failed Host Check: pihole.local vs 10.69.X.X, devices, pi.hole, localhost

Googled to try to figure it out, nadda.

https://pihole.local/pialert works fine.
Any suggestions?

**Comment by leiweibau** [comment]
No idea, sorry.
