### ISSUE TITLE
Pi-hole V6 beta support

### ISSUE THREAD

**Issue by JYewdall** [leiweibau/Pi.Alert#382]
My Pi.Alert can only access /etc/pihole/dhcp.leases if, after every reboot, I `sudo chmod 664 /etc/pihole/dhcp.leases`

I need help with my pi.alert config

My Pi.Alert config contains:
# Pi-hole Configuration
# ----------------------
PIHOLE_ACTIVE              = True
PIHOLE_VERSION             = 6
PIHOLE_DB                  = '/etc/pihole/pihole-FTL.db'
PIHOLE6_URL                = 'http://pi.hole:8080/api'
PIHOLE6_PASSWORD           = '********'
DHCP_ACTIVE                = True
DHCP_LEASES                = '/etc/pihole/dhcp.leases'

I assume the pihole6 password is pihole's web password
The pihole6 URL is a guess.

My pi.alert log shows:
File "/home/pi/pialert/back/pialert.py", line 946, in copy_pihole_network
    if not PIHOLE6_PASSWORD or not PIHOLE6_URL:
                                 ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'PIHOLE6_URL' where it is not associated with a value

**Comment by leiweibau** [comment]
http(s)://<IP_ADDPRESS_OF_YOUR_PI_HOLE>/admin/
http(s)://pi.hole/admin (when using Pi-hole as your DNS server)

**Comment by JYewdall** [comment]
Sorry, Same error when I changed PIHOLE6_URL

**Comment by leiweibau** [comment]
> Sorry, Same error when I changed PIHOLE6_URL

My example did not include a port. Did you include it? Can you call up the web interface under the URL that you entered as the value?

**Comment by JYewdall** [comment]
yes, port included. To confirm I copied the URL from the config into a browser and get my pi-hole web interface.

**Comment by leiweibau** [comment]
I can confirm that you have not made an incorrect entry 😉

**Comment by lastsamurai26** [comment]
@JYewdall 
do you have Lighttpd running as a reverse proxy for Pihole if so how did you manage that ?

**Comment by lastsamurai26** [comment]
I know that, that's why the webserver of Pihole is now running on 8080 but you can use lighttpd as reverse so that you can only call http(s)://domain instead of http(s)://domain:8080

I had managed it but due to an update the whole thing no longer works and I am looking for a solution but I can't switch from lighttpd to apache either

**Comment by leiweibau** [comment]
I will publish a release in the next few days, which will take care of the support of Pi-hole 6 beta. I would still like to test the update script a little, as changes were also necessary here in the case of another report.

The support of Pi-hole 6 beta is still beta on my side as well.

**Comment by JYewdall** [comment]
I still have to `sudo chmod 664 /etc/pihole/dhcp.leases` after a pihole update and after every reboot to avoid permission errors on  /etc/pihole/dhcp.leases. Now that pihole V6 support appears to be working can you obtain the DHCP lease information through the API.

**Comment by leiweibau** [comment]
To be honest, I hadn't even thought about the DHCP leases, although I use them myself with v5. The Pi-hole 6 API at least provides for querying them. I'll post the link to the API here so that I don't have to keep looking for it.

https://ftl.pi-hole.net/development-v6/docs/#get-/dhcp/leases

As the basic work has already been done, implementation should now be faster.

**Comment by leiweibau** [comment]
If you want to test reading the DHCP information and possibly give feedback, you can download the script and copy it into the “pialert/back/” directory. However, do not delete the original file, just rename it. You may have to adjust the permissions of the new file.

https://raw.githubusercontent.com/leiweibau/Pi.Alert/refs/heads/next_update/back/pialert.py

**Comment by JYewdall** [comment]
No errors here after replacing pialert.py

Pi.Alert v2024-09-17
---------------------------------------------------------
```
Executing user: pi

Scan Devices
    Timestamp: 2024-09-20 16:05:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole 6 Client List Method...
Auth required
    Pi-hole 6 DHCP Leases Method...
Auth required
    Fritzbox Method...
        ...Skipped
    Mikrotik Method...
        ...Skipped
    UniFi Method...
        ...Skipped
    Satellite Import...
        ...Skipped

Processing scan results...
    Processing ignore list...
        MAC-Ignore list is empty
        IP-Ignore list is empty
    Devices Detected.......: 13
        arp-scan Method....: 11
        Pi-hole Method.....: +0
        Fritzbox Method....: +0
        Mikrotik Method....: +0
        UniFi Method.......: +0
        New Devices........: 0

    Devices in this scan...: 13
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 1
        Disconnections.....: 1
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...
        Names updated: 0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...
    Calculate Activity History...

Reporting...
    Formating report...
    No changes to report...
    Notifications: 0

DONE!!!

```

**Comment by leiweibau** [comment]
"Auth required" Means that the script could not log on to the API.

I had to adjust the URL variable. Can you please check your configuration again according to the instructions?
https://github.com/leiweibau/Pi.Alert/blob/main/docs/PIALERT_CONF.md#pi-hole-configuration

**Comment by JYewdall** [comment]
I am at a loss here.
My config with password redacted:
# Pi-hole Configuration
# ----------------------
PIHOLE_ACTIVE              = True
PIHOLE_VERSION             = 6
PIHOLE_DB                  = '/etc/pihole/pihole-FTL.db'
PIHOLE6_URL                = 'http://192.168.0.72:8080/'
PIHOLE6_PASSWORD           = '*****'
DHCP_ACTIVE                = True
DHCP_LEASES                = '/etc/pihole/dhcp.leases'

Using a different browser I can confirm that my pihole web password is correct. With  and without the trailing / in the URL makes no difference. 
Note - changing the password in the config and then closing the config saves the change without the banner notice that the config has been saved.

**Comment by leiweibau** [comment]
The URL seems to be correct.

Pi-hole is most likely installed on the same hardware as Pi.Alert. Can you test "http://localhost:8080/"  ?

In my test environment, Pi-hole is a separate instance, as my productive system is still v5. I will do another test on the same machine.

**Comment by JYewdall** [comment]
no change. I still see [Auth required ](url)twice when I use http://localhost:8080/

**Comment by leiweibau** [comment]
If you like and are not afraid, you can open the pialert.py file in an editor and navigate to this line

https://github.com/leiweibau/Pi.Alert/blob/c09108109f3cafb2efbfbb394b7166c4da45a6ab/back/pialert.py#L994

Insert the line “print(response_json)” below it so that it looks like this (the spaces are important)

```
    response_json = response.json()
    print(response_json)
```

With the next scan, the response of the API should be output

**Comment by JYewdall** [comment]
Before I do that I have installed pialert on another pi running pihole. I initially set the config to point across at the first pihole seeing the same Auth required.  I have now configured it to point at its own pihole and I will see what happens

**Comment by leiweibau** [comment]
Good to read. 
I have just finished a test setup and am now also testing. Please excuse all the back and forth, but with only one network it is difficult to test the many different configurations and then also different software versions

**Comment by JYewdall** [comment]
On what I think is the working pialert I see:
`{'session': {'valid': True, 'totp': False, 'sid': 'TOYJ629Iwq26n2dSWeykvw=', 'csrf': '5bQAX9seFjqIaz7v2WLjug=', 'validity': 604800, 'message': 'password correct'}, 'took': 0.5810847282409668}`
 
On the failing first pialert I see:
`{'error': {'key': 'api_seats_exceeded', 'message': 'API seats exceeded', 'hint': 'increase webserver.api.max_sessions'}, 'took': 0.4008824825286865}`

Now working after I deleted 16 sessions!
The sessions take the form of:

2024-09-20 19:30:13 | 2024-09-27 19:30:14 | ::1 | python-requests/2.28.1

They are added to every 5 minutes! Pi.Alert?
The setting for webserver.session.timeout on both my Pis was 604800 (7 days!) and was not set by me. The default is 1800.
1800 seconds gives Pi.Alert time to access 6 times before sessions are closed if that is what webserver.session.timeout does.

**Comment by leiweibau** [comment]
Very interesting.
If you don't mind me asking? Where did you delete the sessions? Pi-Hole v6 or in a directory?

**Comment by JYewdall** [comment]
I deleted them in the web settings for API in expert mode.
I  still may have a problem because the first session from pi.alert is still showing in the list 3 minutes after I thought it would have expired.

**Comment by leiweibau** [comment]
I have just had another look at the Pi-hole API documentation. I will try to have Pi.Alert terminate the session after the operation

**Comment by JYewdall** [comment]
It is I who should be thanking you for all your hard work. It is all looking good here.

**Comment by leiweibau** [comment]
> but I now never see an entry in the list of active sessions. Is it that fast.

Yes, I had to insert a delay in the script to take the screenshot.

**Comment by JYewdall** [comment]
2024-9-28 update
looking good until:
```
Scanning...
    arp-scan Method...
        ...Skipped
    Pi-hole 6 Client List Method...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3816, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/pialert/back/pialert.py", line 100, in main
    res = scan_network()
          ^^^^^^^^^^^^^^
  File "/home/pi/pialert/back/pialert.py", line 746, in scan_network
    copy_pihole_network()
  File "/home/pi/pialert/back/pialert.py", line 937, in copy_pihole_network
    copy_pihole_network_six()
  File "/home/pi/pialert/back/pialert.py", line 1057, in copy_pihole_network_six
    interfaces = get_pihole_interface_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pialert/back/pialert.py", line 1121, in get_pihole_interface_da                            ta
    ips = [addr['address'] for addr in interface['addresses'] if addr['family']                             == 'inet']
                                       ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'addresses'

------------------------------------------------------------
 Update process finished
------------------------------------------------------------
```

**Comment by JYewdall** [comment]
pialert.1.log now contains:
```
Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole 6 Client List Method...
Traceback (most recent call last):
File "/home/pi/pialert/back/pialert.py", line 3816, in
    sys.exit(main())    
             ^^^^^^
File "/home/pi/pialert/back/pialert.py", line 100, in main
    res = scan_network()
         ^^^^^^^^^^^^^^
File "/home/pi/pialert/back/pialert.py", line 746, in scan_network
    copy_pihole_network()
File "/home/pi/pialert/back/pialert.py", line 937, in copy_pihole_network
    copy_pihole_network_six()
File "/home/pi/pialert/back/pialert.py", line 1057, in copy_pihole_network_six
    interfaces = get_pihole_interface_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/pialert/back/pialert.py", line 1121, in get_pihole_interface_data
    ips = [addr['address'] for addr in interface['addresses'] if addr['family'] == 'inet']
                                     ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'addresses'
```

**Comment by leiweibau** [comment]
First the explanation of the function.
The network list also contains pi-hole itself. However, pi-hole itself does not perform any DNS queries via itself. In order to recognize from the network list whether a device is online, it checks when the last DNS request was made. The function is used to read the interface list from Pi-Alert and compare it with the known IPs in the network list. If there is a match, the timestamp of the last request is modified so that Pi-Hole itself is recognized as “online”. I only use IPv4 addresses for the IPs.

About your error:
At first glance, the error suggests that the script does not find any IPv4 addresses in pi-hole's interface list.

https://github.com/leiweibau/Pi.Alert/blob/97cfeb451b638f1f1a513617d7f119519731e3c3/back/pialert.py#L1113

Could you possibly insert a “print(data)” under this line?

Unfortunately, I can't reproduce the error in my case

**Comment by JYewdall** [comment]
Done

```
Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole 6 Client List Method...
{'interfaces': [{'name': 'lo', 'speed': None, 'type': 'loopback', 'flags': ['up', 'loopback', 'running', 'lower_up'], 'state': 'unknown', 'carrier': True, 'proto_down': False, 'address': '00:00:00:00:00:00', 'broadcast': '00:00:00:00:00:00', 'stats': {'rx_bytes': {'value': 33.202172, 'unit': 'M'}, 'tx_bytes': {'value': 33.202172, 'unit': 'M'}, 'bits': 64}, 'addresses': [{'family': 'inet', 'scope': 'host', 'flags': ['permanent'], 'prefixlen': 8, 'address': '127.0.0.1', 'address_type': 'loopback', 'local': '127.0.0.1', 'local_type': 'loopback', 'label': 'lo', 'prefered': 4294967295, 'valid': 4294967295, 'cstamp': 1727266534.86, 'tstamp': 1727266534.86}, {'family': 'inet6', 'scope': 'host', 'flags': ['permanent'], 'prefixlen': 128, 'address': '::1', 'address_type': 'loopback', 'prefered': 4294967295, 'valid': 4294967295, 'cstamp': 1727266534.86, 'tstamp': 1727266534.86}]}, {'name': 'eth0', 'speed': 1000, 'type': 'ether', 'flags': ['up', 'broadcast', 'running', 'multicast', 'lower_up'], 'state': 'up', 'carrier': True, 'proto_down': False, 'address': 'dc:a6:32:5a:26:54', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'perm_address': 'dc:a6:32:5a:26:54', 'stats': {'rx_bytes': {'value': 398.442033, 'unit': 'M'}, 'tx_bytes': {'value': 214.469204, 'unit': 'M'}, 'bits': 64}, 'addresses': [{'family': 'inet', 'scope': 'universe', 'flags': ['permanent'], 'prefixlen': 24, 'address': '192.168.0.72', 'address_type': 'private', 'local': '192.168.0.72', 'local_type': 'private', 'broadcast': '192.168.0.255', 'broadcast_type': 'private', 'label': 'eth0', 'prefered': 4294967295, 'valid': 4294967295, 'cstamp': 1727266546.74, 'tstamp': 1727266546.74}, {'family': 'inet6', 'scope': 'universe', 'flags': [], 'prefixlen': 64, 'address': '2001:**REDACTED**', 'address_type': 'global (GUA)', 'prefered': 16, 'valid': 26, 'cstamp': 1727496041.23, 'tstamp': 1727555409.13}, {'family': 'inet6', 'scope': 'link', 'flags': ['permanent'], 'prefixlen': 64, 'address': 'fe80::13bf:27ae:21b9:b1db', 'address_type': 'link-local (LL)', 'prefered': 4294967295, 'valid': 4294967295, 'cstamp': 1727266546.74, 'tstamp': 1727266546.74}]}, {'name': 'wlan0', 'speed': None, 'type': 'ether', 'flags': ['up', 'broadcast', 'multicast'], 'state': 'down', 'carrier': False, 'proto_down': False, 'address': 'dc:a6:32:5a:26:55', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'perm_address': 'dc:a6:32:5a:26:55', 'stats': {'rx_bytes': {'value': 0, 'unit': ''}, 'tx_bytes': {'value': 0, 'unit': ''}, 'bits': 64}}], 'took': 0.00060272216796875}
Traceback (most recent call last):
File "/home/pi/pialert/back/pialert.py", line 3817, in
    sys.exit(main())    
             ^^^^^^
File "/home/pi/pialert/back/pialert.py", line 100, in main
    res = scan_network()
         ^^^^^^^^^^^^^^
File "/home/pi/pialert/back/pialert.py", line 746, in scan_network
    copy_pihole_network()
File "/home/pi/pialert/back/pialert.py", line 937, in copy_pihole_network
    copy_pihole_network_six()
File "/home/pi/pialert/back/pialert.py", line 1057, in copy_pihole_network_six
    interfaces = get_pihole_interface_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/pialert/back/pialert.py", line 1122, in get_pihole_interface_data
    ips = [addr['address'] for addr in interface['addresses'] if addr['family'] == 'inet']
                                     ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'addresses'
```

**Comment by leiweibau** [comment]
In this “fixed” script the error is intercepted, but it is not yet clear to me why the error occurs

https://raw.githubusercontent.com/leiweibau/Pi.Alert/b03b9497ed9e72337db960c80dad5c24e1980807/back/pialert.py

Addendum:
Ah, thank you.
This key is missing for the WLAN interface. This is probably why the script stumbled

**Comment by JYewdall** [comment]
Looks good.
```
Pi.Alert v2024-09-28
---------------------------------------------------------
Executing user: pi

Scan Devices
    Timestamp: 2024-09-28 21:55:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole 6 Client List Method...
    Pi-hole 6 DHCP Leases Method...
    Fritzbox Method... Skipped
    Mikrotik Method... Skipped
    UniFi Method... Skipped
    Satellite Import... Skipped

Processing scan results...
    Processing ignore list...
        MAC-Ignore list is empty
        IP-Ignore list is empty
    Devices Detected.......: 14
        arp-scan Method....: 12
        Pi-hole Method.....: +1
        Fritzbox Method....: +0
        Mikrotik Method....: +0
        UniFi Method.......: +0
        New Devices........: 0

    Devices in this scan...: 14
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 10
        Disconnections.....: 0
        IP Changes.........: 1

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...
        Names updated: 0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...
    Calculate Activity History...

Reporting...
    Formating report...
    Skip mail...
    Skip PUSHSAFER...
    Skip PUSHOVER...
    Skip Telegram...
    Skip NTFY...
    Save report to file...
    Notifications: 0

DONE!!!



```

**Comment by leiweibau** [comment]
It was once again a pleasure to be able to solve the problem quickly and efficiently with you.

**Comment by JYewdall** [comment]
The 10 additions were because I had previously disabled arp-scans. Is there a way of seeing which device changed it's IP address. In my case it could indicate one of my two DHCP servers had not responded or gone offline  for a period.

**Comment by leiweibau** [comment]
There is no nice overview for such a query. The only possibility would be the “Events” overview. You can then enter “Change” in the search field and you will get a list of all detected changes to the IPs.

**Comment by leiweibau** [comment]
The support now seems to be running so far, or has been little used so far, at least the lack of feedback on possible problems suggests so. 😉 I would close the issue for now.
