### ISSUE TITLE
[Bug] Sorting IP column is broken

### ISSUE THREAD

**Issue by JoatmonX** [leiweibau/Pi.Alert#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

Sorting by IP seems to be broken.

**Comment by leiweibau** [comment]
I can't look right now, but you could be right, as this could well be related to the expansion of the list due to a feature request.

**Comment by JYewdall** [comment]
It is the same here.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/afa775a1e4a14e13a1d772627af3e35f022e0461

**Comment by JYewdall** [comment]
Initially the update reported:
```
Error: stepping, attempt to write a readonly database (8)
Failed to write to the journal, but continuing.
```
The first scan with PIHOLE_ACTIVE  = False and  PIHOLE_VERSION  = 6 showed only 2 devices online.
After resetting the permissions on the database ( have you missed off `sudo` in front of `chmod -R 775 ~/pialert/db` in the FAQ) and set PIHOLE_ACTIVE = True,  the next scan ran error free and my expected 14 devises showed as online.
