### ISSUE TITLE
Create HTTP Request to external API

### ISSUE THREAD

**Issue by ace16vitamine** [leiweibau/Pi.Alert#39]
An Option to access external APIs would be great.

Example: Pi Alert is detecting a new device: the Qualysguard Vulns Scanner can be triggered with a HTTP Curl request to scan the new device

**Comment by leiweibau** [comment]
This is an interesting but difficult idea. Each API has its syntax. And the returned data can have different formats. Again, you would have to start testing with a few defined APIs at the beginning. I don't know of any useful service (selfhosted) that could be included.

**Comment by leiweibau** [comment]
I just had a look at the API documentation from Qualys. The documentation is over 800 pages long. I am a hobby developer. As interesting as this idea is, I can't invest time here.

**Comment by ace16vitamine** [comment]
Es geht eigentlich darum, einen HTTP Request auszulösen (eine URL aufzurufen) bei einem neuen Device. Nicht nur Qualys, irgendeine URL
