### ISSUE TITLE
[Bug] Last 3 days, web interface crashes

### ISSUE THREAD

**Issue by fuzzievohs** [leiweibau/Pi.Alert#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

For the last three days (at least) my Pi Alert web interface has crashed.  I get a 500 error when trying to access the web interface.  I can't ssh in to the box.  The only fix is to hard reset the pi.  I don't know where to look to see what's causing the issue.
Thanks for any suggestions.

### Environment

Debian GNU/Linux 12 (bookworm)
Native
RPi 3b+ 
LAN

**Comment by leiweibau** [comment]
If you have the possibility, you can connect a monitor in the event of an error and run “sudo top” locally on the Raspberry Pi to check which process is currently using a lot of resources. Your SD card may also be damaged. Have you made changes to the cronjob to change the scan interval?

**Comment by fuzzievohs** [comment]
I'll try that...didn't happen again.
No SD card.  I run the pi with an SSD.
I have made no changes to the cronjob.

**Comment by fuzzievohs** [comment]
You can close this, it has not happened since.  Probably just the interweb squirrels.
