### ISSUE TITLE
[Feature Request] API - Add Down Devices

### ISSUE THREAD

**Issue by fobi87** [leiweibau/Pi.Alert#391]
Hi.

Can you add the Number of "Down Devices" to the PiAlert API?

thx

**Comment by leiweibau** [comment]
This should be easy to implement. So why not?

**Comment by leiweibau** [comment]
However, there is one thing ;-)
“Down” devices are also ‘offline’ devices at the same time. I will not subtract the down devices from the offline devices so that the total number of devices is correct. “Down” devices are therefore counted twice.

**Comment by leiweibau** [comment]
Contrary to the more convenient way, I now subtract the “down” devices from the offline devices. However, only “Down” devices that are NOT “Archived” are counted via the API.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/76cb6c06225071df6cbfedd682cf7bf5ee1040fc

**Comment by fobi87** [comment]
thx 👌
