### ISSUE TITLE
Display of the system time

### ISSUE THREAD

**Issue by Falconcrest** [leiweibau/Pi.Alert#399]
Hi,

I have a question about the local time in the top right corner. 
Why is GMT displayed there and not the system time, which in my case is correctly set to GMT+2? 
Can this be adjusted?

Thanks

**Comment by leiweibau** [comment]
The 1st entry on the Help/FAQ page deals with this topic and describes possible solutions.

**Comment by leiweibau** [comment]
But since you are not the first with this question and certainly not the last, I will extend the code so that you can set the time zone in the configuration file. This will hopefully save me the constant references to the help/FAQ.

**Comment by Falconcrest** [comment]
Oops, sorry, I didn't look it up there...
Nevertheless, your update would be appreciated. 
Not to open a new thread, does pi.alert also run on an Rpi5?

**Comment by leiweibau** [comment]
> Oops, sorry, I didn't look it up there...

All good. Apparently very few people do that 😉

> does pi.alert also run on an Rpi5

Should work. For testing purposes, I am running it on a Raspberry Pi 3, an Intel NUC and on various VMs with different Debian-based operating systems

**Comment by Falconcrest** [comment]
As I read it, they use an RPi3, among other things... For me it always crashes after about 1 1/2 days, i.e. it goes offline and I can no longer access it via ssh... 
Well, maybe it is also defective, hence the question about the Rpi5. I will install pi.alert once on a Rpi5 8GB with DietPi and PCIe NVMe SSD. 
Thanks for the great support!

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/4317ae53a4af619ce48b14248c85733684539201
