### ISSUE TITLE
[Bug]  Unable to locate package python3-tzlocal-y

### ISSUE THREAD

**Issue by johnny-tknoska** [leiweibau/Pi.Alert#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

I just do a fresh install and got this error and installation process stopped:

:~ $ bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh)"

############################################################
 Pi.Alert Installation
############################################################
Sun 20 Oct 19:53:58 CEST 2024
Logfile: pialert_install_2024-10-20_19-53.log
- Installing dependencies...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cron is already the newest version (3.0pl1-162).
whiptail is already the newest version (0.52.23-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

------------------------------------------------------------
 Pi-hole
------------------------------------------------------------

------------------------------------------------------------
 Lighttpd & PHP
------------------------------------------------------------
- Installing apt-utils...
- Installing lighttpd...
- Installing PHP...
- Activating PHP...
- Restarting lighttpd...
- Installing sqlite3...
- Installing mmdblookup

------------------------------------------------------------
 arp-scan, dnsutils and nmap
------------------------------------------------------------
- Installing arp-scan...
- Testing arp-scan...
WARNING: Cannot open MAC/Vendor file ieee-oui.txt: Permission denied
WARNING: Cannot open MAC/Vendor file mac-vendor.txt: Permission denied

- Installing dnsutils & net-tools...
- Installation of tools for hostname detection...
- Installing nmap, zip, aria2 and wakeonlan

------------------------------------------------------------
 Python
------------------------------------------------------------
- Checking Python 2...
  - Python 2 is installed
    - Python 3.11.2

- Checking Python 3...
  - Python 3 is installed
    - Python 3.11.2

- Using the available Python version installed
  - Python 3 is available

- Using Python 3
E: Unable to locate package python3-tzlocal-y
:~ $

**Comment by leiweibau** [comment]
Thanks

... fixed

**Comment by johnny-tknoska** [comment]
Thanks! Works fine now! A missing blank I guess ;-)

**Comment by leiweibau** [comment]
yes ;-)
