### ISSUE TITLE
[Bug] can't start an update

### ISSUE THREAD

**Issue by myssv** [leiweibau/Pi.Alert#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

it is allways saying this
![grafik](https://github.com/user-attachments/assets/c80f9594-3746-444e-b47f-2639cdabce86)

### Environment

**OS**: Debian 12 on ProxMox

**Comment by leiweibau** [comment]
Release Notes

> Changed:
> * The update script does not perform an update as long as a scan is running. To do this, it checks for the existence of the ".scanning" file, which is created for the duration of a scan.

Otherwise, everything is in the box. After a short time, press Enter again. When the scan is finished, the update starts, otherwise the message is repeated

I will add "Press enter to retry" later

**Comment by myssv** [comment]
Sorry, forgot to mention that I'm trying since 5 hours ....

a already stopped all services

![grafik](https://github.com/user-attachments/assets/4ef9b2bd-4e8b-421c-a2b4-1e1c36a540e3)

But still got the message

**Comment by myssv** [comment]
even deactivating Pi.Alert doesn't help

![grafik](https://github.com/user-attachments/assets/079f443e-6cdd-40d3-9f29-f6b4b09b94f3)

**Comment by leiweibau** [comment]
Ich schreib mal deutsch 😉
Mit den Kacheln oben, schaltest du nur die Module aus. Die ganzen Importe werden trotzdem gemacht. Wenn du jetzt erst den Timer gesetzt hast, kann es sein, dass vielleicht noch ein Scan läuft. Probiere es jetzt einfach noch mal

**Comment by myssv** [comment]
Sehr gerne :-)

wie gesagt, ich probiere es seit ca. 10:00h immer wieder. Er will einfach nicht. Auch jetzt habe ich es 5 Minuten lang probiert bevor ich auf "Comment" klicke.

**Comment by leiweibau** [comment]
Ich teste hier auch gerade noch einmal eine zusätzliche Maschine. Verwendest du root, oder einen "normalen" User

**Comment by myssv** [comment]
ich nutze root

**Comment by leiweibau** [comment]
Setze den Pause Timer mal auf 30min. Da haben wir etwas Zeit. Wenn der Timer gesetzt ist, kannst du dann mal bitte in der Konsole im Verzeichnis "/root/pialert/back/" schauen, ob es dort eine Datei ".scanning" gibt und welches Datum diese Datei hat?

**Comment by myssv** [comment]
Ist es normal, dass der Timer immer wieder verschwindet?

![grafik](https://github.com/user-attachments/assets/8a582fc5-28db-4158-a262-6c8cea57dc69)

**Comment by leiweibau** [comment]
mach mal "ls -al"

**Comment by myssv** [comment]
ich starte vorher immer das Update, damit Du sehen kannst, dass es wirklich nicht löuft

![grafik](https://github.com/user-attachments/assets/bd3eb796-9177-45fc-8691-bdbb7d339ee1)

**Comment by myssv** [comment]
![grafik](https://github.com/user-attachments/assets/6985e02f-e3ed-4102-9905-8ba685235dcf)

Möchtest Du Remote hier rauf?

**Comment by leiweibau** [comment]
> Möchtest Du Remote hier rauf?

Danke, aber AUF KEINEN FALL

Es existiert keine Datei "setting_stoppialert", der Timer ist also nicht gesetzt.

Ich kann dir jetzt spontan 2 Möglichkeiten anbieten:

Möglichkeit A:
1. gehe ins Verzeichnis "/root/pialert/config"
2. `echo 30 > setting_stoppialert`
3. prüfe im Verzeichnis "/root/pialert/back", wann die Datei ".scanning" verschwindet und startet das Update.

Ich habe es eben gerade auch unter "root" getestet und es hat funktioniert

Möglichkeit B (Ich würde A bevorzugen):
1. lösche im Verzeichnis "/root/pialert/back" die Datei ".scanning"
2. Starte das Update

Während des Updates wird noch einmal versucht, laufende Scans zu beenden, das aber auf eine etwas radikalere Art.

**Comment by myssv** [comment]
Ich habe es jetzt extra noch einmal gesetzt:

![grafik](https://github.com/user-attachments/assets/a9cc0816-a315-4a27-9f02-22318e05b7b0)

nach einiger Zeit verschwindet der Eintrag wieder

![grafik](https://github.com/user-attachments/assets/fff5f9b4-8594-4e57-9219-f6974f655337)

Die Datei ist immer noch nicht da

![grafik](https://github.com/user-attachments/assets/74259427-a728-4a90-90fb-e13c262e9150)

Habe sie jetzt manuell erstellt:

![grafik](https://github.com/user-attachments/assets/ad0732f1-351e-4c4b-ba07-a349b752d8c1)

Warte, dass die .scanning datei verschwindet

![grafik](https://github.com/user-attachments/assets/69fb7442-3f76-4e7c-9269-91375eeac61e)

Sie hat einen neuen Zeitstempel, aber war nicht weg ...

![grafik](https://github.com/user-attachments/assets/4e85d134-90d5-4196-afbc-a02630265bef)

**Comment by myssv** [comment]
STOP, mein Fehler. Habe die Datei falsch erstellt

**Comment by leiweibau** [comment]
Probiere mal diess aktualisierte Script. Es beseitigt nicht das konkrete Problem. Ist aber vielleicht besser handzuhaben

bash -c "$(wget -qLO - https://raw.githubusercontent.com/leiweibau/Pi.Alert/refs/heads/next_update/install/pialert_update.sh)"

**Comment by myssv** [comment]
kleine Kosmetik :-)

![grafik](https://github.com/user-attachments/assets/8cc3f60a-420e-44d4-a467-0566768dcf82)

aber läuft

![grafik](https://github.com/user-attachments/assets/0f0def1f-1195-419d-8f81-3f857971af7b)

**Comment by leiweibau** [comment]
Ja, die Kosmetik ist schon erledigt. Github hat es nur noch nicht komplett verarbeitet. Ich werd den Text in der Box noch etwas anpassen. Der Hinweis auf die Help/FAQ Seite, fällt mit diesem Update eh weg

**Comment by myssv** [comment]
Ist das noch nötig?

![grafik](https://github.com/user-attachments/assets/7676baa7-458e-4a92-b789-65f166540428)

**Comment by myssv** [comment]
ok, dann schon mal vielen Dank!

**Comment by myssv** [comment]
Da bin ich jetzt überfordert:

![grafik](https://github.com/user-attachments/assets/a2ca678e-91e1-4d37-b0f1-98def57fbab9)

**Comment by myssv** [comment]
Wo kommt die Adresse her?

Unable to get a connection: HTTPConnectionPool(host='192.168.172.1', port=49000)

**Comment by myssv** [comment]
ja, mein Fehler. Sorry!

**Comment by leiweibau** [comment]
Funktioniert nun alles, oder gibts noch Fehler, auf die Ich reagieren muss?

**Comment by myssv** [comment]
ok, Danke!

Mir ist gerade was aufgefallen:

![grafik](https://github.com/user-attachments/assets/b822e6e9-bd01-42bc-b39c-1df3201eba34)

Wenn ich auf "Meldungen anzeigen" gehe, wird ein großer freier Platz angezeigt:

![grafik](https://github.com/user-attachments/assets/a21b8afc-c7f5-4749-b196-ae6763d56e05)

**Comment by myssv** [comment]
Aber das ist ein neuer Punkt und hat mit diesem nichts zu tun.

Vielen Dank für Deine Hilfe!

**Comment by leiweibau** [comment]
mach mal "./pialert-cli set_permissions" im Verzeichnnis "/root/pialert/back"

**Comment by myssv** [comment]
root@PiAlert:~/pialert/back# ./pialert-cli set_permissions
Pi.Alert Group: www-data
    Set DB Group Permissions only
    Set Config Group Permissions only
    Set Back Group Permissions only
    Set Reports Permissions
Group Permissions set

**Comment by leiweibau** [comment]
Ich hatte deine Anfrage zum Datenbankupdate übersehen.

Ja, das ist noch notwendig

**Comment by myssv** [comment]
Das ist mir schon klar, aber muss die Abfrage noch sein? Es sind ja eigentlich keine Scans aktiv, wenn das Update startet.

**Comment by leiweibau** [comment]
Im Prinzip hast du recht. Das Datenbankupdate wird von der "pialert-cli" durchgeführt, die man auch unabhängig vom Update ausführen kann, z.B. wenn man ein Datenbank aus einem Backup aktualisieren möchte. Deshalb gibt es noch einmal einen Warndialog.

**Comment by leiweibau** [comment]
Closed. With an improvement to the update script, the scenario can now be bypassed if necessary.
