### ISSUE TITLE
[Bug] Log-out not possible

### ISSUE THREAD

**Issue by FairTradeOrange** [leiweibau/Pi.Alert#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

At first, sorry for my english, i hope everything is understandable, plz just ask if not, this is my first "Bug Issue".

**It is not possible to log out after enable "Login" in the settings and set a password.**

I discovered yesterday the project, i have a PiHole installed for years and so i was interested and installed this project via the "One-step Automated Install" on a Raspberry Pi 4. 
I tried rebooting the system and enabling/disabling Login but nothing changes.

I also think that there is something missing in the logout panel (Image below)?

After the installation i had some dmesg logs filled with "device eth0 entered/left promiscuous mode" every minutes. But a reboot fixed that.
Everything else seems correct. 

Thank you for your time and continuing the project!

### Environment

Linux Raspberry Pi 4 Model B Rev 1.2 - 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

### Anything else?

![grafik](https://github.com/user-attachments/assets/57f71d32-98cc-4d8b-8f6b-1c1c28125731)

**Comment by leiweibau** [comment]
Hello,

Thanks for the report.
Your impression that something is wrong with the display in the menu is correct. The Fontawesome icons are not displayed. These are included in the “package” and should not actually be blocked in any way. Which browser are you using? Do you have any experience with the browser's “developer tools”?
Which URL do you call up for the web interface?

> At first, sorry for my english, I hope everything is understandable,

I can also offer you German as an alternative language.

**Comment by FairTradeOrange** [comment]
I use Firefox 133.0b3 (64-Bit) (aurora). 

I use the URL:
 http://<IP>/pialert/devices.php 

At first i tried the deprecated image (https://github.com/pucherot/Pi.Alert/) but uninstalled it and tried this instead. 
Which i think is really great. ( :
Maybe because of that there are some problems?
I have a little bit experiences with the dev console, saving something into localstorage or sessionstorage or call js, 
should i do something specific?

Just for information, i also used another browser for testing, it seems the "Enable Login" configuration does not work, there is no login panel at all.

I also thought the button is broken, but when i use the button a normal request is send:

GET /pialert/index.php?action=logout HTTP/1.1
Host: <IP>
Accept-Language: de-DE,de;q=0.9
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.71 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://<IP>/pialert/devices.php
Accept-Encoding: gzip, deflate, br
Cookie: PHPSESSID=53mc7bhvqh9jnh0dl4ulm4ntga; devicesList=[3,8,22,10,7,2,13,4,1,6,5,9,19,11,12,14,15,16,17,18,20,21]
Connection: keep-alive

------------------------------------------------------------------------------------------------------------------------------------


Ok, i searched a bit and will now add the errors from the lighttpd log ( var/log/lighttpd),
i will uninstall everything again and will install it clearly.

![grafik](https://github.com/user-attachments/assets/01444b97-06c1-4fe1-b231-27d8a5689f65)

![grafik](https://github.com/user-attachments/assets/121c7509-e180-4b5a-bd60-f5ba6fd9cd66)



I think i made some faults and it's not your application.
