### ISSUE TITLE
Q: Is it possible to add this to an exising PiHole

### ISSUE THREAD

**Issue by Ingalara** [leiweibau/Pi.Alert#41]
This looks like an awesome project! Just wanted to check if I could run the install script on an existing PiHole running on a RPI3 without losing my current config (DNS, DHCP etc). Or is there a better way to do this?

**Comment by leiweibau** [comment]
It is always good to make a backup. If this is done, nothing can happen. Basically it is possible to add "Pi.Alert" to an existing "Pi-Hole" installation. I myself also use it in parallel with a "Pi-Hole" installation.
