### ISSUE TITLE
[Bug] Pi.Alert stopped working after recent update 2024-10-20

### ISSUE THREAD

**Issue by Vorteth** [leiweibau/Pi.Alert#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

Not entirely sure what happened but on the 20th of October I updated pi.alert like normal and everything 'seemed' to work. I checked and no scans or backups have taken place since that time. I confirmed after 2024-10-20 there were no events.

I found if I forced a scan it worked as expected, same code that I used to run the command was inside the crontab.

I re-ran the update pi.alert after pausing it and it yelled at me that the database was read-only.

I ran the permission fix, and reran the update which went through successfully.

Not really sure 'why' this broke, but figured I'd let you know, not sure if it's a one off or something indicative of further issues.

I'll monitor it by having my daily work PC flagged to alert me on join and drop to ensure it doesn't stop again.

Thanks again for all your hard work!

### Environment

Raspberry Pi 4 - 2 GB model - runs Pi-hole, Pi.Alert and caddy exclusively, no other software.

**Comment by Vorteth** [comment]
Seems like it's still happening.

Came home and the system had a permission issue on the DB and then when it scanned it didn't see my phone there. I reran the scan command and it showed it as now being connected. I confirmed it says it is using user 'pi' and I am not executing the scan in sudo.

Thoughts?

**Comment by leiweibau** [comment]
What are the file permissions when this error occurs? Actually, the file permissions are set to the executing user at the start of each scan.

**Comment by Vorteth** [comment]
Not really sure candidly. I think something locked it up on the PiHole, I'll watch it. 

You can close this out or leave it open and I'll let you know if I notice a problem again.

**Comment by leiweibau** [comment]
Closed in agreement with the user
