### ISSUE TITLE
[Bug] Vendor Field - Self Populating?

### ISSUE THREAD

**Issue by bam7** [leiweibau/Pi.Alert#415]
I see behavior where any edits I make to the vendor field get overwritten on the next scan with generic system information.   For example, under vendor on a device it would say "Intel Corporate" presumably because it's a wireless NIC.  If I change this field to "HP" or "Dell" or  something similar, it changes back on the next scan.    Another common system value seems to be "(Unknown: locally administered)" on Apple devices and "Espressif Inc." on Sonoff smart switches.   

Is there not a way to make changes to that vendor field persistent, or am I missing something?  it doesn't seem like a useful sortable field if it can't be customized.

**Comment by leiweibau** [comment]
Hello,

> For example, under vendor on a device it would say "Intel Corporate" presumably because it's a wireless NIC. If I change this field to "HP" or "Dell" or something similar, it changes back on the next scan.

You made the right observation, and to be honest, I haven't given it any further thought. I will make adjustments here in the near future.

> Another common system value seems to be "(Unknown: locally administered)"

For this question, I refer you to the documentation https://github.com/leiweibau/Pi.Alert/blob/main/docs/RAMDOM_MAC.md

> "Espressif Inc." on Sonoff smart switches

Here I refer you to this URL https://www.netify.ai/resources/macs/brands/espressif as an example
I also have some IoT devices myself, with this vendor

**Comment by bam7** [comment]
It's a bit annoying to change back every time it auto populates.   At this point if this is the expected behavior, I will just hide that field and not use it to sort devices, no big deal.   Maybe something to think about for the future once all the important problems are solved.

**Comment by leiweibau** [comment]
The fix will be included in the next update. If nothing major comes in between, the release should happen in the next 3-5 days.
