### ISSUE TITLE
Unmet dependencies on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by iball** [leiweibau/Pi.Alert#42]
Running this on an Ubuntu 22.04 LTS minimal server required me to install cron and whiptail PRIOR to running the install script.

Once they were installed the script ran through and installed PiAlert just fine, minus PiHole which I didn't need to install.

Might want to think about adding checks for the presence of cron and whiptail at the beginning and installing them if not found.

**Comment by leiweibau** [comment]
Thank you for the hint.

**Comment by leiweibau** [comment]
should be fixed now
