### ISSUE TITLE
[Bug] File "<string>", line 53, in <module>

### ISSUE THREAD

**Issue by plawer** [leiweibau/Pi.Alert#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

Brand new installation without pi-hole. I am getting this error in the log pialert.log/pialert.1.log and when I run the job via ssh

```
Traceback (most recent call last):
  File "/home/pialert/pialert/back/./pialert.py", line 50, in <module>
    exec(open(PIALERT_PATH + "/config/pialert.conf").read())
  File "<string>", line 53, in <module>
NameError: name 'user' is not defined. Did you mean: 'super'?
```

I've tried applying ./pialert-cli set_permissions but that did not change anything (also with lxc and homedir parameter).

Original file config rights
```
pialert@pialert:~/pialert/config$ ls -al
total 36
drwxrwxr-x 2 pialert  www-data 4096 Nov 23 00:34 .
drwxr-xr-x 9 pialert  pialert  4096 Nov 11 19:34 ..
-rwxrwxr-x 1 www-data www-data 5880 Nov 23 14:15 pialert-prev.bak
-rwxrwxr-x 1 www-data www-data 5930 Nov 23 14:15 pialert.conf
-rwxrwxr-x 1 pialert  www-data 5892 Nov 23 00:32 pialert.conf.back
-rwxrwxr-x 1 pialert  www-data   83 Nov 11 19:34 version.conf
```

Attempted to change ownership on the config file. Same result
```
pialert@pialert:~/pialert/config$ ls -al
total 36
drwxrwxr-x 2 pialert www-data 4096 Nov 23 00:34 .
drwxr-xr-x 9 pialert pialert  4096 Nov 11 19:34 ..
-rwxrwxr-x 1 pialert www-data 5880 Nov 23 14:15 pialert-prev.bak
-rwxrwxr-x 1 pialert www-data 5930 Nov 23 14:15 pialert.conf
-rwxrwxr-x 1 pialert www-data 5892 Nov 23 00:32 pialert.conf.back
-rwxrwxr-x 1 pialert www-data   83 Nov 11 19:34 version.conf
```

### Environment

OS: Debian 12.7 CT on Proxmox 8.3.0, platform x64

**Comment by leiweibau** [comment]
When you write that you run Pi.Alert under Proxmox, did you install it via the helper scripts?

> when I run the job via ssh

Which command exactly are you trying to execute via ssh?

Does the regular scan work?

> also with lxc

The use of the "LXC" parameter only makes sense when installing via the helper scripts.

**Comment by plawer** [comment]
python3 ./pialert/back/pialert.py 1

**Comment by plawer** [comment]
And no, I only have the inital scan. It has not updated any of the hosts last session timestamp. It is the same as the first session.

![image](https://github.com/user-attachments/assets/df2be105-9b04-40b8-ad6c-bf4632cc4d2d)

**Comment by leiweibau** [comment]
When you write that you run Pi.Alert under Proxmox, did you install it via the helper scripts?

**Comment by plawer** [comment]
curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh | bash

**Comment by leiweibau** [comment]
I don't know how much time you want to spend troubleshooting, but if you want to run Pi.Alert under Proxmox, could you maybe try installing it via the Proxmox helper script? Here I have worked with the developer to realize a working installation under Proxmox?

https://community-scripts.github.io/ProxmoxVE/scripts?id=pialert

**Comment by plawer** [comment]
Thanks, I don't get the error now.
