### ISSUE TITLE
[Feature Request] MAC Vendor database updates?

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#423]
Is it possible to add additional entries to the MAC vendor database?

I would suggest the following additions: 

60:74:F4 is Govee home automation
A4:36:C7 is an LG Refrigerator

**Comment by leiweibau** [comment]
The vendor DB is regularly updated from the Internet and I have no influence on the content. What I could imagine, however, would be a kind of "individual vendor DB" that is "filled" by the user himself and is used with priority in the vendor assignment.

**Comment by hspindel** [comment]
> The vendor DB is regularly updated from the Internet and I have no influence on the content. What I could imagine, however, would be a kind of "individual vendor DB" that is "filled" by the user himself and is used with priority in the vendor assignment.

Thank you for the info.

I would think that would be a very low priority enhancement.

**Comment by leiweibau** [comment]
A separate .txt file, which is located in the db directory, is processed. 

<img width="820" alt="screen" src="https://github.com/user-attachments/assets/b20f366b-4493-4a6f-af15-21abce0481a6">

**Comment by hspindel** [comment]
Wow, thank you!

**Comment by hspindel** [comment]
I gave this a try, but I must be doing something wrong.  I have added the file pialert\db\user_vendors.txt.  Permissions on this file are -rwxrwxr-x.

6074f44f        govee

pialert scan reports:

govee.sci1.com | 2024-12-15   11:18 | 192.1.1.93 | 60:74:f4:4f:76:b1 | Private

I expected to see "govee" where the report says "private".

I tried stopping and restarting pialert scans.  Maybe I need to do something else to totally restart pialert?

Thank you!




</body>
</html>[govee.sci1.com](http://192.1.1.11/pialert/deviceDetails.php?mac=60:74:f4:4f:76:b1)	2024-12-15   11:18	192.1.1.93	60:74:f4:4f:76:b1	Private

**Comment by leiweibau** [comment]
`6074f44f govee`
is a TAB between  f and govee?

**Comment by hspindel** [comment]
> `6074f44f govee` is a TAB between "...f" and "govee"? The vendor assignment is only executed if “Vendor” is empty or “(unknown)” In the case you describe, you would have to define additional filters for which the vendor assignment is triggered

Yes, there is a tab there.

Where it now says "Private" I am pretty sure it used to "Unknown".  As a test, I've renamed user_vendors.txt to users_vendors.txt.save.  Then I stopped and restarted the scans.  Is there something more I need to do to get pialert to recognize a new user_vendors.txt?  It is currently still saying "Private".

You mentioned setting additional filters.  How do I do that?

**Comment by leiweibau** [comment]
No, the file is simply used. The “problem” at this point is that “Private” is not an “empty” string. In this sense, it is a “valid manufacturer”. For this reason, the vendor field is not set to “(unknown)” in order to trigger a new vendor assignment. I have a similar phenomenon sporadically in the VM. Here, “(Unknown: locally administered)” appears as the vendor. As I have already written, I would have to add another “list” that contains entries that are considered “invalid vendors”, i.e. trigger a new vendor assignment. Another classic example of: Looks simple, but it's not 😉

**Comment by hspindel** [comment]
Yikes.  I understand.  Too bad it was not as simple as it would appear to be.

The example user_vendors.txt mentions the issue you to which you are referring - that if a vendor field is detected, pialert ignores user_vendors.txt.  What would happen if you reversed that logic and allowed the contents of user_vendors.txt to override any detected vendor?

**Comment by hspindel** [comment]
Interesting!  I didn't realize the vendor field was user-editable.  That solves the issue for me.

Thank you.

**Comment by leiweibau** [comment]
I'm glad that Pi.Alert still has a surprise or two up its sleeve 😉. 
Let's see what else I can do with the current implementation.
