### ISSUE TITLE
[Bug] Errors on latest update

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

After updating pialert to the latest version, I got emails with the following messages:

RaspberryPi : Dec 15 00:33:20 : www-data : a password is required ; PWD=/root/pialert/front/php/server ; USER=root ; COMMAND=/usr/bin/killall arp-scan
RaspberryPi : Dec 15 00:33:21 : www-data : a password is required ; PWD=/root/pialert/front/php/server ; USER=root ; COMMAND=/usr/bin/chown -R www-data:www-data /root/pialert/back/../front/reports/
RaspberryPi : Dec 15 00:33:21 : www-data : a password is required ; PWD=/root/pialert/front/php/server ; USER=root ; COMMAND=/usr/bin/chmod -R 775 /root/pialert/back/../front/reports/
RaspberryPi : Dec 15 00:33:26 : www-data : a password is required ; PWD=/root/pialert/front/php/server ; USER=root ; COMMAND=/usr/bin/chmod -R 775 /root/pialert/back/../front/reports/
RaspberryPi : Dec 15 00:33:26 : www-data : a password is required ; PWD=/root/pialert/front/php/server ; USER=root ; COMMAND=/usr/bin/chown -R www-data:www-data /root/pialert/back/../front/reports/

pialert seems to be working normally despite the messages.

I tried to look for the files that are targeted for changes by the chmod and chown commands, but I see nothing named "reports" under the back directory.  Under the front directory there is a directory named "reports".  Its permissions are drwxrwxr-x, the owner is root, and the group is staff.

### Environment

Raspberry Pi.

**Comment by leiweibau** [comment]
> but I see nothing named "reports" under the back directory. Under the front directory there is a directory named "reports". Its permissions are drwxrwxr-x, the owner is root, and the group is staff.

There is a place with 2 “.” in the path specification. At this point, the program moves upwards in the directory tree. The path would be “/pialert/front/reports/”
root should normally be able to change permissions without a password.

**Comment by hspindel** [comment]
> There is a place with 2 “.” in the path specification. At this point, the program moves upwards in the directory tree. The path would be “/root/pialert/front/reports/” root should normally be able to change permissions without a password.

Okay, that's where I see the directory named reports.  So why would I get these errors?  Maybe I forgot to su before running the update script?

**Comment by hspindel** [comment]
I'm guessing the problem was that I forgot to su.  I re-ran the update script and it ran without errors.

Sorry for the rookie mistake.
