### ISSUE TITLE
Clicking on MAC address link in email results in '404 Not Found' Page

### ISSUE THREAD

**Issue by walksonair** [leiweibau/Pi.Alert#44]
When I get the emails for P.Alert Report, I often click on the MAC address to get more info as its a link back into Pi.Alert. Since switching to this fork, I noticed that I get directed to a 404 Page. It seems the issue may be due to the URL using http://pi.alert and thus not being resolved to my rasp_pi running Pi.Alert. 

Anyone run into this before and can help fix?

**Comment by leiweibau** [comment]
Hello,

there is a configuration option for it https://github.com/leiweibau/Pi.Alert/blob/main/config/pialert.conf#L35

**Comment by walksonair** [comment]
Thanks very much! I will modify the config document.

**Comment by leiweibau** [comment]
Check also the line above
