### ISSUE TITLE
Configure pialert without internet 

### ISSUE THREAD

**Issue by intheshell** [leiweibau/Pi.Alert#45]
Hello my friend

Can i install pialert on a network without internet. I try this but the device dont appears

Regards

**Comment by leiweibau** [comment]
Off the cuff, I can't answer the question, I would have to test it. You would then be missing the functions that MAC addresses are assigned to manufacturers. Also notifications would not work.

**Comment by leiweibau** [comment]
Another consideration to your request.
Prerequisites for such an installation are:
- all dependencies (python packages, software like webserver, arp-scan, etc) must already be installed on the system
- you need the package "pialert_latest.tar" from the repository

Then you could edit the installation script with the path of the "pialert_latest.tar". This should get the biggest problems out of the way. However, since the issue with dependencies is very individual, I can not make a precise statement.

**Comment by intheshell** [comment]
well, anyway what i did: i moved the machine that was working with internet to a network without internet and it stopped working.

**Comment by leiweibau** [comment]
Okay, so Pi.Alert is already installed? I can test this in the next days. 
Are you running Pi-hole on the same system?
Have you assigned a static IP to Pi.Alert or do you use a DHCP?

**Comment by leiweibau** [comment]
Try to change the following lines (line 181+) from

```
    # Get Internet IP
    print ('\nRetrieving Internet IP...')
    internet_IP = get_internet_IP()
    # TESTING - Force IP
        # internet_IP = "1.2.3.4"
```
to:
```
    # Get Internet IP
    print ('\nRetrieving Internet IP...')
    # internet_IP = get_internet_IP()
    # TESTING - Force IP
    internet_IP = "0.0.0.0"
```
Also the section beginning in line 702 from:
```
    # Check Internet connectivity
    internet_IP = get_internet_IP()
        # TESTING - Force IP
        # internet_IP = ""
```
to 
```
    # Check Internet connectivity
    # internet_IP = get_internet_IP()
        # TESTING - Force IP
    internet_IP = "0.0.0.0"
```
In my test environment it worked in offline mode. Here below again the links to the corresponding lines.
https://github.com/leiweibau/Pi.Alert/blob/main/back/pialert.py#L181
https://github.com/leiweibau/Pi.Alert/blob/main/back/pialert.py#L702

**Comment by intheshell** [comment]
Hello my friend, ok I will to check.

regards

**Comment by intheshell** [comment]
you are great!!, now i can use pialert without internet

regards
