### ISSUE TITLE
Speedtest-cli not working.

### ISSUE THREAD

**Issue by TCFlyer** [leiweibau/Pi.Alert#47]
Under Internet the speedtest button not working. Verified speedtest-cli is in the /pialert/back directory.

**Comment by leiweibau** [comment]
Can you show me the permission of the directory "back" and that of "speedtest-cli". What output is displayed when you call "speedtest-cli" directly?

ls -al ~/pialert/
ls -al ~/pialert/back/
~/pialert/back/speedtest-cli

**Comment by TCFlyer** [comment]
root@TIGNETMON:~# ~/pialert/back/speedtest-cli
/usr/bin/env: ‘python’: No such file or directory

When I installed `python-is-python3` it started working.

root@TIGNETMON:~# ~/pialert/back/speedtest-cli
Retrieving speedtest.net configuration...
Testing from Comcast Cable (XXX.XXX.XXX.XXX)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Summit Broadband (Orlando, FL) [124.07 km]: 26.097 ms
Testing download speed................................................................................
Download: 423.86 Mbit/s
Testing upload speed......................................................................................................
Upload: 11.74 Mbit/s

**Comment by leiweibau** [comment]
Can I now assume that everything is working correctly? If so, I would use your feedback for the documentation.

**Comment by leiweibau** [comment]
Should be fixed for new installations https://github.com/leiweibau/Pi.Alert/commit/ab854406894f0d25db23f31547e05ada81d8d6e4
