### ISSUE TITLE
Multisite and mysql 

### ISSUE THREAD

**Issue by juancabrio** [leiweibau/Pi.Alert#48]
I love this utility and the tweaks made here.  I'm thinking I could use this across all my sites if I had multisite support and MySQL.
I imagine an RPI at every site, all reporting home to a single DB.  That would be cool !

**Comment by leiweibau** [comment]
Yes, would be cool, but would significantly increase complexity. I will not implement it, at least from today's perspective :D

**Comment by juancabrio** [comment]
Yep, I agree. It would almost need a rewrite from scratch.  I will remain content querying my remote sites with some scripts and such.

**Comment by jokob-sk** [comment]
Sorry to comment on a closed issue, just thought of a possible  workaround - You could use a Home Assistant instance as your hub - I noticed @leiweibau added support for HA so if you @juancabrio are already using HA, this might be a way forward. I did something similar in my fork with MQTT as well. Just food for thought.
