### ISSUE TITLE
404 Not Found when trying to access pi alert

### ISSUE THREAD

**Issue by Mhuz** [leiweibau/Pi.Alert#49]
I just installed pi alert on my raspberry pi zero 2 w, alongside pi-hole. The installation was successful, but when I try to access the dashboard I simply get a 404 error.
![image](https://user-images.githubusercontent.com/22480189/208157144-efd2cd45-d1a0-4a31-b763-991a3277ef98.png)

Any solutions?

**Comment by PatrickScheich** [comment]
@Mhuz I encounter the same phenomenon, could you share the solution?

**Comment by Mhuz** [comment]
Since I removed it right after, I don't remember well. But if I recall correctly, the problem is in the url: check it, it should point to the wrong folder and return that 404 error. Let me know if I can help you more.

**Comment by n00bcodr** [comment]
@PatrickScheich were you able to fix this?
