### ISSUE TITLE
New Automated install - new crontab file is missing newline before EOF, can't install

### ISSUE THREAD

**Issue by ukjohnd** [leiweibau/Pi.Alert#50]
Replacing original working pucherot version with this supported fork.

Automated install fails with message
- Adding jobs to the crontab...
new crontab file is missing newline before EOF, can't install.

Used automated un-install script  prior to install and wiped crontab.

Environment
Debian 11 - Virtualbox guest.
Working Pi-hole install with dnscrypt-proxy

Many thanks

**Comment by ukjohnd** [comment]
Same Error running manual install command.
:~$ (crontab -l 2>/dev/null; cat ~/pialert/install/pialert.cron) | crontab -
new crontab file is missing newline before EOF, can't install.

**Comment by leiweibau** [comment]
Thank you for the message. Is fixed. It was a missing line break

**Comment by ukjohnd** [comment]
Confirmed working.

Many thanks for the very swift fix leiweibau, and thank you for keeping pi.alert alive
