### ISSUE TITLE
Additional languages?

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#52]
Of course, I can send the texts through a translator and then embed them. But since I want to do a reasonable job, I am dependent on support. Would perhaps one or the other be willing to check a roughly translated language file for errors and report back changes? If no one can be found, I will pause the idea further.

Interesting languages at the moment would be:
French, Italian, Czech, Polish

I would not have a fixed order.

**Comment by fr1cklr** [comment]
Hi @leiweibau, first of all, it's a great project - please keep on developing!

There are some typos in your German translation (eg. "Einstellungen" > "Wartung" > "Alle Geäte", "Alle Gräte"). I want to offer you to double check the German translation. Sadly, I am not speaking the languages mentioned above.

**Comment by fr1cklr** [comment]
By the way, after switching to German, the Location and Group drop-down lists of the device details stay in English.

**Comment by leiweibau** [comment]
Oops. Sorry. German of all languages should not be a problem for me ;) But that's how it is when the fingers are not fast enough for the head. The bugs you reported will be fixed in the next version.

> By the way, after switching to German, the Location and Group drop-down lists of the device details stay in English.

Yes, that is correct. However, since you can simply add your own entry to the field, I think a translation is unnecessary here.

**Comment by leiweibau** [comment]
The issue is closed because the expectation was not met.
