### ISSUE TITLE
[FAQ] Make Pi.Alert useable in offline Networks

### ISSUE THREAD

**Issue by intheshell** [leiweibau/Pi.Alert#53]
Hi my friend
I have an issue, when I m configure "mode offline" on Pialert to scan a network without internet, when i try to modify any device, i cant,

the logs shows: 

Pi.Alert 3.7.9 (2022-10-28)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-12-21 17:45:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1776, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 97, in main
    res = scan_network()
  File "/root/pialert/back/pialert.py", line 456, in scan_network
    copy_pihole_network()
  File "/root/pialert/back/pialert.py", line 604, in copy_pihole_network
    sql.execute ("DELETE FROM PiHole_Network")
sqlite3.OperationalError: database is locked
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@>

that database is locked, has any idea to do for unlock DB?

**Comment by leiweibau** [comment]
Please check the Permissions. Have you checked the FAQ/Help section? There is an entry about "read only" db.

**Comment by intheshell** [comment]
Thanks, but I have a question. It turns out that the database is not locked when I remove the "offline mode", it will be that some process takes the database by modifying the lines:

    # Get Internet IP
    print ('\nRetrieving Internet IP...')
    internet_IP = get_internet_IP()
    # TESTING - Force IP
        # internet_IP = "1.2.3.4"
to:

    # Get Internet IP
    print ('\nRetrieving Internet IP...')
    # internet_IP = get_internet_IP()
    # TESTING - Force IP
    internet_IP = "0.0.0.0"
Also the section beginning in line 702 from:

    # Check Internet connectivity
    internet_IP = get_internet_IP()
        # TESTING - Force IP
        # internet_IP = ""
to

    # Check Internet connectivity
    # internet_IP = get_internet_IP()
        # TESTING - Force IP
    internet_IP = "0.0.0.0"

**Comment by leiweibau** [comment]
Can you show me you pialert.conf, especially the Pi-hole Configuration?

**Comment by intheshell** [comment]
Yes ,sure 👍 

# Pi-hole Configuration
# ----------------------
PIHOLE_ACTIVE     = True
PIHOLE_DB         = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE       = False
DHCP_LEASES       = '/etc/pihole/dhcp.leases'

**Comment by leiweibau** [comment]
Why is PIHOLE_ACTIVE = True when you are in an offline network? Please set it to False

**Comment by intheshell** [comment]
ok thanks,  i Disable the pihole_active, but persist: 

    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1776, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 97, in main
    res = scan_network()
  File "/root/pialert/back/pialert.py", line 465, in scan_network
    save_scanned_devices (arpscan_devices, cycle_interval)
  File "/root/pialert/back/pialert.py", line 654, in save_scanned_devices
    sql.execute ("DELETE FROM CurrentScan WHERE cur_ScanCycle = ?",
sqlite3.OperationalError: database is locked
^@^@^@^@^@^@^@^@^@^@................

thanks for help me

**Comment by leiweibau** [comment]
With the "offline" fix and disabling Pi-Hole, I can't reproduce your error unfortunately. Here everything works as it should. 
At this point I would try to either restore a backup of my database or start again with an empty database from my fork.

**Comment by intheshell** [comment]
Hi Master, I have been looking for the reason why it could eventually be failing and I noticed that the database session is taken and apparently it is due to the process of...  Trying to resolve devices without name...

will it be so?


Devices Detected.......: 63
        arp-scan Method....: 61
        Pi-hole Method.....: +0
        New Devices........: 0

    Devices in this cycle..: 63
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 1
        Disconnections.....: 2
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name....



root@rle2ag-1:~/pialert/log# cd ..              
root@rle2ag-1:~/pialert# cd db
root@rle2ag-1:~/pialert/db# sudo fuser -v pialert.db
                     USER        PID ACCESS COMMAND
/root/pialert/db/pialert.db:
                     root       6157 F.... python3
root@rle2ag-1:~/pialert/db#

**Comment by leiweibau** [comment]
Based on your findings, you can try the following. Search
```    # Resolve devices names
    print_log ('   Resolve devices names...')
    update_devices_names()
```
and change it to

```    # Resolve devices names
    print_log ('   Resolve devices names...')
    # update_devices_names()
```

But I admit that it hurts a bit to cripple the software more and more :(

**Comment by intheshell** [comment]
If you are absolutely right, I believe that now the software is 100% in offline mode, since it does not make queries outside its network, therefore it is useful in case of having a panel to manage alerts without internet access (there are still , believe it or not) .

Thank you very much, it is solved.

**Comment by leiweibau** [comment]
I'm happy to hear that. 
Please note that you have to repeat these changes when you install an update. I will rename an issue so that it is obvious that there is information worth knowing here. At this time, I do not plan to "officially" include this mode.
