### ISSUE TITLE
Unable to SIGN OUT

### ISSUE THREAD

**Issue by francouai** [leiweibau/Pi.Alert#54]
Sorry, but I found another bug here.
When I click on the top/right PI-ALERT (SIGN OUT), it going back the the main menu  (pialert/devices.php)
LOGIN is enable on the Maintenance menu.

**Comment by leiweibau** [comment]
I can't reproduce this on my end right now. Could it be a cache problem?

**Comment by leiweibau** [comment]
Can you check the pialert.conf, if the Login is realy enabled?

**Comment by francouai** [comment]
I just set to TRUE this line:
"PIALERT_WEB_PROTECTION = True"
But I cannot change the default password from 123456 to something else.

I don't understand how to do it:

```
To change password run:
./pialert-cli set_password new_password
in the back folder.
```


pi@Pi-hole:~/pialert $ pialert-cli 123456 QWERTY
-bash: pialert-cli: command not found

I'm soo bad :)

**Comment by leiweibau** [comment]
you need to enter the directory "~/pialert/back" first. Then you can run `./pialert-cli set_password YOUR_NEW_PASSWORD`

**Comment by francouai** [comment]
haa perfect!!!
thanks!

**Comment by leiweibau** [comment]
There is a permission bug in the update script. I am working on it. The next update should not break the login settings button on the maintenance page.
