### ISSUE TITLE
arp-scan needs sudo privledges

### ISSUE THREAD

**Issue by amastelek** [leiweibau/Pi.Alert#58]
When a non-standard user is used, e.g. piadmin then the arp-scan fails in the cronjob

A file needs to be created /etc/sudoers.d/pialert-arpscan

piadmin ALL=(ALL) NOPASSWD: /usr/sbin/arp-scan

Maybe you can add that file for the user that is running pialert during install?

**Comment by leiweibau** [comment]
Yes, you are right. I'll leave this issue open for now until I implement a solution.
