### ISSUE TITLE
MAC field in Devices table is not populated

### ISSUE THREAD

**Issue by amastelek** [leiweibau/Pi.Alert#59]
The only thing listed is Random but I would assume the vendor name would be there as well?

**Comment by leiweibau** [comment]
Information about this https://github.com/pucherot/Pi.Alert/issues/201

**Comment by leiweibau** [comment]
Sounds nice. Feel free to make a pull request

**Comment by leiweibau** [comment]
But consider the aspect of copyrights on company logos. If in doubt, I will not include it in my fork.

**Comment by amastelek** [comment]
I'll use generic icons and when and display the vendor name on the hover.
