### ISSUE TITLE
install/pialert_cron does not respect individual install path

### ISSUE THREAD

**Issue by QuantumLibet** [leiweibau/Pi.Alert#61]
When installing Pi.Alert, an individual path can be chosen, which defaults to ~/pialert. The value is saved to the config/pialert.conf as PIALERT_PATH.

When installing the crontab, PIALERT_PATH is not evaluated, instead everything defaults to the default path of ~/pialert.

**Comment by leiweibau** [comment]
That's right. As you can see, an already finished "cron" file is entered into Cron.

https://github.com/leiweibau/Pi.Alert/blob/main/install/pialert.cron

The path variable is not used to be able to change the path, but to not always have to enter the path.

**Comment by leiweibau** [comment]
Technically, you can change the path, but the setup does not say about a possible change of the path.

"This script will install Pi.Alert in this system using this path" 
"Do you want to continue?"
