### ISSUE TITLE
[Feature Request] Configurable columns for device list

### ISSUE THREAD

**Issue by fr1cklr** [leiweibau/Pi.Alert#63]
I would love to have the possibility to change add or remove columns of the device list. For example, I would like to have the column "Location" added to and the column "MAC" removed from the device list. Changing the order of columns would be nice too.

**Comment by leiweibau** [comment]
Sounds interesting. I would have an idea for an implementation. When I have a little more time, I might implement it as a prototype.

**Comment by leiweibau** [comment]
Take a look at https://github.com/leiweibau/Pi.Alert/pull/66
I have invested some time. Surely there would still be a few possibilities for improvement, but on the whole, I am happy with it.

<img width="1084" alt="Bildschirmfoto 2023-01-13 um 21 33 48" src="https://user-images.githubusercontent.com/105860611/212414140-f2f3f5dc-05d9-4066-b961-1ead49911e9a.png">

I'm still testing it a bit and will work a bit more on the language files. In the next few days I will provide an update.

**Comment by leiweibau** [comment]
Okay ... "Location" is now added.
