### ISSUE TITLE
[Feature Request] Adding links to IP addresses in device list

### ISSUE THREAD

**Issue by fr1cklr** [leiweibau/Pi.Alert#65]
I would love to have the possibility to click on the IP address of a device (or an icon in an additional column) in the device list and visit its website, for example for those where port 80 has been identified as active in a nmap scan. With this devices with a GUI will be highlighted and can easily accessed.

**Comment by leiweibau** [comment]
Nice idea. Feel free to try it out for me ;) I like to look at pull requests :D

I'll also explain why I don't spend time on it. I myself have several webservers on different ports in my network. A link to a webserver running on port 80 or 443 would only be a useful feature for me in very few cases.
