### ISSUE TITLE
Next and previous buttons doesn't work in device details anymore

### ISSUE THREAD

**Issue by fr1cklr** [leiweibau/Pi.Alert#68]
The next and previous buttons on the top right of the device details page are disabled all the time.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/59923325/212701812-195eba10-3389-4955-bbc2-781ea2f08d91.png">

Am I the only one with this?

**Comment by leiweibau** [comment]
That's too bad.
I have it on the list. Is, probably due to the fact that I have added "Location" to the table for someone. ;D

**Comment by leiweibau** [comment]
If you can not wait for the update follow https://github.com/leiweibau/Pi.Alert/commit/eed38505b0ec1edb3236d51379c3eb8e7fcfa137
