### ISSUE TITLE
MAC address table not populated while MAC address of device known.

### ISSUE THREAD

**Issue by ToontjeM** [leiweibau/Pi.Alert#71]
![image](https://user-images.githubusercontent.com/98271783/213505329-35d579f9-a512-4b33-b6e5-a65e86dff591.png)
![image](https://user-images.githubusercontent.com/98271783/213505415-c78ef7d5-2194-41d7-9d2f-640a73d5d48b.png)

**Comment by leiweibau** [comment]
Look at https://github.com/leiweibau/Pi.Alert/issues/59
