### ISSUE TITLE
What does the * mean in the hostname?

### ISSUE THREAD

**Issue by ToontjeM** [leiweibau/Pi.Alert#72]
![image](https://user-images.githubusercontent.com/98271783/213506207-26660d37-a954-4317-a9f0-7cd95541ba55.png)

**Comment by leiweibau** [comment]
This means nothing to me, as I know nothing about the structure of your network. Probably the arp-scan could not do a meaningful name resolution. You can now see if you can get out which host it is via the details page using the nmap scan. Alternatively you can check your router or DHCP server.
