### ISSUE TITLE
not sorting by "Last IP"

### ISSUE THREAD

**Issue by ramess18** [leiweibau/Pi.Alert#73]
I think there is an issue with sorting by _Last IP_ in _Devices_ menu. All my IPs are somehow "shuffled" please see screenshot. 
![image](https://user-images.githubusercontent.com/16610727/213701510-5c745436-e5cf-4254-85c7-c07a09f43c86.png)
It appered in version 3.7.16 and still present in version 3.7.17

**Comment by leiweibau** [comment]
Look at https://github.com/leiweibau/Pi.Alert/issues/69

**Comment by ramess18** [comment]
Thanks. It worked :)
