### ISSUE TITLE
Ubuntu Server 22.04 - Pialert does not show Pihole records

### ISSUE THREAD

**Issue by ah92uk** [leiweibau/Pi.Alert#74]
On my Ubuntu Server 22.04 instance, Pialert has successfully been installed and devices on the local VLAN shown via ARP scan, however devices shown in PiHole (which spans VLANs) running on the same machine do not show in Pialert. 

I'm not sure if this is an issue with my installation or Pialert but a reinstall and update doesn't seem to solve it. 

All files (e.g. Pihole-FTL.db) are where they should be.

**Comment by leiweibau** [comment]
Does the scan log provide any helpful information?

**Comment by ah92uk** [comment]
Latest scan reads:

Pi.Alert 3.7.18 (2023-01-20)
---------------------------------------------------------
Current User: virtual1

Scan Devices
ScanCycle: 1
Timestamp: 2023-01-22 19:40:00

Scanning...
arp-scan Method...
arp-scan: One interface
Pi-hole Method...
DHCP Leases Method...

Processing scan results...
Devices Detected.......: 3
arp-scan Method....: 0
Pi-hole Method.....: +0
New Devices........: 0

Devices in this cycle..: 3
Down Alerts........: 0
New Down Alerts....: 0
New Connections....: 0
Disconnections.....: 0
IP Changes.........: 0

Updating DB Info...
Sessions Events (connect / discconnect) ...
Creating new devices...
Updating Devices Info...
Trying to resolve devices without name....
Names updated: 0
Voiding false (ghost) disconnections...
Pairing session events (connection / disconnection) ...
Creating sessions snapshot...
Skipping repeated notifications...
Calculate Activity History...

Reporting...
Formating report...
No changes to report...
Notifications: 0

DONE!!!

**Comment by leiweibau** [comment]
And your Config File looks like this?
```
# Pi-hole Configuration
# ----------------------
PIHOLE_ACTIVE     = True
PIHOLE_DB         = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE       = True
DHCP_LEASES       = '/etc/pihole/dhcp.leases'
```

**Comment by ah92uk** [comment]
DNS - yes, but PiHole isn't performing DHCP functions for my network, will that be an issue here? 

# Pi-hole Configuration
# ----------------------
PIHOLE_ACTIVE     = True
PIHOLE_DB         = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE       = False
DHCP_LEASES       = '/etc/pihole/dhcp.leases'

I notice the FAQ about /etc/sudoers, which I've applied - does this or other permissioning have influence on Pialert being able to read pihole-FTL.db? In my system, pihole-FTL.db is in the location specified above, whilst pialert is in /home/virtual1/pialert - not sure if that'd make a difference?

**Comment by leiweibau** [comment]
> DNS - yes, but PiHole isn't performing DHCP functions for my network, will that be an issue here?

I dont think so.

> does this or other permissioning have influence on Pialert being able to read pihole-FTL.db?

I could imagine that. But I don't have the time to set up an Ubuntu Server VM and play through the different configurations at the moment. I hope you have understanding for this.

What I would test in your place, would be:
- Create a backup of the config
- copy the database /etc/pihole/pihole-FTL.db into the user directory of "virtual1"
- Change the permissions for "virtual1"
- Change the path in the config to the current location of the new database copy.

If this works, it will be a permissions problem and you can work on a solution

**Comment by ah92uk** [comment]
>What I would test in your place, would be:

>Create a backup of the config
>copy the database /etc/pihole/pihole-FTL.db into the user directory of "virtual1"
>Change the permissions for "virtual1"
>Change the path in the config to the current location of the new database copy.

I've tried this with no luck unfortunately, I located the .db file within the /pialert directory and pointed Pi.Alert to the new location and still no PiHole DNS clients are found by Pi.Alert.

I've also reviewed the permissions and pihole-FTL.db has read permissions across owner, group and other/ world so that shouldn't be an issue from a basic file access perspective.

I'll have a look at sudoers.d, PiHole has an entry in there so I'm wondering perhaps some of the database operations between PiAlert and PiHole's .db needs sudo similar to the arp-scan FAQ posted above?

**Comment by leiweibau** [comment]
I just installed an Ubuntu server 22.04.1 in a VM and to it. Using the install script from my fork, I installed Pi-Hole and Pi.Alert. I have not added the sudo modification here yet. After a few minutes the first devices appeared. In the "Events" I see that apparently some data from Pi-Hole are taken over (arp-scan was not executed because of missing sudo).

<img width="692" alt="screenshot" src="https://user-images.githubusercontent.com/105860611/214007253-71bef2d1-2294-4d21-b903-48ee76fa1491.png">

**Comment by ah92uk** [comment]
Very odd - it must be my configuration somewhere? I've uninstalled and reinstalled both PiHole and PiAlert completely and still face the same issue.

If you have time and wouldn't mind, could you ls -l the /pialert/back and /etc/pihole directories and let me know your pialert.conf settings please?

**Comment by leiweibau** [comment]
Hello,

sorry it took a while. But instead I have looked into the topic a little more closely. I had to set up the VM from last time again first.

Environment:
- Ubuntu Server 22.04.1
- User is not yet configured as sudoer
- Network of the VM is isolated

Test scenario:
- Pi-hole database of a productive instance backed up
- Database copied to the VM
- With the next cronjob the devices showed up in the Pi.Alert device list

Conclusion:
```
Processing scan results....
Devices Detected.......: 3
arp-scan Method....: 0
Pi-hole Method.....: +0
New Devices........: 1
```
- Despite adding the new hosts, the Pi-hole Method shows "0" (I'm not through the Python code yet, but think this counter only affects the DHCP server function of Pi-hole.)
- You can recognize the hosts from the Pi-hole database by "(Pi-Hole)" in the event list
- In case of questions, I let the VM exist for now

**Comment by ah92uk** [comment]
Hi,

Thanks for looking into this in more detail! The instance I'm running still doesn't seem to function despite various attempts to play around with the permissioning, sudoers etc. and reinstall.

I've also tried forcing the Pihole process by modifying the code to remove the "if" functions and moving the Pihole copy function as part of the main always-executed code, to no avail.

The ARP scanning works fine for me and I can scan the management VLAN it resides within but the Pihole connectivity just doesn't seem to be there.

It must be something to do with my machine, so this could be closed as a niche issue?

**Comment by leiweibau** [comment]
Before I delete the VM, is there anything else you want to know?
