### ISSUE TITLE
pialert_vendors.log

### ISSUE THREAD

**Issue by Primal-id** [leiweibau/Pi.Alert#75]
clicking "vendor update" button results in error No log available 

![image](https://user-images.githubusercontent.com/1058873/213926282-b3a83a7f-dfdd-4e18-b8ad-064687d41626.png)

![image](https://user-images.githubusercontent.com/1058873/213926458-1115857d-63a8-489e-bffd-de7b9b297604.png)

**Comment by leiweibau** [comment]
File size is 0kb. 0kb = no log

**Comment by leiweibau** [comment]
I am more irritated because of the side displays. I will check the CSS asap.

**Comment by leiweibau** [comment]
I hope your opening question is answered.

To my confusion regarding the screenshot and page rendering. I have tested with:
- Firefox (macOS / Windows 11)
- Firefox - Private Window (macOS / Windows 11)
- Safari (macOS)
- Safari - Private Window (macOS)
- Edge (Windows 11)
- Edge - InPrivate Window (Windows 11)
- Google Chrome (macOS)
- Google Chrome - Incognito Window (macOS)
- Firefox Mobile (iOS and Android)
- Chromium (Debian)
- Chromium - Incognito (Debian)
Nowhere is the page displayed as it is on your screenshot.

**Comment by leiweibau** [comment]
Perhaps there is also a problem of understanding here. The "Vendor Update" button is in the "Log Viewer" box. Here no Vendor Update is made, but only the log of the "Vendor Update" is opened.
