### ISSUE TITLE
[Feature Request] - Add more locations and types

### ISSUE THREAD

**Issue by Primal-id** [leiweibau/Pi.Alert#76]
It would be nice to be able to add more locations to the drop down box and types. Such as I could add camera, smart plug or VM (virtual machine) to the drop down list. Same with locations. I could add closet. Self adding would be useful. Hard to predict every category someone would need

**Comment by leiweibau** [comment]
You can simple type a new location in the field.

**Comment by Primal-id** [comment]
Works perfectly. Thanks!
