### ISSUE TITLE
chmod: cannot access '/home/jay/pialert/front/reports': No such file or directory

### ISSUE THREAD

**Issue by voxie12** [leiweibau/Pi.Alert#77]
i tried to install pialert on both dietpi and raspbian but both doesnt work at all. i got this error. it says "chmod: cannot access '/home/jay/pialert/front/reports': No such file or directory"

i used it without sudo if you ask.

**Comment by leiweibau** [comment]
It is only a commit at the moment. The updated package will follow in the next hours with the necessary folder.

**Comment by leiweibau** [comment]
I have now updated the package. Unfortunately, the notification does not work with with dietpi :( Probably I have to rebuild it.

**Comment by leiweibau** [comment]
Does it work? The problem described above excluded.

**Comment by voxie12** [comment]
it does work on raspbian! thanks for your help.
