### ISSUE TITLE
Delete all notifications at once?

### ISSUE THREAD

**Issue by voxie12** [leiweibau/Pi.Alert#79]
I have 1218 notifications. I couldn't be bothered clicking "delete" bottom every time.

Is there a way to delete all of them at once?

Thx

**Comment by leiweibau** [comment]
Do you see a big red button under the headline on the notification page? I added this feature with the last update. Do you have the latest version?

**Comment by voxie12** [comment]
i am on 3.7.19  (2023-01-24) 

ill update to see if i can.

**Comment by voxie12** [comment]
i can see big red button and thank you a lot. keep the good work up

**Comment by leiweibau** [comment]
I try my best
