### ISSUE TITLE
[Feature Request] Adding pagination to the bottom of deviceDetails.php

### ISSUE THREAD

**Issue by fr1cklr** [leiweibau/Pi.Alert#81]
The pagination to the upper right hand of the deviceDetails.php should be added to the bottom of the page as well as this would increase the comfort for the mobile version, for example.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/59923325/217539700-da5b3b61-e682-406b-98f6-b0f9704d0128.png">

**Comment by leiweibau** [comment]
Hello

In principle, this is not a problem. Can you sketch for me where it is best to place this button group? With or without the counter in the middle?

**Comment by fr1cklr** [comment]
Below the blue "Save" button. If possible, with the counter (1:1 like the upper one).

**Comment by leiweibau** [comment]
I have implemented it and will test it some more in the next few days. A release will only be made with the completion of the web service monitoring.

Here you can find the corresponding commit https://github.com/leiweibau/Pi.Alert/commit/6e5683199ff07fb6a79cfafe9bed660cfe62bc12
<img width="177" alt="Bildschirmfoto 2023-02-09 um 22 42 56" src="https://user-images.githubusercontent.com/105860611/217946765-453dd75e-8e32-486a-8bd8-601d81fd2af0.png">

**Comment by leiweibau** [comment]
Update Released
