### ISSUE TITLE
Script "pialert.py" is broken when using Python2

### ISSUE THREAD

**Issue by SWLtd** [leiweibau/Pi.Alert#83]
`File:  ./pialert/back/pialert.py`
`Line:  21`

Problem Description:
   When running under Python2, this script fails due to the Python3-only syntax for the `urlparse` library import...

Old Code:
`   from urllib.parse import urlparse`
New Code:
`   try:`
`      from urlparse import urlparse`
`   except ImportError:`
`      from urllib.parse import urlparse`

BTW:
   Thanks for forking and carrying on with this development.  I'm liking the new changes from Pucherot's last version.

**Comment by leiweibau** [comment]
That is possible. I will try to edit the installation script in the next time. Python 2 is no longer maintained (EOL) by the developers for 3 years.

**Comment by leiweibau** [comment]
Feel free to make a pull request
