### ISSUE TITLE
the disk is getting fat and fat for no reason.

### ISSUE THREAD

**Issue by voxie12** [leiweibau/Pi.Alert#84]
![image](https://user-images.githubusercontent.com/65469239/219065919-4a2652f5-119a-4bd0-b6bd-125f43d6157f.png)

os: debian
disk: 250GB
mem: 8gb
last time i installed it on 8 feb 2023

i posed my issue in pihole forum:
https://discourse.pi-hole.net/t/disk-shortage-etc-pihole-pihole-ftl-db-ahead-99-used/60945

after i installed pihole (native), i also installed unbound and pialert.
i let it run for about a week. then i found an error in Pi-hole diagnosis.

is pialert the reason to fill the storage so fast?

thx

**Comment by leiweibau** [comment]
My development version of Pi.Alert is about 130 MB including 3 database backups. The size of the database is also related to the number of devices and the storage time in the configuration file.

My Pi-hole version is significantly larger here, which is also related to appropriate configurations and block lists. In my case, that's 1.1GB in /etc/pihole alone.

**Comment by voxie12** [comment]
i used ncdu,

total disk usage:
/ : 10.5 GiB
/etc/pihole : 196.9 MiB
/home/jay/pialert : 101.7 MiB

![image](https://user-images.githubusercontent.com/65469239/219157310-a349e37f-3ff4-4445-a660-c14f12110995.png)

i installed armbian on orange pi zero 2 on 22th oct 2022 and then i put pihole, unbound and pialert on the same day. the disk is only 16% which is good. i just dont understand whats going on my debian. i cant find what is causing it.

**Comment by voxie12** [comment]
ncdu says 10.5GB of /
duf says 148GB of /
du says 11GB of /
dust says 10GB of /

i think duf is correct.

**Comment by voxie12** [comment]
ok

**Comment by leiweibau** [comment]
However, if you find the cause of this problem, I would be interested in that as well, as it is quite a strange problem.

**Comment by voxie12** [comment]
i finally found an issue. the problem is unbound...

[pihole doc unbound](https://docs.pi-hole.net/guides/dns/unbound/#setting-up-pi-hole-as-a-recursive-dns-server-solution): kept making the disk used.

[wundertech](https://www.wundertech.net/use-unbound-to-enhance-the-privacy-of-pi-hole-on-a-raspberry-pi/): perfectly fine.

i guess the issue is not your problem.

**Comment by leiweibau** [comment]
Thank you for your feedback.
