### ISSUE TITLE
"Save" button not clickable in mobile version

### ISSUE THREAD

**Issue by fr1cklr** [leiweibau/Pi.Alert#85]
![Screenshot_20230220_173307_Chrome](https://user-images.githubusercontent.com/59923325/220177869-482f084b-f6a8-4c70-8a0e-7cb7aab8b3ab.jpg)

After updating a device (Android/Chrome), the blue "Save" button gets activated, but it cannot be clicked. Using the pagination, it works (= device infos get saved before next device gets displayed). I guess it has to do with the newly added pagination ;)

**Comment by leiweibau** [comment]
I just tested it mobile as well (iOS Firefox) and can't reproduce the problem at the moment, the "Save" button works as expected. Since I'm on business right now, I can't take care of it in the next few days.

**Comment by leiweibau** [comment]
I have now tested several times over the last few days with iOS/Safari and Android/Firefox, but could not reproduce the error you describe

**Comment by leiweibau** [comment]
Does this problem still exist, or was it possibly temporary? If the problem still exists, I would appreciate step-by-step instructions on how to reproduce the error.

**Comment by fr1cklr** [comment]
Thanks for sticking with it! That issue still exists. For me :) It only appears, when the "Save" button is located as shown in the vertical screenshot (2nd line of buttons). When I turn the phone horizontally, there's enough space for all four buttons and then it works as desired by pressing on "Save" after an update of a device.

I can reproduce it even on my notebook by down-sizing a browser window that much (minimal width) that a second line of buttons appear. If the buttons are still in one line above the pagination you can press "STRG/CMD" and "+" to increase the size of the browser content and then the second line of buttons appear (see screenshot below). In that case, it's not possible to submit the "Save" button.

So, when the button is in the same line with the pagination it does not work. Why does this second line of buttons appear due to less space on my smartphone and not on yours? Maybe because my eyes are not the best and I have a bit bigger font size on my smartphone than it's standard.

![image](https://user-images.githubusercontent.com/59923325/222777171-28d9e766-e999-4b55-b92a-7f9e9acbe4df.png)

**Comment by fr1cklr** [comment]
Works like a charme. Thank you!
