### ISSUE TITLE
Deviceports not shown on network site

### ISSUE THREAD

**Issue by flwilk** [leiweibau/Pi.Alert#86]
I created some switches and added devices to them. The devices were shown but portnumbers are missing (not shown).

**Comment by leiweibau** [comment]
Silly question. Did you also specify the number of ports?

![84003CF2-9767-4B10-931D-D01EE62CCF80](https://user-images.githubusercontent.com/105860611/220260973-844fb9db-2a1d-4317-8c5f-3a7896c6b81e.jpeg)

If you edit the switch, you must re-enter the port count or it will be deleted.

**Comment by flwilk** [comment]
Yes, ports are specified...after I edited the switch again and added the ports again it is shown. Could be I edited the switch before an did not enter the ports. Perhaps you can add a note about editing the devices on the network page?

Seems to appear due to incorrect operation.

**Comment by leiweibau** [comment]
I know that there is still some room for improvement here. If there is time left, I will certainly work on it a bit more.
