### ISSUE TITLE
sqlite3.OperationalError: no such table: Services_Events

### ISSUE THREAD

**Issue by JYewdall** [leiweibau/Pi.Alert#87]
Ran update to latest version  and then ran cleanup.
cleanup shows old version and a missing table
My Pi.Alert is running quite happily.

Pi.Alert (2023-02-10)
---------------------------------------------------------
Current User: pi

Cleanup Database
Timestamp: 2023-03-02 02:00:00

Cleanup Services_Events, up to the lastest 30 days...
Traceback (most recent call last):
File "/home/pi/pialert/back/pialert.py", line 2229, in
sys.exit(main())
File "/home/pi/pialert/back/pialert.py", line 95, in main
res = cleanup_database()
File "/home/pi/pialert/back/pialert.py", line 353, in cleanup_database
sql.execute ("DELETE FROM Services_Events WHERE moneve_DateTime <= date('now', '-"+strdaystokeepOH+" day')")
sqlite3.OperationalError: no such table: Services_Events

**Comment by leiweibau** [comment]
I'm guessing you don't have "Web Service Monitoring" enabled?

Yes, I missed to include the query for the status of the "Web Service Monitoring" during the "cleanup" as well. As a quick fix, you can enable the "Web Service Monitoring" for about 15 minutes. In the process, the missing entries in the database will be added. After that, you can deactivate the function again. I will take care of this in the next update.

Which version do you see in the lower right corner (in Pi.Alert)? The log you show here is from the cronjob 2am (yesterday).

If you run the "cleanup" via console/terminal usually no log is written unless you use:
`python3 ~/pialert/back/pialert.py cleanup >~/pialert/log/pialert.cleanup.log`

**Comment by JYewdall** [comment]
Doh! Of course when I click on cleanup I am viewing the log not performing a cleanup. 
I ran python3 ~/pialert/back/pialert.py cleanup >~/pialert/log/pialert.cleanup.log and the response was:

python3 ~/pialert/back/pialert.py cleanup >~/pialert/log/pialert.cleanup.log
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2211, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 98, in main
    res = cleanup_database()
  File "/home/pi/pialert/back/pialert.py", line 364, in cleanup_database
    sql.execute ("VACUUM;")
sqlite3.DatabaseError: database disk image is malformed

cleanup log shows:
Pi.Alert (2023-02-26)
---------------------------------------------------------
Current User: pi

Cleanup Database
Timestamp: 2023-03-04 09:51:00

Cleanup Services_Events, up to the lastest 30 days...

Cleanup Online_History, up to the lastest 30 days...

Cleanup Events, up to the lastest 90 days...

Shrink Database...

**Comment by leiweibau** [comment]
This was my fault now. I forgot a „ “
`python3 ~/pialert/back/pialert.py cleanup > ~/pialert/log/pialert.cleanup.log`

But the log looks okay now.
