### ISSUE TITLE
Cannot get it scanning multiple vLANs

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#88]
Hi,

So I've installed this on a VM on subnet 192.168.1.0/24 which has privileges to access all other subnets.

In the config I've set:
SCAN_SUBNETS    = '192.168.1.0/24 192.168.5.0/24 192.168.10.0/24 192.168.15.0/24 192.168.20.0/24 192.168.25.0/24 192.168.30.0/24 192.168.35.0/24 192.168.40.0/24 192.168.45.0/24 192.168.50.0/24 192.168.55.0/24 192.168.60.0/24 192.168.65.0/24 192.168.70.0/24 192.168.75.0/24 192.168.80.0/24 192.168.85.0/24 192.168.90.0/24 192.168.95.0/24 192.168.100.0/24 192.168.200.0/24'

I restarted the whole server (as I wasn't sure how to restart just pi.alert) to ensure the config was loaded.

I noted in the settings page:
Scan Status	1 scan(s) currently running

After it finished it only seems to have found a single device on 192.168.20.0/24 which was a raspberry pi running AdGuard as one of the networks nameservers. There is another instance of AdGuard running on the same subnet on a VM but this wasn't detected. Nor was anything else on any other subnet (and there's plenty to be discovered).

Not sure what i'm doing wrong?

**Comment by TheCableGuy99** [comment]
Never mind with this, I've gone with another solution.

**Comment by Couto** [comment]
@TheCableGuy99 What is the other solution that you used? Thanks

**Comment by TheCableGuy99** [comment]
> @TheCableGuy99 What is the other solution that you used? Thanks

Honestly, I can't remember but as I see it I've got the vlans up and running with a guide similar to this one:
[https://www.sbprojects.net/projects/raspberrypi/vlan.php](url)

And my config looks slightly different to that of my above post:
`SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth0', '192.168.5.0/24 --interface=eth0.5', '192.168.10.0/24 --interface=eth0.10', '192.168.15.0/24 --interface=eth0.15', '192.168.20.0/24 --interface=eth0.20', '192.168.25.0/24 --interface=eth0.25', '192.168.30.0/24 --interface=eth0.30', '192.168.35.0/24 --interface=eth0.35', '192.168.40.0/24 --interface=eth0.40', '192.168.50.0/24 --interface=eth0.50' ]`

I'm presuming both of those got it working as it is now.

**Comment by Tuxtom007** [comment]
Hello,

maybe it helps someone, I have found a solution that works quite stable for me at the moment.
- PiAlert runs in a Linux container on Proxmox
- I use around 10 VLANs in the network, each VLAN has a /24 IP network
- I have given PiAlert another network interface in Proxmox for each VLAN, but without an IP address, the NICs are called eth0.<VLAN-ID> accordingly.
- after countless attempts, the following config is the best for me and it works:

`SCAN_SUBNETS    =  ['--localnet --interface=eth0', '10.0.10.0/24 --interface=eth0.10 --arpspa=10.0.10.253', , '10.0.20.0/24 --interface=eth0.20 --arpspa=10.0.20.253', ....]`
