### ISSUE TITLE
[Feature Request] Detect DHCP servers

### ISSUE THREAD

**Issue by juancabrio** [leiweibau/Pi.Alert#90]
Hi, 
I find it useful to scan for DHCP servers.  Sometimes there is a rogue server out there.  Maybe an option to display all DHCP servers on the network would be handy. 

Cheers

Juan.

**Comment by leiweibau** [comment]
Nice idea. I just took a look at how this could be implemented.

**Comment by leiweibau** [comment]
It is implemented https://github.com/leiweibau/Pi.Alert/commit/e395176cbd691fa6f99e2e79001e3fbd1eba3d58
It will be released as an update in the next few days.
