### ISSUE TITLE
Issue with mapping switches together

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#91]
Hi,

I've been playing and managed to get this working, stable and scanning all vLANs now (yayyy), this is definitely number 1 for my network monitoring now as I can't have all the vLANs in a docker and need it to run on a proper O/S.

Anyway, I was mapping ports when I realised although I can map a device to multiple ports (for port aggregation), I cannot map a switch to more than 1 other switch.

It appears to be limited to a daisy chain network setup which is a problem and means I cannot use this feature properly.

I have many managed switches which all connect to each other using multiple ports for link aggregation. 

Am I missing something or can this not be done? If not can I put it forward as a feature improvement please?

Thanks.

**Comment by leiweibau** [comment]
Sorry, can you make me a sketch please?

**Comment by TheCableGuy99** [comment]
Sure:

This is in it's more simple form... It's easy enough to map each port for each switch. But if a switch is connected to multiple switches using multiple ports then it becomes a problem because you can't seem to say a switch is connected to more than one switch.

So with the diagram, how would I go about saying one of the switches is connected to two other switches and using multiple ports for each switch? 

![diagram](https://user-images.githubusercontent.com/39552752/224570990-d65402f2-1a50-49bc-8ac7-c27c7b3f39b5.png)

Thanks.

**Comment by leiweibau** [comment]
This should be possible, if I understand you correctly. Have you looked at the help "How does the network page work?" (help_faq.php#collapse601)?
You would have to enter the destination MAC and the local port in the manual port configuration for each switch, via editing (ATTENTION, do not forget to enter port number and type again).

Router (11:22:33:aa:bb:cc), Swtch A Port 1 and 2, Switch B Port 3 and 4
Switch A (aa:bb:cc:dd:ee:ff) Router port 1 and 2, Switch B port 3 and 4
Switch B (11:22:33:44:55:66) Router port 1 and 2, Switch A port 3 and 4.

manual configuration router:
aa:bb:cc:dd:ee:ff,1;aa:bb:cc:dd:ee:ff,2;11:22:33:44:55:66,3;11:22:33:44:55:66,4;

manual configuration Switch A:
11:22:33:44:55:66,1;11:22:33:44:55:66,2;11:22:33:44:55:66,3;11:22:33:44:55:66,4;

manual configuration Switch B:
11:22:33:44:55:66,1;11:22:33:44:55:66,2;aa:bb:cc:dd:ee:ff,3;aa:bb:cc:dd:ee:ff,4;

At the moment, a manual port configuration already stored is not shown again. I have it on my to-do list, but the priority is not high. I am aware that the configuration is not intuitive, but I made a mistake in thinking when I first created it. After that I had to decide for myself between a complete rewrite, this solution or the removal of this feature.

**Comment by TheCableGuy99** [comment]
I have to be honest it's a bit confusing this so if you are undecided on the future of this feature i'm going to leave it for now. If it does get a proper re-vamp in the future i'd love to see the ability to map switches as well as port. Maybe even a network map could automatically be generated for people once they have entered the connection info?

I'll leave it with you on this occasion. Thanks!

**Comment by TheCableGuy99** [comment]
I took another look at this with a fresh head and was able to get it working (thank you). I just have a little complicated setup and I needed to get my head round it slowly and think about what device is connecting to where but it works quite nicely.

I do still have a couple of questions though...
1) Can wifi devices be added to multiple APs? For example, I have an iPhone which switches APs depending which building i'm in so I'd like to be able to add that (amongst other portable devices) to multiple APs so it shows which one it's connect to. Is that possible?
2) I'd really like to see the ability to add devices to switch ports that are not found in the scan. The reason for this is there are ports assigned that might be reserved or just being used for power. These might not be network capable devices but still use the switch. So if we can manually add devices to a switch port we can still see that the port is in use... also a tick box to say it's using power would be nice.

Thanks again for your consideration on this and your help.

**Comment by leiweibau** [comment]
> Can wifi devices be added to multiple APs? For example, I have an iPhone which switches APs depending which building i'm in so I'd like to be able to add that (amongst other portable devices) to multiple APs so it shows which one it's connect to. Is that possible?

The assignment to multiple APs is not possible at the moment, although the idea is quite plausible.
Detection of which AP a Wi-Fi device is logged on to is technically not possible with the type of detection (arp-scan).

> I'd really like to see the ability to add devices to switch ports that are not found in the scan. The reason for this is there are ports assigned that might be reserved or just being used for power. These might not be network capable devices but still use the switch. So if we can manually add devices to a switch port we can still see that the port is in use... also a tick box to say it's using power would be nice.

This should already be addressed with Issue https://github.com/leiweibau/Pi.Alert/issues/95.

**Comment by TheCableGuy99** [comment]
> The assignment to multiple APs is not possible at the moment, although the idea is quite plausible.
Detection of which AP a Wi-Fi device is logged on to is technically not possible with the type of detection (arp-scan).

Okay so if it's not possible to detect which AP it's connected to if it was able to be added to multiple APs in the network I presume it would still appear as "Online" to all AP's it's assigned to? If so I could at least assign it to multiple APs and see if it's online. Although not perfect it's a step to still being a better feature.

> This should already be addressed with Issue https://github.com/leiweibau/Pi.Alert/issues/95.

Thanks I've replied to issue #95 as I wanted to clarify the needs.

**Comment by leiweibau** [comment]
You have now given me a big wish list. 😉 Some things are easy to do, others not. Since I am also only a small hobby programmer who also has a real job (even if it does not look like that 😉 ) I ask for patience and forgiveness if I do not implement something or something else very slowly.

**Comment by TheCableGuy99** [comment]
I know mate, I'd love to help but i'm no programmer myself. I've recently discovered this and without your fork specifically being able to run on a popper O/S i'd still be looking for a decent program to monitor my network on multiple subnets/vLANs so thank you for all you do.

There's absolutely no rush, these are all just things that I feel would make it a bit better an part of progression, if you manage to do even some of them it would be most appreciated :)

**Comment by leiweibau** [comment]
I hope that the upcoming update will also help you with the issue of assigning one device to multiple wlans. It is not that this is now explicitly possible, but with the help of the "dummy" devices, you can now assign a device with the same name to another wlan. Only the entry "Unmanaged" at the IP, would make the difference.

<img width="864" alt="Untitled" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/218b942e-51ea-40cd-9c1b-f02c6cbfbf2b">

The yellow "UM" badge appears only on devices that work with port numbers.

<img width="817" alt="Untitled1" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/aa13382f-2a7d-4d0b-9dde-a6d8d916eb83">

**Comment by TheCableGuy99** [comment]
ahhh very nice!!!

Oh another note, why does the page where you enter details for a device constantly refresh when you change tabs? I'm always changing tabs to look up information on a device to enter it and when returning I have a popup about leaving the page as though I'm trying to.

It's just not normal behaviour?

**Comment by leiweibau** [comment]
Yes, that is what is desired. In the context of a mobile app, this also makes sense, since you don't have any controls in a fullscreen app. However, when used as a desktop web page, I understand the irritation about this. I will add a dependency to the screen resolution or to the user agent.

**Comment by TheCableGuy99** [comment]
There's a mobile app? Where please? I searched the iOS store and couldn't find one!

**Comment by leiweibau** [comment]
Sorry. By mobile app I meant "mobile web app", in other words putting a web page on the home screen.

**Comment by TheCableGuy99** [comment]
Ahh right, never done that once, only ever used bookmarks in my browser. But if you're going to resolve it by resolution it's another tick towards progression... THANK YOU! Really love this program!
