### ISSUE TITLE
[Feature request] Display mac address field

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#92]
Hi, 

Can I request a field to display the mac address on the "Devices" page?

Thank you.

**Comment by jokob-sk** [comment]
Hey!

You can set displayed column names and the order in the Maintenance section.
J

**Comment by jokob-sk** [comment]
Sorry wrong fork.

**Comment by leiweibau** [comment]
I will take care of this in the near future

**Comment by TheCableGuy99** [comment]
Thank you, could I also request some additional fields/options?0

In the "Device > Details" page you currently have the "Vendor", could we have a field for the "Model" below so both the vendor and item model can be logged?

Could we also get a field for the serial number?

Lastly, an option to save the database and download it and re-import it? Maybe an auto save option?

Thanks for your consideration in all these. I think they would be a great addition..

**Comment by TheCableGuy99** [comment]
Sorry I just thought of one other feature that would be nice for consideration if possible please...

Could we have the ability to add something to the database even if it's not online?

**Comment by leiweibau** [comment]
I have added the possibility to show the Mac address in the overview
