### ISSUE TITLE
[Feature Request] Additional fields on the details page

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#93]
@TheCableGuy99

In the "Device > Details" page you currently have the "Vendor", could we have a field for the "Model" below so both the vendor and item model can be logged?

Could we also get a field for the serial number?

**Comment by leiweibau** [comment]
I will think about it

**Comment by TheCableGuy99** [comment]
Thanks :)

**Comment by leiweibau** [comment]
it is done. It will be included in the next update

**Comment by TheCableGuy99** [comment]
Fantastic mate!!! Thank you very much :)))
