### ISSUE TITLE
[Feature Request] Option to save the database and download it

### ISSUE THREAD

**Issue by leiweibau** [leiweibau/Pi.Alert#94]
@TheCableGuy99

Lastly, an option to save the database and download it and re-import it? Maybe an auto save option?

**Comment by leiweibau** [comment]
The backup function could be used for this purpose.

A saving is therefore already possible. A download of the backup is an easy function to implement at that moment. 

The upload would then be the challenge. I will think about it.

**Comment by TheCableGuy99** [comment]
Yeah, I did note the download but it's not as easy to restore as a web upload if possible.

Thanks for your consideration :)

**Comment by leiweibau** [comment]
After some testing and some research, I have to say no to the request for a DB upload. I hope I could help at least a little bit with the download option

Reason: 
1. my own environment is not based on "lighttpd" but on "nginx", so I have to implement extra configurations for this alone.
2. also for "lighttpd" an additional configuration is necessary, which differs from the previous one. And I do not want to damage a running configuration.
