### ISSUE TITLE
[Feature Request] Ethernet or Wi-Fi

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#96]
Can you add a drop down box to select if a device is Ethernet or Wi-Fi?

As some device have both it's important to log both so I currently have to add (Ethernet) or (Wi-Fi) in the suffix of the name to identify how it's connecting.

Thanks for your consideration.

**Comment by leiweibau** [comment]
I will think about it

**Comment by TheCableGuy99** [comment]
Thanks :)

**Comment by ramess18** [comment]
I would rather have an option to have device with ethernet and Wi-Fi - to be as one device instead of two.

**Comment by ramess18** [comment]
> Can you add a drop down box to select if a device is Ethernet or Wi-Fi?
> 
> As some device have both it's important to log both so I currently have to add (Ethernet) or (Wi-Fi) in the suffix of the name to identify how it's connecting.
> 
> Thanks for your consideration.

You can achieve this via Network (left menu). Then you can on device select your option (Wifi, Switch..).
See my device's screenshot:
![image](https://user-images.githubusercontent.com/16610727/225246518-c9758a6f-c58b-4af4-87fe-ee83d2948cde.png)

**Comment by TheCableGuy99** [comment]
Hi, I'm not quite sure I understand and think we might have our wires crossed so would like to explain again in more details to ensure you understand me correctly...

So let's take my laptop an an example... It has 2 ways of connecting (3 if you count Bluetooth) to the internet. Each of these 3 have their own mac address.

When I list then I set the same to "My Laptop - Ethernet" so I know exactly the device and how it's connecting. 

Now if I connect via Wi-Fi I have to create a duplicate entry for the same device so the wifi mac address is logged and the name as "My Laptop - Wi-Fi".

What I am proposing is adding a new drop down menu in the devices page that has just 3 options... 
Ethernet
Wi-Fi
Bluetooth

Thinking about it more, if the page could support multiple mac addresses with the drop down menu next to each one then we could just add a single entry for each device and it records all the mac addresses and what type of device it is.

I simple propose putting the drop down menu to the right of where the current mac address field is now and duplicate the two fields below twice so you can have up to 3 mac addresses and the type of connection it is next to each one.

The current mac address box field is far too big for a mad address anyway so it should fit nearly next to it.

Does that make sense?

**Comment by leiweibau** [comment]
> Can you add a drop down box to select if a device is Ethernet or Wi-Fi?
> 
> As some device have both it's important to log both so I currently have to add (Ethernet) or (Wi-Fi) in the suffix of the name to identify how it's connecting.

This is done. I may add another optional column to allow sorting by connection type.

> I would rather have an option to have device with ethernet and Wi-Fi - to be as one device instead of two. I case you use such device on ethernet and also on Wi-Fi (ie. laptop-wifi and docking station).

A consolidation of multiple Mac addresses based on a freely selectable hostname?

Will be too complicated for me.
Thought experiment: As long as I sort the devices by name, this may work at first. But I have to create a possibility to select both "interfaces" for processing in this device list, e.g. if you want to have different notifications. However, if I sort by IP or MAC (insert more examples here), then I need to remove this consolidation for these sorts again, otherwise the overview is lost.

If someone implements this elegantly, I will probably be happy to adopt it.

**Comment by leiweibau** [comment]
<img width="355" alt="preview" src="https://user-images.githubusercontent.com/105860611/225315387-32ded1ed-af9b-4f99-90be-a9be97bdc75f.png">
Even if "Ethernet" and "WiFi" are preset, you can still enter something of your own (e.g. wet shoelace)
It will be included in the next update

**Comment by TheCableGuy99** [comment]
yeah I know as I do that now but it's just a little something to make it that bit nicer :)

Just add "Bluetooth" in that list though please? Although it's not a common connection it still is used and has a mac address.

**Comment by TheCableGuy99** [comment]
thanks buddy. You can close this one as well now. Really appreciate all these tweaks, makes a difference :)

**Comment by leiweibau** [comment]
It will be included in the next update
