### ISSUE TITLE
[Feature Request] Wide screen

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#97]
As there are a few posts requesting additional data/columns in the details page, could you consider the ability to make the page wider to accommodate these? Maybe even the ability to specifically adjust the columns to a custom width by entering a pixel width for each column or re-sizing it like in excel by dragging it with the mouse? Not sure if that's possible but would be nice.

I think i'm all out of ideas now lol Thanks again for your consideration.

**Comment by leiweibau** [comment]
You can try this.
remove "layout-boxed" in the following line.

https://github.com/leiweibau/Pi.Alert/blob/ac31c86006092dc045cb5a604ae0e0a9023077bb/front/php/templates/header.php#L230

**Comment by TheCableGuy99** [comment]
perfect!!!!

The boxes adjust themselves I think to try accommodate any text that might spill over so I don't think it needs altering any more than that.

Going forward though will you be able to add something like a tick box or drop down menu which lets you decide which version you want? Or will I need to re-apply that edit each time?

**Comment by leiweibau** [comment]
The idea was good and the implementation on my part was long necessary. This layout will stay like this from now on :)

btw. Sorting by MAC-Address is broken. It will be fixed in the next update.

**Comment by TheCableGuy99** [comment]
brilliant, see you're already half way to doing half the request hehe thanks pal!

**Comment by leiweibau** [comment]
I have looked at a few plugins (ColReorder, Flutter) for Datatables that allow moving or changing columns. Sometimes these then break with certain browser versions. Also, I have to admit that I'm not completely comfortable with JS ;) So this feature will not be implemented on my part. Maybe there will be a pull request for this idea sometime.

**Comment by TheCableGuy99** [comment]
It's actually fine as it is now mate. The colums auto-adjust anyway and with the full screen there's more than enough room for content as I use it on my laptop mostly. Even though it still shrinks down pretty well on the mobile also. I don't think it really needs anything else and can probably close this now as far as I'm concerned. Cheers :)
