### ISSUE TITLE
[Feature Request] Ntfy

### ISSUE THREAD

**Issue by dude997** [leiweibau/Pi.Alert#98]
Could you add the abilty to use your own ntfy server in the pialert config and be able to set the priority level aswell thanks in advance

**Comment by leiweibau** [comment]
Ntfy is already integrated, or have I misunderstood something here?

What do you mean with "priority level"?

**Comment by dude997** [comment]
Sorry if i didnt explain it that well the notify server is set to use notify.sh and priority is set urgent in the pialert.py by default. iwould like to be able to change those as i run my own ntfy server
Example code in the pialert.py file
def send_ntfy_test (_notiMessage):
    requests.post("http://192.168.2.100:8025/{}".format(NTFY_TOPIC),
    data=_notiMessage,
    headers={
        "Title": "Pi.Alert Notification",
        "Click": REPORT_DASHBOARD_URL,
        "Priority": "default",
        "Tags": "warning"
    })
This is what i change it to but on an update i always have to reset it for both the alert and test alerts so an option to set the server and priority in the pi alert config through the gui would be helpful

**Comment by leiweibau** [comment]
Okay, i understand. I will change/add that.

**Comment by leiweibau** [comment]
Can you try this? I don't have NTFY infrastructure
https://github.com/leiweibau/Pi.Alert/commit/9037fc6e88d2e4e121c1ae21b9a567bc4cdf2e95

**Comment by leiweibau** [comment]
Sorry ... missed the "Test Notification" https://github.com/leiweibau/Pi.Alert/commit/ea2fd2767ef87f2f68b614fa0559b7297a7c8d9a

**Comment by dude997** [comment]
ok i can but i not sure how to add the modified files

**Comment by leiweibau** [comment]
I just pushed a fixed Version.
https://raw.githubusercontent.com/leiweibau/Pi.Alert/main/back/pialert.py

the new section in pialert.conf is:

# ntfy
# ----------------------
REPORT_NTFY         = False
REPORT_NTFY_WEBMON  = False
NTFY_HOST           = 'https://ntfy.sh'
NTFY_TOPIC          = 'replace_my_secure_topicname_91h889f28'
NTFY_USER           = 'user'
NTFY_PASSWORD	    = 'passw0rd'
NTFY_PRIORITY 	    = 'default'

The old ntfy section can be deleted.

**Comment by dude997** [comment]
yep the alerts are working thank you very much and thank you for trying to help me out with the vlans aswell

**Comment by leiweibau** [comment]
I will provide an update in the next few minutes. The update script will write the new entries into the config. Since you already have them, they would be written twice, which is nonsense. To avoid this, please replace the line "# ntfy" with "# ntfy (extended)" in pialert.conf before the update.

Thank you for your support as well.
