### ISSUE TITLE
Pihole more than one subnet(lan and vlan)

### ISSUE THREAD

**Issue by dude997** [leiweibau/Pi.Alert#99]
my pihole server gets dns requests from different subnets a main lan(192.168.1.0/24) and a vlan it(100.100.1.0/24).DHCP is done on the router and redirected to pihole which serves both no problem 
I have pi alert config set to 
PIHOLE_ACTIVE = True
PIHOLE_DB= '/etc/pihole/pihole-FTL.db'
SCAN_SUBNETS    = '192.168.1.0/24 100.100.1.0/24'  
but pialert only picks up the main lan subnet and never anything from the vlan is there something i need to set to make it see the devices on vlan

**Comment by leiweibau** [comment]
Unfortunately, I just took this section and hoped that everything would work.

Now that I have skimmed the topic again, I have to conclude for myself that probably the option you used must be wrong and I will remove this part from the configuration.

Consideration: Why do you use VLAN (formerly also simply called subnets)? To separate devices from each other, of course.

So why should it be possible for a device that is in one VLAN to scan all VLANs. This can only happen at a location where there is also access to all VLANs. And for this, as far as I know, an interface is required for each VLAN. At this point a configuration like "'192.168.1.0/24 --interface=eth1', '192.168.2.0/24 --interface=eth0'" should work.

Unfortunately I can't test this because I don't use VLANs/subnets. The thing is, ARP is not routed.

**Comment by dude997** [comment]
i use a vlan for a guest network to keep people and iot devices from accesing things on the main i don't want them to have access to for the pi hole part i thought it read the pihole-FTL.db to get other addresses arp didn't pick up and on my pihole it lists everything on the vlan as well as the main lan so i thought pialert would grab the vlan devices aswell but it doesnt seem to 
thankyou for responding to me

**Comment by leiweibau** [comment]
It should read the Pi-hole db. Is Pi.Alert installed in the same System as Pi-hole?

**Comment by dude997** [comment]
Yeah that's what i thought aswell and yes its is

**Comment by dude997** [comment]
when i run the scan manually this is the output
Pi.Alert (2023-03-11)
---------------------------------------------------------
Current User: root

Scan Devices
Timestamp: 2023-03-14 09:55:00

Scanning...
arp-scan Method...
arp-scan: One interface
Pi-hole Method...
DHCP Leases Method...

Processing scan results...
Devices Detected.......: 14
arp-scan Method....: 12
Pi-hole Method.....: +0
New Devices........: 0

**Comment by leiweibau** [comment]
Is Pi-hole the DHCP for your guest vlan?

**Comment by dude997** [comment]
no it is not the router is

**Comment by leiweibau** [comment]
Okay. This removes the possibility of discovering hosts using DHCP. Do you currently have devices on this network that have and use Internet access?

**Comment by leiweibau** [comment]
Can you find one of the devices you are missing in the scan result in Pi-hole -> Tools -> Network?

**Comment by dude997** [comment]
yes there are some devices on the vlan that use internet right now

**Comment by dude997** [comment]
yes i can see all the devices on the vlan under Pi-hole -> Tools -> Network

**Comment by dude997** [comment]
i can see under the hardware address for all on the vlan devices is displays N/A and all on the main lan give a mac address and what they are example ee:ee:ee:ee:ee:ee
Elitegroup Computer Systems Co.,Ltd.

**Comment by dude997** [comment]
it shows all ips for vlans though

**Comment by dude997** [comment]
ok i copy the database and change the permissions and path in the config

**Comment by dude997** [comment]
after copying the db to user directory set the permissions to 777 and change the path in the pialert.conf and running a manual scan i get the same results as before

**Comment by leiweibau** [comment]
I am just thinking through your hint that the missing MAC address could be the cause of the problem. I have to take a look at the database structure of Pi.Alert and Pi-hole. If I remember correctly, the MAC address should be the primary key in the Pi.Alert DB. And then the MAC address must not be the same for 5 or 10, not even for 2. 

So it is conceivable that these devices are simply ignored.

**Comment by dude997** [comment]
hmmm ok makes sense to me i will look into why my mac addresses are not showing up for the vlan

**Comment by dude997** [comment]
there is no N/A the output of the first command there is a bunch or mac addresses first followed by the ips on my vlan example ip-172.16.1.119
output from the second command just shows the all the vlan ips ie ip-172.16.1.119

**Comment by leiweibau** [comment]
all "ip-*" entries are ignored, and that makes sense for me.

https://github.com/leiweibau/Pi.Alert/blob/9037fc6e88d2e4e121c1ae21b9a567bc4cdf2e95/back/pialert.py#L665

So I can't do anything on my side for now. The only possibility I see is to get an interface into the vlan. How you do that, and whether it is worth the effort, I can not answer.

**Comment by jokob-sk** [comment]
I might be misunderstanding or wrong , but if the multiple subnets are implemented same as in my fork this approach could work: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SUBNETS.md

**Comment by leiweibau** [comment]
Do you see the "interface" parameter next to both vlans?

**Comment by leiweibau** [comment]
Whether it's a virtual interface or a physical one, but without an interface you can't get into another vlan. Otherwise the vlan makes no sense. It is supposed to segment the traffic.

It's different when it comes to the vlanID. Here you can assign multiple vlanIDs to a NIC or a port. Apart from the fact that so far all vlans are subnets for me. But that's probably because of my age ;)

**Comment by jokob-sk** [comment]
You definitely know more about networking than me, so I trust your answer 😁👍

**Comment by dude997** [comment]
yeah i tried the vlan tagging but that didn't work. It probally something that i have setup in the router preventing the arp-scan(because im definitely no networking expert). But i ended up being able to use nmap from my main subnet to my guest subnet (main can access guest but not vice versa). I made a little script that runs nmap stores the ips and hostnames to file and just sends an alert throught NTFY if it finds any new ips so at least i get an alert of new people on the network(all my devices are on staic ips so easy to tell)
